// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
@ffi.DefaultAsset('package:reactphysics3d_dart/reactphysics3d_dart.dart')
library;

import 'dart:ffi' as ffi;

/// ==================== PhysicsCommon (Factory) ====================
@ffi.Native<ffi.Pointer<RP3D_PhysicsCommon> Function()>(isLeaf: true)
external ffi.Pointer<RP3D_PhysicsCommon> rp3d_physics_common_create();

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_PhysicsCommon>)>(isLeaf: true)
external void rp3d_physics_common_destroy(
  ffi.Pointer<RP3D_PhysicsCommon> common,
);

@ffi.Native<
    ffi.Pointer<RP3D_PhysicsWorld> Function(
        ffi.Pointer<RP3D_PhysicsCommon>)>(isLeaf: true)
external ffi.Pointer<RP3D_PhysicsWorld>
    rp3d_physics_common_create_physics_world(
  ffi.Pointer<RP3D_PhysicsCommon> common,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Pointer<RP3D_PhysicsWorld>)>(isLeaf: true)
external void rp3d_physics_common_destroy_physics_world(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  ffi.Pointer<RP3D_PhysicsWorld> world,
);

/// Shape creation through PhysicsCommon
@ffi.Native<
    ffi.Pointer<RP3D_BoxShape> Function(ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external ffi.Pointer<RP3D_BoxShape> rp3d_physics_common_create_box_shape(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  ffi.Pointer<RP3D_Vector3> halfExtents,
);

@ffi.Native<
    ffi.Pointer<RP3D_SphereShape> Function(
        ffi.Pointer<RP3D_PhysicsCommon>, ffi.Float)>(isLeaf: true)
external ffi.Pointer<RP3D_SphereShape> rp3d_physics_common_create_sphere_shape(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  double radius,
);

@ffi.Native<
    ffi.Pointer<RP3D_CapsuleShape> Function(
        ffi.Pointer<RP3D_PhysicsCommon>, ffi.Float, ffi.Float)>(isLeaf: true)
external ffi.Pointer<RP3D_CapsuleShape>
    rp3d_physics_common_create_capsule_shape(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  double radius,
  double height,
);

/// HeightField creation/destruction (float data type)
@ffi.Native<
    ffi.Pointer<RP3D_HeightField> Function(
        ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Uint32,
        ffi.Uint32,
        ffi.Pointer<ffi.Float>,
        ffi.Float,
        ffi.Float,
        ffi.Pointer<ffi.Char>,
        ffi.Uint32)>(isLeaf: true)
external ffi.Pointer<RP3D_HeightField>
    rp3d_physics_common_create_height_field_float(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  int nbRows,
  int nbColumns,
  ffi.Pointer<ffi.Float> heights,
  double minHeight,
  double maxHeight,
  ffi.Pointer<ffi.Char> errorBuffer,
  int errorBufferSize,
);

/// HeightField creation/destruction (integer data type)
@ffi.Native<
    ffi.Pointer<RP3D_HeightField> Function(
        ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Uint32,
        ffi.Uint32,
        ffi.Pointer<ffi.Int32>,
        ffi.Float,
        ffi.Float,
        ffi.Double,
        ffi.Pointer<ffi.Char>,
        ffi.Uint32)>(isLeaf: true)
external ffi.Pointer<RP3D_HeightField>
    rp3d_physics_common_create_height_field_int(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  int nbRows,
  int nbColumns,
  ffi.Pointer<ffi.Int32> heights,
  double minHeight,
  double maxHeight,
  double integerHeightScale,
  ffi.Pointer<ffi.Char> errorBuffer,
  int errorBufferSize,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Pointer<RP3D_HeightField>)>(isLeaf: true)
external void rp3d_physics_common_destroy_height_field(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  ffi.Pointer<RP3D_HeightField> heightField,
);

/// HeightFieldShape creation/destruction
@ffi.Native<
    ffi.Pointer<RP3D_HeightFieldShape> Function(ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Pointer<RP3D_HeightField>, ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external ffi.Pointer<RP3D_HeightFieldShape>
    rp3d_physics_common_create_height_field_shape(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  ffi.Pointer<RP3D_HeightField> heightField,
  ffi.Pointer<RP3D_Vector3> scaling,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Pointer<RP3D_HeightFieldShape>)>(isLeaf: true)
external void rp3d_physics_common_destroy_height_field_shape(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  ffi.Pointer<RP3D_HeightFieldShape> heightFieldShape,
);

/// TriangleVertexArray creation/destruction
@ffi.Native<
    ffi.Pointer<RP3D_TriangleVertexArray> Function(
        ffi.Uint32,
        ffi.Pointer<ffi.Float>,
        ffi.Uint32,
        ffi.Uint32,
        ffi.Pointer<ffi.Uint32>,
        ffi.Uint32)>(isLeaf: true)
external ffi.Pointer<RP3D_TriangleVertexArray>
    rp3d_triangle_vertex_array_create(
  int nbVertices,
  ffi.Pointer<ffi.Float> verticesStart,
  int verticesStride,
  int nbIndices,
  ffi.Pointer<ffi.Uint32> indicesStart,
  int indicesStride,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_TriangleVertexArray>)>(
    isLeaf: true)
external void rp3d_triangle_vertex_array_destroy(
  ffi.Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
);

/// TriangleVertexArray accessors
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<RP3D_TriangleVertexArray>)>(
    isLeaf: true)
external int rp3d_triangle_vertex_array_get_nb_vertices(
  ffi.Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<RP3D_TriangleVertexArray>)>(
    isLeaf: true)
external int rp3d_triangle_vertex_array_get_nb_triangles(
  ffi.Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
);

@ffi.Native<
    ffi.Pointer<ffi.Float> Function(
        ffi.Pointer<RP3D_TriangleVertexArray>)>(isLeaf: true)
external ffi.Pointer<ffi.Float> rp3d_triangle_vertex_array_get_vertices_start(
  ffi.Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
);

@ffi.Native<
    ffi.Pointer<ffi.Uint32> Function(
        ffi.Pointer<RP3D_TriangleVertexArray>)>(isLeaf: true)
external ffi.Pointer<ffi.Uint32> rp3d_triangle_vertex_array_get_indices_start(
  ffi.Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_TriangleVertexArray>, ffi.Uint32,
        ffi.Pointer<ffi.Uint32>)>(isLeaf: true)
external void rp3d_triangle_vertex_array_get_triangle_vertices_indices(
  ffi.Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
  int triangleIndex,
  ffi.Pointer<ffi.Uint32> out,
);

/// PolygonVertexArray creation/destruction
@ffi.Native<
    ffi.Pointer<RP3D_PolygonVertexArray> Function(
        ffi.Uint32,
        ffi.Pointer<ffi.Float>,
        ffi.Uint32,
        ffi.Uint32,
        ffi.Pointer<ffi.Uint32>,
        ffi.Uint32,
        ffi.Pointer<ffi.Uint32>,
        ffi.Uint32)>(isLeaf: true)
external ffi.Pointer<RP3D_PolygonVertexArray> rp3d_polygon_vertex_array_create(
  int nbVertices,
  ffi.Pointer<ffi.Float> verticesStart,
  int verticesStride,
  int nbIndices,
  ffi.Pointer<ffi.Uint32> indicesStart,
  int indicesStride,
  ffi.Pointer<ffi.Uint32> polygonIndicesStart,
  int polygonIndicesStride,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_PolygonVertexArray>)>(
    isLeaf: true)
external void rp3d_polygon_vertex_array_destroy(
  ffi.Pointer<RP3D_PolygonVertexArray> polygonVertexArray,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<RP3D_PolygonVertexArray>)>(
    isLeaf: true)
external int rp3d_polygon_vertex_array_get_nb_vertices(
  ffi.Pointer<RP3D_PolygonVertexArray> polygonVertexArray,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<RP3D_PolygonVertexArray>)>(
    isLeaf: true)
external int rp3d_polygon_vertex_array_get_nb_faces(
  ffi.Pointer<RP3D_PolygonVertexArray> polygonVertexArray,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PolygonVertexArray>, ffi.Uint32,
        ffi.Pointer<ffi.Float>)>(isLeaf: true)
external void rp3d_polygon_vertex_array_get_vertex(
  ffi.Pointer<RP3D_PolygonVertexArray> polygonVertexArray,
  int vertexIndex,
  ffi.Pointer<ffi.Float> outVertex,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PolygonVertexArray>, ffi.Uint32,
        ffi.Pointer<ffi.Uint32>, ffi.Pointer<ffi.Uint32>)>(isLeaf: true)
external void rp3d_polygon_vertex_array_get_polygon_face(
  ffi.Pointer<RP3D_PolygonVertexArray> polygonVertexArray,
  int faceIndex,
  ffi.Pointer<ffi.Uint32> outNbVertices,
  ffi.Pointer<ffi.Uint32> outIndexBase,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<RP3D_PolygonVertexArray>)>(
    isLeaf: true)
external int rp3d_polygon_vertex_array_get_indices_stride(
  ffi.Pointer<RP3D_PolygonVertexArray> polygonVertexArray,
);

@ffi.Native<
    ffi.Pointer<ffi.Uint32> Function(
        ffi.Pointer<RP3D_PolygonVertexArray>)>(isLeaf: true)
external ffi.Pointer<ffi.Uint32> rp3d_polygon_vertex_array_get_indices_start(
  ffi.Pointer<RP3D_PolygonVertexArray> polygonVertexArray,
);

@ffi.Native<
    ffi.Uint32 Function(ffi.Pointer<RP3D_PolygonVertexArray>, ffi.Uint32,
        ffi.Uint32)>(isLeaf: true)
external int rp3d_polygon_vertex_array_get_vertex_index_in_face(
  ffi.Pointer<RP3D_PolygonVertexArray> polygonVertexArray,
  int faceIndex,
  int vertexInFace,
);

/// VertexArray creation/destruction
@ffi.Native<
    ffi.Pointer<RP3D_VertexArray> Function(
        ffi.Uint32, ffi.Pointer<ffi.Float>, ffi.Uint32)>(isLeaf: true)
external ffi.Pointer<RP3D_VertexArray> rp3d_vertex_array_create(
  int nbVertices,
  ffi.Pointer<ffi.Float> verticesStart,
  int verticesStride,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_VertexArray>)>(isLeaf: true)
external void rp3d_vertex_array_destroy(
  ffi.Pointer<RP3D_VertexArray> vertexArray,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<RP3D_VertexArray>)>(isLeaf: true)
external int rp3d_vertex_array_get_nb_vertices(
  ffi.Pointer<RP3D_VertexArray> vertexArray,
);

@ffi.Native<ffi.Pointer<ffi.Float> Function(ffi.Pointer<RP3D_VertexArray>)>(
    isLeaf: true)
external ffi.Pointer<ffi.Float> rp3d_vertex_array_get_vertices_start(
  ffi.Pointer<RP3D_VertexArray> vertexArray,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<RP3D_VertexArray>)>(isLeaf: true)
external int rp3d_vertex_array_get_stride(
  ffi.Pointer<RP3D_VertexArray> vertexArray,
);

/// TriangleMesh creation/destruction
@ffi.Native<
    ffi.Pointer<RP3D_TriangleMesh> Function(ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Pointer<RP3D_TriangleVertexArray>)>(isLeaf: true)
external ffi.Pointer<RP3D_TriangleMesh>
    rp3d_physics_common_create_triangle_mesh(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  ffi.Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Pointer<RP3D_TriangleMesh>)>(isLeaf: true)
external void rp3d_physics_common_destroy_triangle_mesh(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  ffi.Pointer<RP3D_TriangleMesh> triangleMesh,
);

/// TriangleMesh accessors
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<RP3D_TriangleMesh>)>(isLeaf: true)
external int rp3d_triangle_mesh_get_nb_vertices(
  ffi.Pointer<RP3D_TriangleMesh> triangleMesh,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<RP3D_TriangleMesh>)>(isLeaf: true)
external int rp3d_triangle_mesh_get_nb_triangles(
  ffi.Pointer<RP3D_TriangleMesh> triangleMesh,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_TriangleMesh>, ffi.Uint32,
        ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external void rp3d_triangle_mesh_get_vertex(
  ffi.Pointer<RP3D_TriangleMesh> triangleMesh,
  int vertexIndex,
  ffi.Pointer<RP3D_Vector3> outVertex,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_TriangleMesh>, ffi.Uint32,
        ffi.Pointer<ffi.Uint32>)>(isLeaf: true)
external void rp3d_triangle_mesh_get_triangle_vertices_indices(
  ffi.Pointer<RP3D_TriangleMesh> triangleMesh,
  int triangleIndex,
  ffi.Pointer<ffi.Uint32> indices,
);

/// ConvexMesh creation/destruction
@ffi.Native<
    ffi.Pointer<RP3D_ConvexMesh> Function(ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Pointer<RP3D_TriangleVertexArray>)>(isLeaf: true)
external ffi.Pointer<RP3D_ConvexMesh>
    rp3d_physics_common_create_convex_mesh_from_triangles(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  ffi.Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
);

@ffi.Native<
    ffi.Pointer<RP3D_ConvexMesh> Function(ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Pointer<RP3D_PolygonVertexArray>)>(isLeaf: true)
external ffi.Pointer<RP3D_ConvexMesh>
    rp3d_physics_common_create_convex_mesh_from_polygons(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  ffi.Pointer<RP3D_PolygonVertexArray> polygonVertexArray,
);

@ffi.Native<
    ffi.Pointer<RP3D_ConvexMesh> Function(ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Pointer<RP3D_VertexArray>)>(isLeaf: true)
external ffi.Pointer<RP3D_ConvexMesh>
    rp3d_physics_common_create_convex_mesh_from_vertices(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  ffi.Pointer<RP3D_VertexArray> vertexArray,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Pointer<RP3D_ConvexMesh>)>(isLeaf: true)
external void rp3d_physics_common_destroy_convex_mesh(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  ffi.Pointer<RP3D_ConvexMesh> convexMesh,
);

/// ConvexMeshShape creation/destruction
@ffi.Native<
    ffi.Pointer<RP3D_ConvexMeshShape> Function(ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Pointer<RP3D_ConvexMesh>, ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external ffi.Pointer<RP3D_ConvexMeshShape>
    rp3d_physics_common_create_convex_mesh_shape(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  ffi.Pointer<RP3D_ConvexMesh> convexMesh,
  ffi.Pointer<RP3D_Vector3> scaling,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Pointer<RP3D_ConvexMeshShape>)>(isLeaf: true)
external void rp3d_physics_common_destroy_convex_mesh_shape(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  ffi.Pointer<RP3D_ConvexMeshShape> convexMeshShape,
);

/// ConcaveMeshShape creation/destruction
@ffi.Native<
    ffi.Pointer<RP3D_ConcaveMeshShape> Function(
        ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Pointer<RP3D_TriangleMesh>,
        ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external ffi.Pointer<RP3D_ConcaveMeshShape>
    rp3d_physics_common_create_concave_mesh_shape(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  ffi.Pointer<RP3D_TriangleMesh> triangleMesh,
  ffi.Pointer<RP3D_Vector3> scaling,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Pointer<RP3D_ConcaveMeshShape>)>(isLeaf: true)
external void rp3d_physics_common_destroy_concave_mesh_shape(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  ffi.Pointer<RP3D_ConcaveMeshShape> concaveMeshShape,
);

/// Mesh/shape destruction
@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Pointer<RP3D_BoxShape>)>(isLeaf: true)
external void rp3d_physics_common_destroy_box_shape(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  ffi.Pointer<RP3D_BoxShape> shape,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Pointer<RP3D_SphereShape>)>(isLeaf: true)
external void rp3d_physics_common_destroy_sphere_shape(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  ffi.Pointer<RP3D_SphereShape> shape,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PhysicsCommon>,
        ffi.Pointer<RP3D_CapsuleShape>)>(isLeaf: true)
external void rp3d_physics_common_destroy_capsule_shape(
  ffi.Pointer<RP3D_PhysicsCommon> common,
  ffi.Pointer<RP3D_CapsuleShape> shape,
);

/// ==================== PhysicsWorld ====================
@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_PhysicsWorld>, ffi.Float)>(
    isLeaf: true)
external void rp3d_world_update(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  double timeStep,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PhysicsWorld>,
        ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external void rp3d_world_set_gravity(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  ffi.Pointer<RP3D_Vector3> gravity,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PhysicsWorld>,
        ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external void rp3d_world_get_gravity(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  ffi.Pointer<RP3D_Vector3> outGravity,
);

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<RP3D_PhysicsWorld>)>(isLeaf: true)
external int rp3d_world_get_is_sleeping_enabled(
  ffi.Pointer<RP3D_PhysicsWorld> world,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_PhysicsWorld>, ffi.Uint8)>(
    isLeaf: true)
external void rp3d_world_set_is_sleeping_enabled(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  int isSleepingEnabled,
);

/// Gravity and sleep control
@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_PhysicsWorld>, ffi.Uint8)>(
    isLeaf: true)
external void rp3d_world_set_is_gravity_enabled(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  int isGravityEnabled,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_PhysicsWorld>, ffi.Float)>(
    isLeaf: true)
external void rp3d_world_set_sleep_linear_velocity(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  double sleepLinearVelocity,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_PhysicsWorld>, ffi.Float)>(
    isLeaf: true)
external void rp3d_world_set_sleep_angular_velocity(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  double sleepAngularVelocity,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_PhysicsWorld>, ffi.Float)>(
    isLeaf: true)
external void rp3d_world_set_time_before_sleep(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  double timeBeforeSleep,
);

/// Debug rendering
@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_PhysicsWorld>, ffi.Uint8)>(
    isLeaf: true)
external void rp3d_world_set_is_debug_rendering_enabled(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  int isEnabled,
);

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<RP3D_PhysicsWorld>)>(isLeaf: true)
external int rp3d_world_get_is_debug_rendering_enabled(
  ffi.Pointer<RP3D_PhysicsWorld> world,
);

@ffi.Native<
    ffi.Pointer<RP3D_DebugRenderer> Function(
        ffi.Pointer<RP3D_PhysicsWorld>)>(isLeaf: true)
external ffi.Pointer<RP3D_DebugRenderer> rp3d_world_get_debug_renderer(
  ffi.Pointer<RP3D_PhysicsWorld> world,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<RP3D_PhysicsWorld>)>(isLeaf: true)
external int rp3d_world_get_nb_rigid_bodies(
  ffi.Pointer<RP3D_PhysicsWorld> world,
);

@ffi.Native<
    ffi.Pointer<RP3D_RigidBody> Function(
        ffi.Pointer<RP3D_PhysicsWorld>, ffi.Uint32)>(isLeaf: true)
external ffi.Pointer<RP3D_RigidBody> rp3d_world_get_rigid_body(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  int index,
);

/// Body creation/destruction
@ffi.Native<
    ffi.Pointer<RP3D_RigidBody> Function(ffi.Pointer<RP3D_PhysicsWorld>,
        ffi.Pointer<RP3D_Transform>)>(isLeaf: true)
external ffi.Pointer<RP3D_RigidBody> rp3d_world_create_rigid_body(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  ffi.Pointer<RP3D_Transform> transform,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PhysicsWorld>,
        ffi.Pointer<RP3D_RigidBody>)>(isLeaf: true)
external void rp3d_world_destroy_rigid_body(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  ffi.Pointer<RP3D_RigidBody> body,
);

/// Raycasting
@ffi.Native<
    ffi.Uint8 Function(ffi.Pointer<RP3D_PhysicsWorld>, ffi.Pointer<RP3D_Ray>,
        ffi.Pointer<RP3D_RaycastInfo>)>(isLeaf: true)
external int rp3d_world_raycast(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  ffi.Pointer<RP3D_Ray> ray,
  ffi.Pointer<RP3D_RaycastInfo> raycastInfo,
);

/// ==================== RigidBody ====================
@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<RP3D_RigidBody>, ffi.Pointer<RP3D_Transform>)>(isLeaf: true)
external void rp3d_body_get_transform(
  ffi.Pointer<RP3D_RigidBody> body,
  ffi.Pointer<RP3D_Transform> outTransform,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_RigidBody>, ffi.Float, ffi.Float,
        ffi.Float, ffi.Float, ffi.Float, ffi.Float, ffi.Float)>(isLeaf: true)
external void rp3d_body_set_transform(
  ffi.Pointer<RP3D_RigidBody> body,
  double posX,
  double posY,
  double posZ,
  double quatX,
  double quatY,
  double quatZ,
  double quatW,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<RP3D_RigidBody>, ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external void rp3d_body_get_position(
  ffi.Pointer<RP3D_RigidBody> body,
  ffi.Pointer<RP3D_Vector3> outPosition,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_RigidBody>,
        ffi.Pointer<RP3D_Quaternion>)>(isLeaf: true)
external void rp3d_body_get_orientation(
  ffi.Pointer<RP3D_RigidBody> body,
  ffi.Pointer<RP3D_Quaternion> outOrientation,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_RigidBody>, ffi.UnsignedInt)>(
    isLeaf: true)
external void rp3d_body_set_type(
  ffi.Pointer<RP3D_RigidBody> body,
  int type,
);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<RP3D_RigidBody>)>(isLeaf: true)
external int rp3d_body_get_type(
  ffi.Pointer<RP3D_RigidBody> body,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_RigidBody>, ffi.Float)>(
    isLeaf: true)
external void rp3d_body_set_mass(
  ffi.Pointer<RP3D_RigidBody> body,
  double mass,
);

@ffi.Native<ffi.Float Function(ffi.Pointer<RP3D_RigidBody>)>(isLeaf: true)
external double rp3d_body_get_mass(
  ffi.Pointer<RP3D_RigidBody> body,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<RP3D_RigidBody>, ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external void rp3d_body_set_linear_velocity(
  ffi.Pointer<RP3D_RigidBody> body,
  ffi.Pointer<RP3D_Vector3> linearVelocity,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<RP3D_RigidBody>, ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external void rp3d_body_get_linear_velocity(
  ffi.Pointer<RP3D_RigidBody> body,
  ffi.Pointer<RP3D_Vector3> outLinearVelocity,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<RP3D_RigidBody>, ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external void rp3d_body_set_angular_velocity(
  ffi.Pointer<RP3D_RigidBody> body,
  ffi.Pointer<RP3D_Vector3> angularVelocity,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<RP3D_RigidBody>, ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external void rp3d_body_get_angular_velocity(
  ffi.Pointer<RP3D_RigidBody> body,
  ffi.Pointer<RP3D_Vector3> outAngularVelocity,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<RP3D_RigidBody>, ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external void rp3d_body_apply_force(
  ffi.Pointer<RP3D_RigidBody> body,
  ffi.Pointer<RP3D_Vector3> force,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_RigidBody>, ffi.Pointer<RP3D_Vector3>,
        ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external void rp3d_body_apply_force_at_position(
  ffi.Pointer<RP3D_RigidBody> body,
  ffi.Pointer<RP3D_Vector3> force,
  ffi.Pointer<RP3D_Vector3> position,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<RP3D_RigidBody>, ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external void rp3d_body_apply_torque(
  ffi.Pointer<RP3D_RigidBody> body,
  ffi.Pointer<RP3D_Vector3> torque,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_RigidBody>, ffi.Uint8)>(
    isLeaf: true)
external void rp3d_body_set_is_active(
  ffi.Pointer<RP3D_RigidBody> body,
  int isActive,
);

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<RP3D_RigidBody>)>(isLeaf: true)
external int rp3d_body_get_is_active(
  ffi.Pointer<RP3D_RigidBody> body,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_RigidBody>, ffi.Uint8)>(
    isLeaf: true)
external void rp3d_body_set_is_sleeping_allowed(
  ffi.Pointer<RP3D_RigidBody> body,
  int isAllowed,
);

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<RP3D_RigidBody>)>(isLeaf: true)
external int rp3d_body_get_is_sleeping_allowed(
  ffi.Pointer<RP3D_RigidBody> body,
);

/// Gravity control
@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_RigidBody>, ffi.Uint8)>(
    isLeaf: true)
external void rp3d_body_enable_gravity(
  ffi.Pointer<RP3D_RigidBody> body,
  int enableGravity,
);

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<RP3D_RigidBody>)>(isLeaf: true)
external int rp3d_body_is_gravity_enabled(
  ffi.Pointer<RP3D_RigidBody> body,
);

/// Debug rendering
@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_RigidBody>, ffi.Uint8)>(
    isLeaf: true)
external void rp3d_body_set_is_debug_enabled(
  ffi.Pointer<RP3D_RigidBody> body,
  int isEnabled,
);

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<RP3D_RigidBody>)>(isLeaf: true)
external int rp3d_body_get_is_debug_enabled(
  ffi.Pointer<RP3D_RigidBody> body,
);

/// Mass properties
@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_RigidBody>)>(isLeaf: true)
external void rp3d_body_update_mass_properties_from_colliders(
  ffi.Pointer<RP3D_RigidBody> body,
);

/// Collider management
@ffi.Native<
    ffi.Pointer<RP3D_Collider> Function(
        ffi.Pointer<RP3D_RigidBody>,
        ffi.Pointer<RP3D_CollisionShape>,
        ffi.Pointer<RP3D_Transform>)>(isLeaf: true)
external ffi.Pointer<RP3D_Collider> rp3d_body_add_collider(
  ffi.Pointer<RP3D_RigidBody> body,
  ffi.Pointer<RP3D_CollisionShape> shape,
  ffi.Pointer<RP3D_Transform> transform,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<RP3D_RigidBody>, ffi.Pointer<RP3D_Collider>)>(isLeaf: true)
external void rp3d_body_remove_collider(
  ffi.Pointer<RP3D_RigidBody> body,
  ffi.Pointer<RP3D_Collider> collider,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<RP3D_Collider>, ffi.Pointer<RP3D_Material>)>(isLeaf: true)
external void rp3d_collider_set_material(
  ffi.Pointer<RP3D_Collider> collider,
  ffi.Pointer<RP3D_Material> material,
);

/// ==================== Collider ====================
@ffi.Native<ffi.Pointer<RP3D_Material> Function(ffi.Pointer<RP3D_Collider>)>(
    isLeaf: true)
external ffi.Pointer<RP3D_Material> rp3d_collider_get_material(
  ffi.Pointer<RP3D_Collider> collider,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<RP3D_Collider>, ffi.Pointer<RP3D_AABB>)>(isLeaf: true)
external void rp3d_collider_get_local_bounds(
  ffi.Pointer<RP3D_Collider> collider,
  ffi.Pointer<RP3D_AABB> outAABB,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_Collider>, ffi.Uint8)>(
    isLeaf: true)
external void rp3d_collider_set_is_trigger(
  ffi.Pointer<RP3D_Collider> collider,
  int isTrigger,
);

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<RP3D_Collider>)>(isLeaf: true)
external int rp3d_collider_get_is_trigger(
  ffi.Pointer<RP3D_Collider> collider,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_Collider>, ffi.Uint8)>(
    isLeaf: true)
external void rp3d_collider_set_is_world_query_collider(
  ffi.Pointer<RP3D_Collider> collider,
  int isWorldQueryCollider,
);

@ffi.Native<ffi.Uint8 Function(ffi.Pointer<RP3D_Collider>)>(isLeaf: true)
external int rp3d_collider_get_is_world_query_collider(
  ffi.Pointer<RP3D_Collider> collider,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_Collider>, ffi.UnsignedShort)>(
    isLeaf: true)
external void rp3d_collider_set_collision_category_bits(
  ffi.Pointer<RP3D_Collider> collider,
  int collisionCategoryBits,
);

@ffi.Native<ffi.UnsignedShort Function(ffi.Pointer<RP3D_Collider>)>(
    isLeaf: true)
external int rp3d_collider_get_collision_category_bits(
  ffi.Pointer<RP3D_Collider> collider,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_Collider>, ffi.UnsignedShort)>(
    isLeaf: true)
external void rp3d_collider_set_collide_with_mask_bits(
  ffi.Pointer<RP3D_Collider> collider,
  int collideWithMaskBits,
);

@ffi.Native<ffi.UnsignedShort Function(ffi.Pointer<RP3D_Collider>)>(
    isLeaf: true)
external int rp3d_collider_get_collide_with_mask_bits(
  ffi.Pointer<RP3D_Collider> collider,
);

/// ==================== Material ====================
@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_Material>)>(isLeaf: true)
external void rp3d_material_destroy(
  ffi.Pointer<RP3D_Material> material,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_Material>, ffi.Float)>(
    isLeaf: true)
external void rp3d_material_set_bounciness(
  ffi.Pointer<RP3D_Material> material,
  double bounciness,
);

@ffi.Native<ffi.Float Function(ffi.Pointer<RP3D_Material>)>(isLeaf: true)
external double rp3d_material_get_bounciness(
  ffi.Pointer<RP3D_Material> material,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_Material>, ffi.Float)>(
    isLeaf: true)
external void rp3d_material_set_friction_coefficient(
  ffi.Pointer<RP3D_Material> material,
  double frictionCoefficient,
);

@ffi.Native<ffi.Float Function(ffi.Pointer<RP3D_Material>)>(isLeaf: true)
external double rp3d_material_get_friction_coefficient(
  ffi.Pointer<RP3D_Material> material,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_Material>, ffi.Float)>(
    isLeaf: true)
external void rp3d_material_set_mass_density(
  ffi.Pointer<RP3D_Material> material,
  double massDensity,
);

@ffi.Native<ffi.Float Function(ffi.Pointer<RP3D_Material>)>(isLeaf: true)
external double rp3d_material_get_mass_density(
  ffi.Pointer<RP3D_Material> material,
);

/// ==================== CollisionShape (base) ====================
@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<RP3D_CollisionShape>, ffi.Pointer<RP3D_AABB>)>(isLeaf: true)
external void rp3d_shape_get_local_bounds(
  ffi.Pointer<RP3D_CollisionShape> shape,
  ffi.Pointer<RP3D_AABB> outAABB,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_HeightFieldShape>,
        ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external void rp3d_concave_shape_set_scale(
  ffi.Pointer<RP3D_HeightFieldShape> shape,
  ffi.Pointer<RP3D_Vector3> scale,
);

/// ==================== HeightFieldShape ====================
@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_HeightFieldShape>, ffi.Uint32,
        ffi.Uint32, ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external void rp3d_height_field_shape_get_vertex_at(
  ffi.Pointer<RP3D_HeightFieldShape> heightFieldShape,
  int row,
  int column,
  ffi.Pointer<RP3D_Vector3> outVertex,
);

/// Vector3
@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external void rp3d_vector3_zero(
  ffi.Pointer<RP3D_Vector3> v,
);

@ffi.Native<ffi.Float Function(ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external double rp3d_vector3_length(
  ffi.Pointer<RP3D_Vector3> v,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external void rp3d_vector3_normalize(
  ffi.Pointer<RP3D_Vector3> v,
);

@ffi.Native<
    ffi.Float Function(
        ffi.Pointer<RP3D_Vector3>, ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external double rp3d_vector3_dot(
  ffi.Pointer<RP3D_Vector3> v1,
  ffi.Pointer<RP3D_Vector3> v2,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_Vector3>, ffi.Pointer<RP3D_Vector3>,
        ffi.Pointer<RP3D_Vector3>)>(isLeaf: true)
external void rp3d_vector3_cross(
  ffi.Pointer<RP3D_Vector3> v1,
  ffi.Pointer<RP3D_Vector3> v2,
  ffi.Pointer<RP3D_Vector3> outResult,
);

/// Quaternion
@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_Quaternion>)>(isLeaf: true)
external void rp3d_quaternion_identity(
  ffi.Pointer<RP3D_Quaternion> q,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_Vector3>, ffi.Float,
        ffi.Pointer<RP3D_Quaternion>)>(isLeaf: true)
external void rp3d_quaternion_from_axis_angle(
  ffi.Pointer<RP3D_Vector3> axis,
  double angle,
  ffi.Pointer<RP3D_Quaternion> outQuat,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_Quaternion>)>(isLeaf: true)
external void rp3d_quaternion_normalize(
  ffi.Pointer<RP3D_Quaternion> q,
);

/// Transform
@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_Transform>)>(isLeaf: true)
external void rp3d_transform_identity(
  ffi.Pointer<RP3D_Transform> t,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<RP3D_Transform>, ffi.Pointer<RP3D_Transform>)>(isLeaf: true)
external void rp3d_transform_inverse(
  ffi.Pointer<RP3D_Transform> t,
  ffi.Pointer<RP3D_Transform> outInverse,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<RP3D_Transform>, ffi.Pointer<ffi.Float>)>(isLeaf: true)
external void rp3d_transform_get_opengl_matrix(
  ffi.Pointer<RP3D_Transform> t,
  ffi.Pointer<ffi.Float> outMatrix,
);

/// ==================== DebugRenderer ====================
@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_DebugRenderer>, ffi.UnsignedInt,
        ffi.Uint8)>(isLeaf: true)
external void rp3d_debug_renderer_set_is_debug_item_displayed(
  ffi.Pointer<RP3D_DebugRenderer> renderer,
  int item,
  int isDisplayed,
);

@ffi.Native<
    ffi.Uint8 Function(
        ffi.Pointer<RP3D_DebugRenderer>, ffi.UnsignedInt)>(isLeaf: true)
external int rp3d_debug_renderer_get_is_debug_item_displayed(
  ffi.Pointer<RP3D_DebugRenderer> renderer,
  int item,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<RP3D_DebugRenderer>)>(isLeaf: true)
external int rp3d_debug_renderer_get_nb_lines(
  ffi.Pointer<RP3D_DebugRenderer> renderer,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<RP3D_DebugRenderer>)>(isLeaf: true)
external int rp3d_debug_renderer_get_nb_triangles(
  ffi.Pointer<RP3D_DebugRenderer> renderer,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_DebugRenderer>, ffi.Pointer<ffi.Float>,
        ffi.Pointer<ffi.Uint32>)>(isLeaf: true)
external void rp3d_debug_renderer_get_lines_array(
  ffi.Pointer<RP3D_DebugRenderer> renderer,
  ffi.Pointer<ffi.Float> outVertices,
  ffi.Pointer<ffi.Uint32> outColors,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_DebugRenderer>, ffi.Pointer<ffi.Float>,
        ffi.Pointer<ffi.Uint32>)>(isLeaf: true)
external void rp3d_debug_renderer_get_triangles_array(
  ffi.Pointer<RP3D_DebugRenderer> renderer,
  ffi.Pointer<ffi.Float> outVertices,
  ffi.Pointer<ffi.Uint32> outColors,
);

/// ==================== Joints ====================
@ffi.Native<
    ffi.Pointer<RP3D_BallAndSocketJoint> Function(
        ffi.Pointer<RP3D_PhysicsWorld>,
        ffi.Pointer<RP3D_BallAndSocketJointInfo>)>(isLeaf: true)
external ffi.Pointer<RP3D_BallAndSocketJoint>
    rp3d_world_create_ball_and_socket_joint(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  ffi.Pointer<RP3D_BallAndSocketJointInfo> jointInfo,
);

@ffi.Native<
    ffi.Pointer<RP3D_HingeJoint> Function(ffi.Pointer<RP3D_PhysicsWorld>,
        ffi.Pointer<RP3D_HingeJointInfo>)>(isLeaf: true)
external ffi.Pointer<RP3D_HingeJoint> rp3d_world_create_hinge_joint(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  ffi.Pointer<RP3D_HingeJointInfo> jointInfo,
);

@ffi.Native<
    ffi.Pointer<RP3D_SliderJoint> Function(ffi.Pointer<RP3D_PhysicsWorld>,
        ffi.Pointer<RP3D_SliderJointInfo>)>(isLeaf: true)
external ffi.Pointer<RP3D_SliderJoint> rp3d_world_create_slider_joint(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  ffi.Pointer<RP3D_SliderJointInfo> jointInfo,
);

@ffi.Native<
    ffi.Pointer<RP3D_FixedJoint> Function(ffi.Pointer<RP3D_PhysicsWorld>,
        ffi.Pointer<RP3D_FixedJointInfo>)>(isLeaf: true)
external ffi.Pointer<RP3D_FixedJoint> rp3d_world_create_fixed_joint(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  ffi.Pointer<RP3D_FixedJointInfo> jointInfo,
);

@ffi.Native<
    ffi.Void Function(
        ffi.Pointer<RP3D_PhysicsWorld>, ffi.Pointer<ffi.Void>)>(isLeaf: true)
external void rp3d_world_destroy_joint(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  ffi.Pointer<ffi.Void> joint,
);

/// Create callbacks
@ffi.Native<
    ffi.Pointer<TCollisionCallback> Function(
        ffi.Pointer<ffi.Char>, ffi.Uint8, ffi.Uint8)>(isLeaf: true)
external ffi.Pointer<TCollisionCallback> rp3d_create_logging_collision_callback(
  ffi.Pointer<ffi.Char> prefix,
  int logContactPoints,
  int verbose,
);

@ffi.Native<ffi.Pointer<TCollisionCallback> Function()>(isLeaf: true)
external ffi.Pointer<TCollisionCallback> rp3d_create_contact_counter_callback();

/// Get callback properties
@ffi.Native<ffi.Uint8 Function(ffi.Pointer<TCollisionCallback>)>(isLeaf: true)
external int rp3d_get_logging_callback_has_contact(
  ffi.Pointer<TCollisionCallback> callback,
);

/// Get callback statistics
@ffi.Native<
    ffi.Void Function(ffi.Pointer<TCollisionCallback>, ffi.Pointer<ffi.Uint32>,
        ffi.Pointer<ffi.Uint32>, ffi.Pointer<ffi.Uint32>)>(isLeaf: true)
external void rp3d_get_logging_callback_stats(
  ffi.Pointer<TCollisionCallback> callback,
  ffi.Pointer<ffi.Uint32> callbackCount,
  ffi.Pointer<ffi.Uint32> totalContactPairs,
  ffi.Pointer<ffi.Uint32> totalContactPoints,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<TCollisionCallback>, ffi.Pointer<ffi.Uint32>,
        ffi.Pointer<ffi.Uint32>, ffi.Pointer<ffi.Uint32>)>(isLeaf: true)
external void rp3d_get_counter_callback_stats(
  ffi.Pointer<TCollisionCallback> callback,
  ffi.Pointer<ffi.Uint32> callbackCount,
  ffi.Pointer<ffi.Uint32> totalContactPairs,
  ffi.Pointer<ffi.Uint32> totalContactPoints,
);

/// Reset callback statistics
@ffi.Native<ffi.Void Function(ffi.Pointer<TCollisionCallback>)>(isLeaf: true)
external void rp3d_reset_callback_stats(
  ffi.Pointer<TCollisionCallback> callback,
);

/// Collision testing with callbacks
@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PhysicsWorld>, ffi.Pointer<RP3D_Body>,
        ffi.Pointer<RP3D_Body>, ffi.Pointer<TCollisionCallback>)>(isLeaf: true)
external void rp3d_test_collision_bodies_direct(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  ffi.Pointer<RP3D_Body> body1,
  ffi.Pointer<RP3D_Body> body2,
  ffi.Pointer<TCollisionCallback> callback,
);

/// Collision testing (manually query for collisions)
@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PhysicsWorld>,
        ffi.Pointer<TCollisionCallback>)>(isLeaf: true)
external void rp3d_test_collision_world(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  ffi.Pointer<TCollisionCallback> callback,
);

@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PhysicsWorld>, ffi.Pointer<RP3D_Body>,
        ffi.Pointer<TCollisionCallback>)>(isLeaf: true)
external void rp3d_test_collision_body(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  ffi.Pointer<RP3D_Body> body,
  ffi.Pointer<TCollisionCallback> callback,
);

/// Overlap/Trigger testing (query for trigger overlaps)
@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PhysicsWorld>,
        ffi.Pointer<TCollisionCallback>)>(isLeaf: true)
external void rp3d_test_overlap_world(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  ffi.Pointer<TCollisionCallback> callback,
);

/// Event listener registration (for automatic callbacks during world.update())
@ffi.Native<
    ffi.Void Function(ffi.Pointer<RP3D_PhysicsWorld>,
        ffi.Pointer<TCollisionCallback>)>(isLeaf: true)
external void rp3d_world_set_event_listener(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  ffi.Pointer<TCollisionCallback> eventListener,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_PhysicsWorld>)>(isLeaf: true)
external void rp3d_world_remove_event_listener(
  ffi.Pointer<RP3D_PhysicsWorld> world,
);

// ==================== SendPort Event Listener (Thread-Safe) ====================

/// Create a SendPort-based event listener for thread-safe callbacks
@ffi.Native<ffi.Uint64 Function(ffi.Uint64 sendPortId)>(isLeaf: true)
external int rp3d_create_sendport_event_listener(int sendPortId);

/// Set the SendPort event listener for a physics world
@ffi.Native<ffi.Void Function(ffi.Pointer<RP3D_PhysicsWorld>, ffi.Uint64)>(
    isLeaf: true)
external void rp3d_world_set_sendport_listener(
  ffi.Pointer<RP3D_PhysicsWorld> world,
  int listenerId,
);

/// Destroy a SendPort event listener
@ffi.Native<ffi.Void Function(ffi.Uint64)>(isLeaf: true)
external void rp3d_destroy_sendport_event_listener(int listenerId);

/// Send data to a Dart SendPort (helper function)
@ffi.Native<
    ffi.Int32 Function(ffi.Uint64 sendPortId, ffi.Pointer<ffi.Uint8> data,
        ffi.Uint32 size)>(isLeaf: true)
external int rp3d_send_to_dart_port(
  int sendPortId,
  ffi.Pointer<ffi.Uint8> data,
  int size,
);

/// Check if there's a pending message from any listener
@ffi.Native<ffi.Int32 Function()>(isLeaf: true)
external int rp3d_has_pending_message();

/// Get the latest message from a listener (for polling)
@ffi.Native<
    ffi.Uint32 Function(ffi.Uint64 listenerId, ffi.Pointer<ffi.Uint8> buffer,
        ffi.Uint32 bufferSize)>(isLeaf: true)
external int rp3d_get_listener_message(
  int listenerId,
  ffi.Pointer<ffi.Uint8> buffer,
  int bufferSize,
);

/// Get message count for a listener
@ffi.Native<ffi.Uint32 Function(ffi.Uint64)>(isLeaf: true)
external int rp3d_get_listener_message_count(int listenerId);

/// Destroy callbacks
@ffi.Native<ffi.Void Function(ffi.Pointer<TCollisionCallback>)>(isLeaf: true)
external void rp3d_destroy_collision_callback(
  ffi.Pointer<TCollisionCallback> callback,
);

final class RP3D_PhysicsCommon extends ffi.Opaque {}

final class RP3D_PhysicsWorld extends ffi.Opaque {}

final class RP3D_RigidBody extends ffi.Opaque {}

final class RP3D_Body extends ffi.Opaque {}

final class RP3D_Collider extends ffi.Opaque {}

final class RP3D_CollisionShape extends ffi.Opaque {}

final class RP3D_BoxShape extends ffi.Opaque {}

final class RP3D_SphereShape extends ffi.Opaque {}

final class RP3D_CapsuleShape extends ffi.Opaque {}

final class RP3D_ConvexMeshShape extends ffi.Opaque {}

final class RP3D_ConcaveMeshShape extends ffi.Opaque {}

final class RP3D_HeightFieldShape extends ffi.Opaque {}

final class RP3D_TriangleMesh extends ffi.Opaque {}

final class RP3D_TriangleVertexArray extends ffi.Opaque {}

final class RP3D_PolygonVertexArray extends ffi.Opaque {}

final class RP3D_VertexArray extends ffi.Opaque {}

final class RP3D_ConvexMesh extends ffi.Opaque {}

final class RP3D_HeightField extends ffi.Opaque {}

final class RP3D_Material extends ffi.Opaque {}

final class RP3D_BallAndSocketJoint extends ffi.Opaque {}

final class RP3D_HingeJoint extends ffi.Opaque {}

final class RP3D_SliderJoint extends ffi.Opaque {}

final class RP3D_FixedJoint extends ffi.Opaque {}

final class RP3D_DebugRenderer extends ffi.Opaque {}

final class TCollisionCallback extends ffi.Opaque {}

/// ==================== Enums ====================
sealed class RP3D_BodyType {
  static const RP3D_BODY_TYPE_STATIC = 1;
  static const RP3D_BODY_TYPE_KINEMATIC = 2;
  static const RP3D_BODY_TYPE_DYNAMIC = 3;
}

sealed class RP3D_DebugItem {
  static const RP3D_DEBUG_ITEM_COLLIDER_AABB = 1;
  static const RP3D_DEBUG_ITEM_COLLIDER_BROADPHASE_AABB = 2;
  static const RP3D_DEBUG_ITEM_COLLISION_SHAPE = 4;
  static const RP3D_DEBUG_ITEM_CONTACT_POINT = 8;
  static const RP3D_DEBUG_ITEM_CONTACT_NORMAL = 16;
}

/// ==================== Value Types (POD Structs) ====================
final class RP3D_Vector3 extends ffi.Struct {
  @ffi.Float()
  external double x;

  @ffi.Float()
  external double y;

  @ffi.Float()
  external double z;
}

final class RP3D_Quaternion extends ffi.Struct {
  @ffi.Float()
  external double x;

  @ffi.Float()
  external double y;

  @ffi.Float()
  external double z;

  @ffi.Float()
  external double w;
}

final class RP3D_Transform extends ffi.Struct {
  external RP3D_Vector3 position;

  external RP3D_Quaternion orientation;
}

final class RP3D_AABB extends ffi.Struct {
  external RP3D_Vector3 min;

  external RP3D_Vector3 max;
}

final class RP3D_Ray extends ffi.Struct {
  external RP3D_Vector3 point1;

  external RP3D_Vector3 point2;

  @ffi.Float()
  external double maxFraction;
}

final class RP3D_RaycastInfo extends ffi.Struct {
  external ffi.Pointer<RP3D_RigidBody> body;

  external ffi.Pointer<RP3D_Collider> collider;

  external RP3D_Vector3 worldPoint;

  external RP3D_Vector3 worldNormal;

  @ffi.Float()
  external double hitFraction;
}

/// Joint info structures
final class RP3D_BallAndSocketJointInfo extends ffi.Struct {
  external RP3D_Vector3 anchorPointWorldSpace;

  external ffi.Pointer<RP3D_RigidBody> body1;

  external ffi.Pointer<RP3D_RigidBody> body2;

  @ffi.Uint8()
  external int isCollisionEnabled;
}

final class RP3D_HingeJointInfo extends ffi.Struct {
  external RP3D_Vector3 anchorPointWorldSpace;

  external RP3D_Vector3 rotationAxisWorld;

  external ffi.Pointer<RP3D_RigidBody> body1;

  external ffi.Pointer<RP3D_RigidBody> body2;

  @ffi.Uint8()
  external int isCollisionEnabled;

  @ffi.Uint8()
  external int isLimitEnabled;

  @ffi.Uint8()
  external int isMotorEnabled;

  @ffi.Float()
  external double minAngleLimit;

  @ffi.Float()
  external double maxAngleLimit;

  @ffi.Float()
  external double motorSpeed;

  @ffi.Float()
  external double maxMotorTorque;
}

final class RP3D_SliderJointInfo extends ffi.Struct {
  external RP3D_Vector3 anchorPointWorldSpace;

  external RP3D_Vector3 sliderAxisWorldSpace;

  external ffi.Pointer<RP3D_RigidBody> body1;

  external ffi.Pointer<RP3D_RigidBody> body2;

  @ffi.Uint8()
  external int isCollisionEnabled;

  @ffi.Uint8()
  external int isLimitEnabled;

  @ffi.Uint8()
  external int isMotorEnabled;

  @ffi.Float()
  external double minTranslationLimit;

  @ffi.Float()
  external double maxTranslationLimit;

  @ffi.Float()
  external double motorSpeed;

  @ffi.Float()
  external double maxMotorForce;
}

final class RP3D_FixedJointInfo extends ffi.Struct {
  external RP3D_Vector3 anchorPointWorldSpace;

  external ffi.Pointer<RP3D_RigidBody> body1;

  external ffi.Pointer<RP3D_RigidBody> body2;

  @ffi.Uint8()
  external int isCollisionEnabled;
}
