// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:jsgen`.
// ignore_for_file: type=lint
import 'dart:typed_data';
import 'dart:js_interop';
import 'dart:js_interop_unsafe';
import 'package:ffigen_js/ffigen_js.dart';
export 'package:ffigen_js/ffigen_js.dart';

extension type GeneratedBindings(NativeLibrary _) implements JSObject {
  static GeneratedBindings get instance =>
      NativeLibrary.instance as GeneratedBindings;

  static void initBindings(String moduleName) {
    var lib = globalContext.getProperty(moduleName.toJS);
    if (lib == null) {
      throw Exception("Failed to find JS module ${moduleName}");
    }
    NativeLibrary.instance = lib as NativeLibrary;
  }

  /// ==================== PhysicsCommon (Factory) ====================
  external Pointer<RP3D_PhysicsCommon> _rp3d_physics_common_create();
  external void _rp3d_physics_common_destroy(
    Pointer<RP3D_PhysicsCommon> common,
  );
  external Pointer<RP3D_PhysicsWorld> _rp3d_physics_common_create_physics_world(
    Pointer<RP3D_PhysicsCommon> common,
  );
  external void _rp3d_physics_common_destroy_physics_world(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_PhysicsWorld> world,
  );

  /// Shape creation through PhysicsCommon
  external Pointer<RP3D_BoxShape> _rp3d_physics_common_create_box_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_Vector3> halfExtents,
  );
  external Pointer<RP3D_SphereShape> _rp3d_physics_common_create_sphere_shape(
    Pointer<RP3D_PhysicsCommon> common,
    double radius,
  );
  external Pointer<RP3D_CapsuleShape> _rp3d_physics_common_create_capsule_shape(
    Pointer<RP3D_PhysicsCommon> common,
    double radius,
    double height,
  );

  /// HeightField creation/destruction
  external Pointer<RP3D_HeightField> _rp3d_physics_common_create_height_field(
    Pointer<RP3D_PhysicsCommon> common,
    int nbRows,
    int nbColumns,
    Pointer<Float32> heights,
    double minHeight,
    double maxHeight,
  );
  external void _rp3d_physics_common_destroy_height_field(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_HeightField> heightField,
  );

  /// HeightFieldShape creation/destruction
  external Pointer<RP3D_HeightFieldShape>
  _rp3d_physics_common_create_height_field_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_HeightField> heightField,
  );
  external void _rp3d_physics_common_destroy_height_field_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_HeightFieldShape> heightFieldShape,
  );

  /// TriangleVertexArray creation/destruction
  external Pointer<RP3D_TriangleVertexArray> _rp3d_triangle_vertex_array_create(
    int nbVertices,
    Pointer<Float32> verticesStart,
    int verticesStride,
    int nbIndices,
    Pointer<Uint32> indicesStart,
    int indicesStride,
  );
  external void _rp3d_triangle_vertex_array_destroy(
    Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
  );

  /// TriangleVertexArray accessors
  external int _rp3d_triangle_vertex_array_get_nb_vertices(
    Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
  );
  external int _rp3d_triangle_vertex_array_get_nb_triangles(
    Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
  );
  external Pointer<Float32> _rp3d_triangle_vertex_array_get_vertices_start(
    Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
  );
  external Pointer<Uint32> _rp3d_triangle_vertex_array_get_indices_start(
    Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
  );
  external void _rp3d_triangle_vertex_array_get_triangle_vertices_indices(
    Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
    int triangleIndex,
    Pointer<Uint32> out,
  );

  /// PolygonVertexArray creation/destruction
  external Pointer<RP3D_PolygonVertexArray> _rp3d_polygon_vertex_array_create(
    int nbVertices,
    Pointer<Float32> verticesStart,
    int verticesStride,
    int nbIndices,
    Pointer<Uint32> indicesStart,
    int indicesStride,
    Pointer<Uint32> polygonIndicesStart,
    int polygonIndicesStride,
  );
  external void _rp3d_polygon_vertex_array_destroy(
    Pointer<RP3D_PolygonVertexArray> polygonVertexArray,
  );

  /// TriangleMesh creation/destruction
  external Pointer<RP3D_TriangleMesh> _rp3d_physics_common_create_triangle_mesh(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
  );
  external void _rp3d_physics_common_destroy_triangle_mesh(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_TriangleMesh> triangleMesh,
  );

  /// TriangleMesh accessors
  external int _rp3d_triangle_mesh_get_nb_vertices(
    Pointer<RP3D_TriangleMesh> triangleMesh,
  );
  external int _rp3d_triangle_mesh_get_nb_triangles(
    Pointer<RP3D_TriangleMesh> triangleMesh,
  );
  external void _rp3d_triangle_mesh_get_vertex(
    Pointer<RP3D_TriangleMesh> triangleMesh,
    int vertexIndex,
    Pointer<RP3D_Vector3> outVertex,
  );
  external void _rp3d_triangle_mesh_get_triangle_vertices_indices(
    Pointer<RP3D_TriangleMesh> triangleMesh,
    int triangleIndex,
    Pointer<Uint32> indices,
  );

  /// ConvexMesh creation/destruction
  external Pointer<RP3D_ConvexMesh>
  _rp3d_physics_common_create_convex_mesh_from_triangles(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
  );
  external Pointer<RP3D_ConvexMesh>
  _rp3d_physics_common_create_convex_mesh_from_polygons(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_PolygonVertexArray> polygonVertexArray,
  );
  external void _rp3d_physics_common_destroy_convex_mesh(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_ConvexMesh> convexMesh,
  );

  /// ConvexMeshShape creation/destruction
  external Pointer<RP3D_ConvexMeshShape>
  _rp3d_physics_common_create_convex_mesh_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_ConvexMesh> convexMesh,
  );
  external void _rp3d_physics_common_destroy_convex_mesh_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_ConvexMeshShape> convexMeshShape,
  );

  /// ConcaveMeshShape creation/destruction
  external Pointer<RP3D_ConcaveMeshShape>
  _rp3d_physics_common_create_concave_mesh_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_TriangleMesh> triangleMesh,
    Pointer<RP3D_Vector3> scaling,
  );
  external void _rp3d_physics_common_destroy_concave_mesh_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_ConcaveMeshShape> concaveMeshShape,
  );

  /// Mesh/shape destruction
  external void _rp3d_physics_common_destroy_box_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_BoxShape> shape,
  );
  external void _rp3d_physics_common_destroy_sphere_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_SphereShape> shape,
  );
  external void _rp3d_physics_common_destroy_capsule_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_CapsuleShape> shape,
  );

  /// ==================== PhysicsWorld ====================
  external void _rp3d_world_update(
    Pointer<RP3D_PhysicsWorld> world,
    double timeStep,
  );
  external void _rp3d_world_set_gravity(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<RP3D_Vector3> gravity,
  );
  external void _rp3d_world_get_gravity(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<RP3D_Vector3> outGravity,
  );
  external int _rp3d_world_get_is_sleeping_enabled(
    Pointer<RP3D_PhysicsWorld> world,
  );
  external void _rp3d_world_set_is_sleeping_enabled(
    Pointer<RP3D_PhysicsWorld> world,
    int isSleepingEnabled,
  );

  /// Gravity and sleep control
  external void _rp3d_world_set_is_gravity_enabled(
    Pointer<RP3D_PhysicsWorld> world,
    int isGravityEnabled,
  );
  external void _rp3d_world_set_sleep_linear_velocity(
    Pointer<RP3D_PhysicsWorld> world,
    double sleepLinearVelocity,
  );
  external void _rp3d_world_set_sleep_angular_velocity(
    Pointer<RP3D_PhysicsWorld> world,
    double sleepAngularVelocity,
  );
  external void _rp3d_world_set_time_before_sleep(
    Pointer<RP3D_PhysicsWorld> world,
    double timeBeforeSleep,
  );

  /// Debug rendering
  external void _rp3d_world_set_is_debug_rendering_enabled(
    Pointer<RP3D_PhysicsWorld> world,
    int isEnabled,
  );
  external int _rp3d_world_get_is_debug_rendering_enabled(
    Pointer<RP3D_PhysicsWorld> world,
  );
  external Pointer<RP3D_DebugRenderer> _rp3d_world_get_debug_renderer(
    Pointer<RP3D_PhysicsWorld> world,
  );
  external int _rp3d_world_get_nb_rigid_bodies(
    Pointer<RP3D_PhysicsWorld> world,
  );
  external Pointer<RP3D_RigidBody> _rp3d_world_get_rigid_body(
    Pointer<RP3D_PhysicsWorld> world,
    int index,
  );

  /// Body creation/destruction
  external Pointer<RP3D_RigidBody> _rp3d_world_create_rigid_body(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<RP3D_Transform> transform,
  );
  external void _rp3d_world_destroy_rigid_body(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<RP3D_RigidBody> body,
  );

  /// Raycasting
  external int _rp3d_world_raycast(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<RP3D_Ray> ray,
    Pointer<RP3D_RaycastInfo> raycastInfo,
  );

  /// ==================== RigidBody ====================
  external void _rp3d_body_get_transform(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Transform> outTransform,
  );
  external void _rp3d_body_set_transform(
    Pointer<RP3D_RigidBody> body,
    double posX,
    double posY,
    double posZ,
    double quatX,
    double quatY,
    double quatZ,
    double quatW,
  );
  external void _rp3d_body_get_position(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Vector3> outPosition,
  );
  external void _rp3d_body_get_orientation(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Quaternion> outOrientation,
  );
  external void _rp3d_body_set_type(Pointer<RP3D_RigidBody> body, int type);
  external int _rp3d_body_get_type(Pointer<RP3D_RigidBody> body);
  external void _rp3d_body_set_mass(Pointer<RP3D_RigidBody> body, double mass);
  external double _rp3d_body_get_mass(Pointer<RP3D_RigidBody> body);
  external void _rp3d_body_set_linear_velocity(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Vector3> linearVelocity,
  );
  external void _rp3d_body_get_linear_velocity(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Vector3> outLinearVelocity,
  );
  external void _rp3d_body_set_angular_velocity(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Vector3> angularVelocity,
  );
  external void _rp3d_body_get_angular_velocity(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Vector3> outAngularVelocity,
  );
  external void _rp3d_body_apply_force(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Vector3> force,
  );
  external void _rp3d_body_apply_force_at_position(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Vector3> force,
    Pointer<RP3D_Vector3> position,
  );
  external void _rp3d_body_apply_torque(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Vector3> torque,
  );
  external void _rp3d_body_set_is_active(
    Pointer<RP3D_RigidBody> body,
    int isActive,
  );
  external int _rp3d_body_get_is_active(Pointer<RP3D_RigidBody> body);
  external void _rp3d_body_set_is_sleeping_allowed(
    Pointer<RP3D_RigidBody> body,
    int isAllowed,
  );
  external int _rp3d_body_get_is_sleeping_allowed(Pointer<RP3D_RigidBody> body);

  /// Gravity control
  external void _rp3d_body_enable_gravity(
    Pointer<RP3D_RigidBody> body,
    int enableGravity,
  );
  external int _rp3d_body_is_gravity_enabled(Pointer<RP3D_RigidBody> body);

  /// Debug rendering
  external void _rp3d_body_set_is_debug_enabled(
    Pointer<RP3D_RigidBody> body,
    int isEnabled,
  );
  external int _rp3d_body_get_is_debug_enabled(Pointer<RP3D_RigidBody> body);

  /// Mass properties
  external void _rp3d_body_update_mass_properties_from_colliders(
    Pointer<RP3D_RigidBody> body,
  );

  /// Collider management
  external Pointer<RP3D_Collider> _rp3d_body_add_collider(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_CollisionShape> shape,
    Pointer<RP3D_Transform> transform,
  );
  external void _rp3d_body_remove_collider(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Collider> collider,
  );
  external void _rp3d_collider_set_material(
    Pointer<RP3D_Collider> collider,
    Pointer<RP3D_Material> material,
  );

  /// ==================== Collider ====================
  external Pointer<RP3D_Material> _rp3d_collider_get_material(
    Pointer<RP3D_Collider> collider,
  );
  external void _rp3d_collider_get_local_bounds(
    Pointer<RP3D_Collider> collider,
    Pointer<RP3D_AABB> outAABB,
  );
  external void _rp3d_collider_set_is_trigger(
    Pointer<RP3D_Collider> collider,
    int isTrigger,
  );
  external int _rp3d_collider_get_is_trigger(Pointer<RP3D_Collider> collider);

  /// ==================== Material ====================
  external void _rp3d_material_destroy(Pointer<RP3D_Material> material);
  external void _rp3d_material_set_bounciness(
    Pointer<RP3D_Material> material,
    double bounciness,
  );
  external double _rp3d_material_get_bounciness(
    Pointer<RP3D_Material> material,
  );
  external void _rp3d_material_set_friction_coefficient(
    Pointer<RP3D_Material> material,
    double frictionCoefficient,
  );
  external double _rp3d_material_get_friction_coefficient(
    Pointer<RP3D_Material> material,
  );
  external void _rp3d_material_set_mass_density(
    Pointer<RP3D_Material> material,
    double massDensity,
  );
  external double _rp3d_material_get_mass_density(
    Pointer<RP3D_Material> material,
  );

  /// ==================== CollisionShape (base) ====================
  external void _rp3d_shape_get_local_bounds(
    Pointer<RP3D_CollisionShape> shape,
    Pointer<RP3D_AABB> outAABB,
  );
  external void _rp3d_concave_shape_set_scale(
    Pointer<RP3D_HeightFieldShape> shape,
    Pointer<RP3D_Vector3> scale,
  );

  /// ==================== HeightFieldShape ====================
  external void _rp3d_height_field_shape_get_vertex_at(
    Pointer<RP3D_HeightFieldShape> heightFieldShape,
    int row,
    int column,
    Pointer<RP3D_Vector3> outVertex,
  );

  /// Vector3
  external void _rp3d_vector3_zero(Pointer<RP3D_Vector3> v);
  external double _rp3d_vector3_length(Pointer<RP3D_Vector3> v);
  external void _rp3d_vector3_normalize(Pointer<RP3D_Vector3> v);
  external double _rp3d_vector3_dot(
    Pointer<RP3D_Vector3> v1,
    Pointer<RP3D_Vector3> v2,
  );
  external void _rp3d_vector3_cross(
    Pointer<RP3D_Vector3> v1,
    Pointer<RP3D_Vector3> v2,
    Pointer<RP3D_Vector3> outResult,
  );

  /// Quaternion
  external void _rp3d_quaternion_identity(Pointer<RP3D_Quaternion> q);
  external void _rp3d_quaternion_from_axis_angle(
    Pointer<RP3D_Vector3> axis,
    double angle,
    Pointer<RP3D_Quaternion> outQuat,
  );
  external void _rp3d_quaternion_normalize(Pointer<RP3D_Quaternion> q);

  /// Transform
  external void _rp3d_transform_identity(Pointer<RP3D_Transform> t);
  external void _rp3d_transform_inverse(
    Pointer<RP3D_Transform> t,
    Pointer<RP3D_Transform> outInverse,
  );
  external void _rp3d_transform_get_opengl_matrix(
    Pointer<RP3D_Transform> t,
    Pointer<Float32> outMatrix,
  );

  /// ==================== DebugRenderer ====================
  external void _rp3d_debug_renderer_set_is_debug_item_displayed(
    Pointer<RP3D_DebugRenderer> renderer,
    int item,
    int isDisplayed,
  );
  external int _rp3d_debug_renderer_get_is_debug_item_displayed(
    Pointer<RP3D_DebugRenderer> renderer,
    int item,
  );
  external int _rp3d_debug_renderer_get_nb_lines(
    Pointer<RP3D_DebugRenderer> renderer,
  );
  external int _rp3d_debug_renderer_get_nb_triangles(
    Pointer<RP3D_DebugRenderer> renderer,
  );
  external void _rp3d_debug_renderer_get_lines_array(
    Pointer<RP3D_DebugRenderer> renderer,
    Pointer<Float32> outVertices,
    Pointer<Uint32> outColors,
  );
  external void _rp3d_debug_renderer_get_triangles_array(
    Pointer<RP3D_DebugRenderer> renderer,
    Pointer<Float32> outVertices,
    Pointer<Uint32> outColors,
  );

  /// ==================== Joints ====================
  external Pointer<RP3D_BallAndSocketJoint>
  _rp3d_world_create_ball_and_socket_joint(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<RP3D_BallAndSocketJointInfo> jointInfo,
  );
  external Pointer<RP3D_HingeJoint> _rp3d_world_create_hinge_joint(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<RP3D_HingeJointInfo> jointInfo,
  );
  external Pointer<RP3D_SliderJoint> _rp3d_world_create_slider_joint(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<RP3D_SliderJointInfo> jointInfo,
  );
  external Pointer<RP3D_FixedJoint> _rp3d_world_create_fixed_joint(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<RP3D_FixedJointInfo> jointInfo,
  );
  external void _rp3d_world_destroy_joint(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<Void> joint,
  );
}

/// ==================== PhysicsCommon (Factory) ====================
Pointer<RP3D_PhysicsCommon> rp3d_physics_common_create() {
  final result = GeneratedBindings.instance._rp3d_physics_common_create();
  return Pointer<RP3D_PhysicsCommon>(result);
}

void rp3d_physics_common_destroy(Pointer<RP3D_PhysicsCommon> common) {
  final result = GeneratedBindings.instance._rp3d_physics_common_destroy(
    common.cast(),
  );
  return result;
}

Pointer<RP3D_PhysicsWorld> rp3d_physics_common_create_physics_world(
  Pointer<RP3D_PhysicsCommon> common,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_create_physics_world(common.cast());
  return Pointer<RP3D_PhysicsWorld>(result);
}

void rp3d_physics_common_destroy_physics_world(
  Pointer<RP3D_PhysicsCommon> common,
  Pointer<RP3D_PhysicsWorld> world,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_destroy_physics_world(common.cast(), world.cast());
  return result;
}

/// Shape creation through PhysicsCommon
Pointer<RP3D_BoxShape> rp3d_physics_common_create_box_shape(
  Pointer<RP3D_PhysicsCommon> common,
  Pointer<RP3D_Vector3> halfExtents,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_create_box_shape(common.cast(), halfExtents.cast());
  return Pointer<RP3D_BoxShape>(result);
}

Pointer<RP3D_SphereShape> rp3d_physics_common_create_sphere_shape(
  Pointer<RP3D_PhysicsCommon> common,
  double radius,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_create_sphere_shape(common.cast(), radius);
  return Pointer<RP3D_SphereShape>(result);
}

Pointer<RP3D_CapsuleShape> rp3d_physics_common_create_capsule_shape(
  Pointer<RP3D_PhysicsCommon> common,
  double radius,
  double height,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_create_capsule_shape(common.cast(), radius, height);
  return Pointer<RP3D_CapsuleShape>(result);
}

/// HeightField creation/destruction
Pointer<RP3D_HeightField> rp3d_physics_common_create_height_field(
  Pointer<RP3D_PhysicsCommon> common,
  int nbRows,
  int nbColumns,
  Pointer<Float32> heights,
  double minHeight,
  double maxHeight,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_create_height_field(
        common.cast(),
        nbRows,
        nbColumns,
        heights,
        minHeight,
        maxHeight,
      );
  return Pointer<RP3D_HeightField>(result);
}

void rp3d_physics_common_destroy_height_field(
  Pointer<RP3D_PhysicsCommon> common,
  Pointer<RP3D_HeightField> heightField,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_destroy_height_field(
        common.cast(),
        heightField.cast(),
      );
  return result;
}

/// HeightFieldShape creation/destruction
Pointer<RP3D_HeightFieldShape> rp3d_physics_common_create_height_field_shape(
  Pointer<RP3D_PhysicsCommon> common,
  Pointer<RP3D_HeightField> heightField,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_create_height_field_shape(
        common.cast(),
        heightField.cast(),
      );
  return Pointer<RP3D_HeightFieldShape>(result);
}

void rp3d_physics_common_destroy_height_field_shape(
  Pointer<RP3D_PhysicsCommon> common,
  Pointer<RP3D_HeightFieldShape> heightFieldShape,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_destroy_height_field_shape(
        common.cast(),
        heightFieldShape.cast(),
      );
  return result;
}

/// TriangleVertexArray creation/destruction
Pointer<RP3D_TriangleVertexArray> rp3d_triangle_vertex_array_create(
  int nbVertices,
  Pointer<Float32> verticesStart,
  int verticesStride,
  int nbIndices,
  Pointer<Uint32> indicesStart,
  int indicesStride,
) {
  final result = GeneratedBindings.instance._rp3d_triangle_vertex_array_create(
    nbVertices,
    verticesStart,
    verticesStride,
    nbIndices,
    indicesStart,
    indicesStride,
  );
  return Pointer<RP3D_TriangleVertexArray>(result);
}

void rp3d_triangle_vertex_array_destroy(
  Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
) {
  final result = GeneratedBindings.instance._rp3d_triangle_vertex_array_destroy(
    triangleVertexArray.cast(),
  );
  return result;
}

/// TriangleVertexArray accessors
int rp3d_triangle_vertex_array_get_nb_vertices(
  Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
) {
  final result = GeneratedBindings.instance
      ._rp3d_triangle_vertex_array_get_nb_vertices(triangleVertexArray.cast());
  return result;
}

int rp3d_triangle_vertex_array_get_nb_triangles(
  Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
) {
  final result = GeneratedBindings.instance
      ._rp3d_triangle_vertex_array_get_nb_triangles(triangleVertexArray.cast());
  return result;
}

Pointer<Float32> rp3d_triangle_vertex_array_get_vertices_start(
  Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
) {
  final result = GeneratedBindings.instance
      ._rp3d_triangle_vertex_array_get_vertices_start(
        triangleVertexArray.cast(),
      );
  return Pointer<Float32>(result);
}

Pointer<Uint32> rp3d_triangle_vertex_array_get_indices_start(
  Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
) {
  final result = GeneratedBindings.instance
      ._rp3d_triangle_vertex_array_get_indices_start(
        triangleVertexArray.cast(),
      );
  return Pointer<Uint32>(result);
}

void rp3d_triangle_vertex_array_get_triangle_vertices_indices(
  Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
  int triangleIndex,
  Pointer<Uint32> out,
) {
  final result = GeneratedBindings.instance
      ._rp3d_triangle_vertex_array_get_triangle_vertices_indices(
        triangleVertexArray.cast(),
        triangleIndex,
        out,
      );
  return result;
}

/// PolygonVertexArray creation/destruction
Pointer<RP3D_PolygonVertexArray> rp3d_polygon_vertex_array_create(
  int nbVertices,
  Pointer<Float32> verticesStart,
  int verticesStride,
  int nbIndices,
  Pointer<Uint32> indicesStart,
  int indicesStride,
  Pointer<Uint32> polygonIndicesStart,
  int polygonIndicesStride,
) {
  final result = GeneratedBindings.instance._rp3d_polygon_vertex_array_create(
    nbVertices,
    verticesStart,
    verticesStride,
    nbIndices,
    indicesStart,
    indicesStride,
    polygonIndicesStart,
    polygonIndicesStride,
  );
  return Pointer<RP3D_PolygonVertexArray>(result);
}

void rp3d_polygon_vertex_array_destroy(
  Pointer<RP3D_PolygonVertexArray> polygonVertexArray,
) {
  final result = GeneratedBindings.instance._rp3d_polygon_vertex_array_destroy(
    polygonVertexArray.cast(),
  );
  return result;
}

/// TriangleMesh creation/destruction
Pointer<RP3D_TriangleMesh> rp3d_physics_common_create_triangle_mesh(
  Pointer<RP3D_PhysicsCommon> common,
  Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_create_triangle_mesh(
        common.cast(),
        triangleVertexArray.cast(),
      );
  return Pointer<RP3D_TriangleMesh>(result);
}

void rp3d_physics_common_destroy_triangle_mesh(
  Pointer<RP3D_PhysicsCommon> common,
  Pointer<RP3D_TriangleMesh> triangleMesh,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_destroy_triangle_mesh(
        common.cast(),
        triangleMesh.cast(),
      );
  return result;
}

/// TriangleMesh accessors
int rp3d_triangle_mesh_get_nb_vertices(
  Pointer<RP3D_TriangleMesh> triangleMesh,
) {
  final result = GeneratedBindings.instance._rp3d_triangle_mesh_get_nb_vertices(
    triangleMesh.cast(),
  );
  return result;
}

int rp3d_triangle_mesh_get_nb_triangles(
  Pointer<RP3D_TriangleMesh> triangleMesh,
) {
  final result = GeneratedBindings.instance
      ._rp3d_triangle_mesh_get_nb_triangles(triangleMesh.cast());
  return result;
}

void rp3d_triangle_mesh_get_vertex(
  Pointer<RP3D_TriangleMesh> triangleMesh,
  int vertexIndex,
  Pointer<RP3D_Vector3> outVertex,
) {
  final result = GeneratedBindings.instance._rp3d_triangle_mesh_get_vertex(
    triangleMesh.cast(),
    vertexIndex,
    outVertex.cast(),
  );
  return result;
}

void rp3d_triangle_mesh_get_triangle_vertices_indices(
  Pointer<RP3D_TriangleMesh> triangleMesh,
  int triangleIndex,
  Pointer<Uint32> indices,
) {
  final result = GeneratedBindings.instance
      ._rp3d_triangle_mesh_get_triangle_vertices_indices(
        triangleMesh.cast(),
        triangleIndex,
        indices,
      );
  return result;
}

/// ConvexMesh creation/destruction
Pointer<RP3D_ConvexMesh> rp3d_physics_common_create_convex_mesh_from_triangles(
  Pointer<RP3D_PhysicsCommon> common,
  Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_create_convex_mesh_from_triangles(
        common.cast(),
        triangleVertexArray.cast(),
      );
  return Pointer<RP3D_ConvexMesh>(result);
}

Pointer<RP3D_ConvexMesh> rp3d_physics_common_create_convex_mesh_from_polygons(
  Pointer<RP3D_PhysicsCommon> common,
  Pointer<RP3D_PolygonVertexArray> polygonVertexArray,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_create_convex_mesh_from_polygons(
        common.cast(),
        polygonVertexArray.cast(),
      );
  return Pointer<RP3D_ConvexMesh>(result);
}

void rp3d_physics_common_destroy_convex_mesh(
  Pointer<RP3D_PhysicsCommon> common,
  Pointer<RP3D_ConvexMesh> convexMesh,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_destroy_convex_mesh(
        common.cast(),
        convexMesh.cast(),
      );
  return result;
}

/// ConvexMeshShape creation/destruction
Pointer<RP3D_ConvexMeshShape> rp3d_physics_common_create_convex_mesh_shape(
  Pointer<RP3D_PhysicsCommon> common,
  Pointer<RP3D_ConvexMesh> convexMesh,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_create_convex_mesh_shape(
        common.cast(),
        convexMesh.cast(),
      );
  return Pointer<RP3D_ConvexMeshShape>(result);
}

void rp3d_physics_common_destroy_convex_mesh_shape(
  Pointer<RP3D_PhysicsCommon> common,
  Pointer<RP3D_ConvexMeshShape> convexMeshShape,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_destroy_convex_mesh_shape(
        common.cast(),
        convexMeshShape.cast(),
      );
  return result;
}

/// ConcaveMeshShape creation/destruction
Pointer<RP3D_ConcaveMeshShape> rp3d_physics_common_create_concave_mesh_shape(
  Pointer<RP3D_PhysicsCommon> common,
  Pointer<RP3D_TriangleMesh> triangleMesh,
  Pointer<RP3D_Vector3> scaling,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_create_concave_mesh_shape(
        common.cast(),
        triangleMesh.cast(),
        scaling.cast(),
      );
  return Pointer<RP3D_ConcaveMeshShape>(result);
}

void rp3d_physics_common_destroy_concave_mesh_shape(
  Pointer<RP3D_PhysicsCommon> common,
  Pointer<RP3D_ConcaveMeshShape> concaveMeshShape,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_destroy_concave_mesh_shape(
        common.cast(),
        concaveMeshShape.cast(),
      );
  return result;
}

/// Mesh/shape destruction
void rp3d_physics_common_destroy_box_shape(
  Pointer<RP3D_PhysicsCommon> common,
  Pointer<RP3D_BoxShape> shape,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_destroy_box_shape(common.cast(), shape.cast());
  return result;
}

void rp3d_physics_common_destroy_sphere_shape(
  Pointer<RP3D_PhysicsCommon> common,
  Pointer<RP3D_SphereShape> shape,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_destroy_sphere_shape(common.cast(), shape.cast());
  return result;
}

void rp3d_physics_common_destroy_capsule_shape(
  Pointer<RP3D_PhysicsCommon> common,
  Pointer<RP3D_CapsuleShape> shape,
) {
  final result = GeneratedBindings.instance
      ._rp3d_physics_common_destroy_capsule_shape(common.cast(), shape.cast());
  return result;
}

/// ==================== PhysicsWorld ====================
void rp3d_world_update(Pointer<RP3D_PhysicsWorld> world, double timeStep) {
  final result = GeneratedBindings.instance._rp3d_world_update(
    world.cast(),
    timeStep,
  );
  return result;
}

void rp3d_world_set_gravity(
  Pointer<RP3D_PhysicsWorld> world,
  Pointer<RP3D_Vector3> gravity,
) {
  final result = GeneratedBindings.instance._rp3d_world_set_gravity(
    world.cast(),
    gravity.cast(),
  );
  return result;
}

void rp3d_world_get_gravity(
  Pointer<RP3D_PhysicsWorld> world,
  Pointer<RP3D_Vector3> outGravity,
) {
  final result = GeneratedBindings.instance._rp3d_world_get_gravity(
    world.cast(),
    outGravity.cast(),
  );
  return result;
}

int rp3d_world_get_is_sleeping_enabled(Pointer<RP3D_PhysicsWorld> world) {
  final result = GeneratedBindings.instance._rp3d_world_get_is_sleeping_enabled(
    world.cast(),
  );
  return result;
}

void rp3d_world_set_is_sleeping_enabled(
  Pointer<RP3D_PhysicsWorld> world,
  int isSleepingEnabled,
) {
  final result = GeneratedBindings.instance._rp3d_world_set_is_sleeping_enabled(
    world.cast(),
    isSleepingEnabled,
  );
  return result;
}

/// Gravity and sleep control
void rp3d_world_set_is_gravity_enabled(
  Pointer<RP3D_PhysicsWorld> world,
  int isGravityEnabled,
) {
  final result = GeneratedBindings.instance._rp3d_world_set_is_gravity_enabled(
    world.cast(),
    isGravityEnabled,
  );
  return result;
}

void rp3d_world_set_sleep_linear_velocity(
  Pointer<RP3D_PhysicsWorld> world,
  double sleepLinearVelocity,
) {
  final result = GeneratedBindings.instance
      ._rp3d_world_set_sleep_linear_velocity(world.cast(), sleepLinearVelocity);
  return result;
}

void rp3d_world_set_sleep_angular_velocity(
  Pointer<RP3D_PhysicsWorld> world,
  double sleepAngularVelocity,
) {
  final result = GeneratedBindings.instance
      ._rp3d_world_set_sleep_angular_velocity(
        world.cast(),
        sleepAngularVelocity,
      );
  return result;
}

void rp3d_world_set_time_before_sleep(
  Pointer<RP3D_PhysicsWorld> world,
  double timeBeforeSleep,
) {
  final result = GeneratedBindings.instance._rp3d_world_set_time_before_sleep(
    world.cast(),
    timeBeforeSleep,
  );
  return result;
}

/// Debug rendering
void rp3d_world_set_is_debug_rendering_enabled(
  Pointer<RP3D_PhysicsWorld> world,
  int isEnabled,
) {
  final result = GeneratedBindings.instance
      ._rp3d_world_set_is_debug_rendering_enabled(world.cast(), isEnabled);
  return result;
}

int rp3d_world_get_is_debug_rendering_enabled(
  Pointer<RP3D_PhysicsWorld> world,
) {
  final result = GeneratedBindings.instance
      ._rp3d_world_get_is_debug_rendering_enabled(world.cast());
  return result;
}

Pointer<RP3D_DebugRenderer> rp3d_world_get_debug_renderer(
  Pointer<RP3D_PhysicsWorld> world,
) {
  final result = GeneratedBindings.instance._rp3d_world_get_debug_renderer(
    world.cast(),
  );
  return Pointer<RP3D_DebugRenderer>(result);
}

int rp3d_world_get_nb_rigid_bodies(Pointer<RP3D_PhysicsWorld> world) {
  final result = GeneratedBindings.instance._rp3d_world_get_nb_rigid_bodies(
    world.cast(),
  );
  return result;
}

Pointer<RP3D_RigidBody> rp3d_world_get_rigid_body(
  Pointer<RP3D_PhysicsWorld> world,
  int index,
) {
  final result = GeneratedBindings.instance._rp3d_world_get_rigid_body(
    world.cast(),
    index,
  );
  return Pointer<RP3D_RigidBody>(result);
}

/// Body creation/destruction
Pointer<RP3D_RigidBody> rp3d_world_create_rigid_body(
  Pointer<RP3D_PhysicsWorld> world,
  Pointer<RP3D_Transform> transform,
) {
  final result = GeneratedBindings.instance._rp3d_world_create_rigid_body(
    world.cast(),
    transform.cast(),
  );
  return Pointer<RP3D_RigidBody>(result);
}

void rp3d_world_destroy_rigid_body(
  Pointer<RP3D_PhysicsWorld> world,
  Pointer<RP3D_RigidBody> body,
) {
  final result = GeneratedBindings.instance._rp3d_world_destroy_rigid_body(
    world.cast(),
    body.cast(),
  );
  return result;
}

/// Raycasting
int rp3d_world_raycast(
  Pointer<RP3D_PhysicsWorld> world,
  Pointer<RP3D_Ray> ray,
  Pointer<RP3D_RaycastInfo> raycastInfo,
) {
  final result = GeneratedBindings.instance._rp3d_world_raycast(
    world.cast(),
    ray.cast(),
    raycastInfo.cast(),
  );
  return result;
}

/// ==================== RigidBody ====================
void rp3d_body_get_transform(
  Pointer<RP3D_RigidBody> body,
  Pointer<RP3D_Transform> outTransform,
) {
  final result = GeneratedBindings.instance._rp3d_body_get_transform(
    body.cast(),
    outTransform.cast(),
  );
  return result;
}

void rp3d_body_set_transform(
  Pointer<RP3D_RigidBody> body,
  double posX,
  double posY,
  double posZ,
  double quatX,
  double quatY,
  double quatZ,
  double quatW,
) {
  final result = GeneratedBindings.instance._rp3d_body_set_transform(
    body.cast(),
    posX,
    posY,
    posZ,
    quatX,
    quatY,
    quatZ,
    quatW,
  );
  return result;
}

void rp3d_body_get_position(
  Pointer<RP3D_RigidBody> body,
  Pointer<RP3D_Vector3> outPosition,
) {
  final result = GeneratedBindings.instance._rp3d_body_get_position(
    body.cast(),
    outPosition.cast(),
  );
  return result;
}

void rp3d_body_get_orientation(
  Pointer<RP3D_RigidBody> body,
  Pointer<RP3D_Quaternion> outOrientation,
) {
  final result = GeneratedBindings.instance._rp3d_body_get_orientation(
    body.cast(),
    outOrientation.cast(),
  );
  return result;
}

void rp3d_body_set_type(Pointer<RP3D_RigidBody> body, int type) {
  final result = GeneratedBindings.instance._rp3d_body_set_type(
    body.cast(),
    type,
  );
  return result;
}

int rp3d_body_get_type(Pointer<RP3D_RigidBody> body) {
  final result = GeneratedBindings.instance._rp3d_body_get_type(body.cast());
  return result;
}

void rp3d_body_set_mass(Pointer<RP3D_RigidBody> body, double mass) {
  final result = GeneratedBindings.instance._rp3d_body_set_mass(
    body.cast(),
    mass,
  );
  return result;
}

double rp3d_body_get_mass(Pointer<RP3D_RigidBody> body) {
  final result = GeneratedBindings.instance._rp3d_body_get_mass(body.cast());
  return result;
}

void rp3d_body_set_linear_velocity(
  Pointer<RP3D_RigidBody> body,
  Pointer<RP3D_Vector3> linearVelocity,
) {
  final result = GeneratedBindings.instance._rp3d_body_set_linear_velocity(
    body.cast(),
    linearVelocity.cast(),
  );
  return result;
}

void rp3d_body_get_linear_velocity(
  Pointer<RP3D_RigidBody> body,
  Pointer<RP3D_Vector3> outLinearVelocity,
) {
  final result = GeneratedBindings.instance._rp3d_body_get_linear_velocity(
    body.cast(),
    outLinearVelocity.cast(),
  );
  return result;
}

void rp3d_body_set_angular_velocity(
  Pointer<RP3D_RigidBody> body,
  Pointer<RP3D_Vector3> angularVelocity,
) {
  final result = GeneratedBindings.instance._rp3d_body_set_angular_velocity(
    body.cast(),
    angularVelocity.cast(),
  );
  return result;
}

void rp3d_body_get_angular_velocity(
  Pointer<RP3D_RigidBody> body,
  Pointer<RP3D_Vector3> outAngularVelocity,
) {
  final result = GeneratedBindings.instance._rp3d_body_get_angular_velocity(
    body.cast(),
    outAngularVelocity.cast(),
  );
  return result;
}

void rp3d_body_apply_force(
  Pointer<RP3D_RigidBody> body,
  Pointer<RP3D_Vector3> force,
) {
  final result = GeneratedBindings.instance._rp3d_body_apply_force(
    body.cast(),
    force.cast(),
  );
  return result;
}

void rp3d_body_apply_force_at_position(
  Pointer<RP3D_RigidBody> body,
  Pointer<RP3D_Vector3> force,
  Pointer<RP3D_Vector3> position,
) {
  final result = GeneratedBindings.instance._rp3d_body_apply_force_at_position(
    body.cast(),
    force.cast(),
    position.cast(),
  );
  return result;
}

void rp3d_body_apply_torque(
  Pointer<RP3D_RigidBody> body,
  Pointer<RP3D_Vector3> torque,
) {
  final result = GeneratedBindings.instance._rp3d_body_apply_torque(
    body.cast(),
    torque.cast(),
  );
  return result;
}

void rp3d_body_set_is_active(Pointer<RP3D_RigidBody> body, int isActive) {
  final result = GeneratedBindings.instance._rp3d_body_set_is_active(
    body.cast(),
    isActive,
  );
  return result;
}

int rp3d_body_get_is_active(Pointer<RP3D_RigidBody> body) {
  final result = GeneratedBindings.instance._rp3d_body_get_is_active(
    body.cast(),
  );
  return result;
}

void rp3d_body_set_is_sleeping_allowed(
  Pointer<RP3D_RigidBody> body,
  int isAllowed,
) {
  final result = GeneratedBindings.instance._rp3d_body_set_is_sleeping_allowed(
    body.cast(),
    isAllowed,
  );
  return result;
}

int rp3d_body_get_is_sleeping_allowed(Pointer<RP3D_RigidBody> body) {
  final result = GeneratedBindings.instance._rp3d_body_get_is_sleeping_allowed(
    body.cast(),
  );
  return result;
}

/// Gravity control
void rp3d_body_enable_gravity(Pointer<RP3D_RigidBody> body, int enableGravity) {
  final result = GeneratedBindings.instance._rp3d_body_enable_gravity(
    body.cast(),
    enableGravity,
  );
  return result;
}

int rp3d_body_is_gravity_enabled(Pointer<RP3D_RigidBody> body) {
  final result = GeneratedBindings.instance._rp3d_body_is_gravity_enabled(
    body.cast(),
  );
  return result;
}

/// Debug rendering
void rp3d_body_set_is_debug_enabled(
  Pointer<RP3D_RigidBody> body,
  int isEnabled,
) {
  final result = GeneratedBindings.instance._rp3d_body_set_is_debug_enabled(
    body.cast(),
    isEnabled,
  );
  return result;
}

int rp3d_body_get_is_debug_enabled(Pointer<RP3D_RigidBody> body) {
  final result = GeneratedBindings.instance._rp3d_body_get_is_debug_enabled(
    body.cast(),
  );
  return result;
}

/// Mass properties
void rp3d_body_update_mass_properties_from_colliders(
  Pointer<RP3D_RigidBody> body,
) {
  final result = GeneratedBindings.instance
      ._rp3d_body_update_mass_properties_from_colliders(body.cast());
  return result;
}

/// Collider management
Pointer<RP3D_Collider> rp3d_body_add_collider(
  Pointer<RP3D_RigidBody> body,
  Pointer<RP3D_CollisionShape> shape,
  Pointer<RP3D_Transform> transform,
) {
  final result = GeneratedBindings.instance._rp3d_body_add_collider(
    body.cast(),
    shape.cast(),
    transform.cast(),
  );
  return Pointer<RP3D_Collider>(result);
}

void rp3d_body_remove_collider(
  Pointer<RP3D_RigidBody> body,
  Pointer<RP3D_Collider> collider,
) {
  final result = GeneratedBindings.instance._rp3d_body_remove_collider(
    body.cast(),
    collider.cast(),
  );
  return result;
}

void rp3d_collider_set_material(
  Pointer<RP3D_Collider> collider,
  Pointer<RP3D_Material> material,
) {
  final result = GeneratedBindings.instance._rp3d_collider_set_material(
    collider.cast(),
    material.cast(),
  );
  return result;
}

/// ==================== Collider ====================
Pointer<RP3D_Material> rp3d_collider_get_material(
  Pointer<RP3D_Collider> collider,
) {
  final result = GeneratedBindings.instance._rp3d_collider_get_material(
    collider.cast(),
  );
  return Pointer<RP3D_Material>(result);
}

void rp3d_collider_get_local_bounds(
  Pointer<RP3D_Collider> collider,
  Pointer<RP3D_AABB> outAABB,
) {
  final result = GeneratedBindings.instance._rp3d_collider_get_local_bounds(
    collider.cast(),
    outAABB.cast(),
  );
  return result;
}

void rp3d_collider_set_is_trigger(
  Pointer<RP3D_Collider> collider,
  int isTrigger,
) {
  final result = GeneratedBindings.instance._rp3d_collider_set_is_trigger(
    collider.cast(),
    isTrigger,
  );
  return result;
}

int rp3d_collider_get_is_trigger(Pointer<RP3D_Collider> collider) {
  final result = GeneratedBindings.instance._rp3d_collider_get_is_trigger(
    collider.cast(),
  );
  return result;
}

/// ==================== Material ====================
void rp3d_material_destroy(Pointer<RP3D_Material> material) {
  final result = GeneratedBindings.instance._rp3d_material_destroy(
    material.cast(),
  );
  return result;
}

void rp3d_material_set_bounciness(
  Pointer<RP3D_Material> material,
  double bounciness,
) {
  final result = GeneratedBindings.instance._rp3d_material_set_bounciness(
    material.cast(),
    bounciness,
  );
  return result;
}

double rp3d_material_get_bounciness(Pointer<RP3D_Material> material) {
  final result = GeneratedBindings.instance._rp3d_material_get_bounciness(
    material.cast(),
  );
  return result;
}

void rp3d_material_set_friction_coefficient(
  Pointer<RP3D_Material> material,
  double frictionCoefficient,
) {
  final result = GeneratedBindings.instance
      ._rp3d_material_set_friction_coefficient(
        material.cast(),
        frictionCoefficient,
      );
  return result;
}

double rp3d_material_get_friction_coefficient(Pointer<RP3D_Material> material) {
  final result = GeneratedBindings.instance
      ._rp3d_material_get_friction_coefficient(material.cast());
  return result;
}

void rp3d_material_set_mass_density(
  Pointer<RP3D_Material> material,
  double massDensity,
) {
  final result = GeneratedBindings.instance._rp3d_material_set_mass_density(
    material.cast(),
    massDensity,
  );
  return result;
}

double rp3d_material_get_mass_density(Pointer<RP3D_Material> material) {
  final result = GeneratedBindings.instance._rp3d_material_get_mass_density(
    material.cast(),
  );
  return result;
}

/// ==================== CollisionShape (base) ====================
void rp3d_shape_get_local_bounds(
  Pointer<RP3D_CollisionShape> shape,
  Pointer<RP3D_AABB> outAABB,
) {
  final result = GeneratedBindings.instance._rp3d_shape_get_local_bounds(
    shape.cast(),
    outAABB.cast(),
  );
  return result;
}

void rp3d_concave_shape_set_scale(
  Pointer<RP3D_HeightFieldShape> shape,
  Pointer<RP3D_Vector3> scale,
) {
  final result = GeneratedBindings.instance._rp3d_concave_shape_set_scale(
    shape.cast(),
    scale.cast(),
  );
  return result;
}

/// ==================== HeightFieldShape ====================
void rp3d_height_field_shape_get_vertex_at(
  Pointer<RP3D_HeightFieldShape> heightFieldShape,
  int row,
  int column,
  Pointer<RP3D_Vector3> outVertex,
) {
  final result = GeneratedBindings.instance
      ._rp3d_height_field_shape_get_vertex_at(
        heightFieldShape.cast(),
        row,
        column,
        outVertex.cast(),
      );
  return result;
}

/// Vector3
void rp3d_vector3_zero(Pointer<RP3D_Vector3> v) {
  final result = GeneratedBindings.instance._rp3d_vector3_zero(v.cast());
  return result;
}

double rp3d_vector3_length(Pointer<RP3D_Vector3> v) {
  final result = GeneratedBindings.instance._rp3d_vector3_length(v.cast());
  return result;
}

void rp3d_vector3_normalize(Pointer<RP3D_Vector3> v) {
  final result = GeneratedBindings.instance._rp3d_vector3_normalize(v.cast());
  return result;
}

double rp3d_vector3_dot(Pointer<RP3D_Vector3> v1, Pointer<RP3D_Vector3> v2) {
  final result = GeneratedBindings.instance._rp3d_vector3_dot(
    v1.cast(),
    v2.cast(),
  );
  return result;
}

void rp3d_vector3_cross(
  Pointer<RP3D_Vector3> v1,
  Pointer<RP3D_Vector3> v2,
  Pointer<RP3D_Vector3> outResult,
) {
  final result = GeneratedBindings.instance._rp3d_vector3_cross(
    v1.cast(),
    v2.cast(),
    outResult.cast(),
  );
  return result;
}

/// Quaternion
void rp3d_quaternion_identity(Pointer<RP3D_Quaternion> q) {
  final result = GeneratedBindings.instance._rp3d_quaternion_identity(q.cast());
  return result;
}

void rp3d_quaternion_from_axis_angle(
  Pointer<RP3D_Vector3> axis,
  double angle,
  Pointer<RP3D_Quaternion> outQuat,
) {
  final result = GeneratedBindings.instance._rp3d_quaternion_from_axis_angle(
    axis.cast(),
    angle,
    outQuat.cast(),
  );
  return result;
}

void rp3d_quaternion_normalize(Pointer<RP3D_Quaternion> q) {
  final result = GeneratedBindings.instance._rp3d_quaternion_normalize(
    q.cast(),
  );
  return result;
}

/// Transform
void rp3d_transform_identity(Pointer<RP3D_Transform> t) {
  final result = GeneratedBindings.instance._rp3d_transform_identity(t.cast());
  return result;
}

void rp3d_transform_inverse(
  Pointer<RP3D_Transform> t,
  Pointer<RP3D_Transform> outInverse,
) {
  final result = GeneratedBindings.instance._rp3d_transform_inverse(
    t.cast(),
    outInverse.cast(),
  );
  return result;
}

void rp3d_transform_get_opengl_matrix(
  Pointer<RP3D_Transform> t,
  Pointer<Float32> outMatrix,
) {
  final result = GeneratedBindings.instance._rp3d_transform_get_opengl_matrix(
    t.cast(),
    outMatrix,
  );
  return result;
}

/// ==================== DebugRenderer ====================
void rp3d_debug_renderer_set_is_debug_item_displayed(
  Pointer<RP3D_DebugRenderer> renderer,
  int item,
  int isDisplayed,
) {
  final result = GeneratedBindings.instance
      ._rp3d_debug_renderer_set_is_debug_item_displayed(
        renderer.cast(),
        item,
        isDisplayed,
      );
  return result;
}

int rp3d_debug_renderer_get_is_debug_item_displayed(
  Pointer<RP3D_DebugRenderer> renderer,
  int item,
) {
  final result = GeneratedBindings.instance
      ._rp3d_debug_renderer_get_is_debug_item_displayed(renderer.cast(), item);
  return result;
}

int rp3d_debug_renderer_get_nb_lines(Pointer<RP3D_DebugRenderer> renderer) {
  final result = GeneratedBindings.instance._rp3d_debug_renderer_get_nb_lines(
    renderer.cast(),
  );
  return result;
}

int rp3d_debug_renderer_get_nb_triangles(Pointer<RP3D_DebugRenderer> renderer) {
  final result = GeneratedBindings.instance
      ._rp3d_debug_renderer_get_nb_triangles(renderer.cast());
  return result;
}

void rp3d_debug_renderer_get_lines_array(
  Pointer<RP3D_DebugRenderer> renderer,
  Pointer<Float32> outVertices,
  Pointer<Uint32> outColors,
) {
  final result = GeneratedBindings.instance
      ._rp3d_debug_renderer_get_lines_array(
        renderer.cast(),
        outVertices,
        outColors,
      );
  return result;
}

void rp3d_debug_renderer_get_triangles_array(
  Pointer<RP3D_DebugRenderer> renderer,
  Pointer<Float32> outVertices,
  Pointer<Uint32> outColors,
) {
  final result = GeneratedBindings.instance
      ._rp3d_debug_renderer_get_triangles_array(
        renderer.cast(),
        outVertices,
        outColors,
      );
  return result;
}

/// ==================== Joints ====================
Pointer<RP3D_BallAndSocketJoint> rp3d_world_create_ball_and_socket_joint(
  Pointer<RP3D_PhysicsWorld> world,
  Pointer<RP3D_BallAndSocketJointInfo> jointInfo,
) {
  final result = GeneratedBindings.instance
      ._rp3d_world_create_ball_and_socket_joint(world.cast(), jointInfo.cast());
  return Pointer<RP3D_BallAndSocketJoint>(result);
}

Pointer<RP3D_HingeJoint> rp3d_world_create_hinge_joint(
  Pointer<RP3D_PhysicsWorld> world,
  Pointer<RP3D_HingeJointInfo> jointInfo,
) {
  final result = GeneratedBindings.instance._rp3d_world_create_hinge_joint(
    world.cast(),
    jointInfo.cast(),
  );
  return Pointer<RP3D_HingeJoint>(result);
}

Pointer<RP3D_SliderJoint> rp3d_world_create_slider_joint(
  Pointer<RP3D_PhysicsWorld> world,
  Pointer<RP3D_SliderJointInfo> jointInfo,
) {
  final result = GeneratedBindings.instance._rp3d_world_create_slider_joint(
    world.cast(),
    jointInfo.cast(),
  );
  return Pointer<RP3D_SliderJoint>(result);
}

Pointer<RP3D_FixedJoint> rp3d_world_create_fixed_joint(
  Pointer<RP3D_PhysicsWorld> world,
  Pointer<RP3D_FixedJointInfo> jointInfo,
) {
  final result = GeneratedBindings.instance._rp3d_world_create_fixed_joint(
    world.cast(),
    jointInfo.cast(),
  );
  return Pointer<RP3D_FixedJoint>(result);
}

void rp3d_world_destroy_joint(
  Pointer<RP3D_PhysicsWorld> world,
  Pointer<Void> joint,
) {
  final result = GeneratedBindings.instance._rp3d_world_destroy_joint(
    world.cast(),
    joint,
  );
  return result;
}

extension RP3D_PhysicsCommonExt on Pointer<RP3D_PhysicsCommon> {
  RP3D_PhysicsCommon toDart() {
    return RP3D_PhysicsCommon(this);
  }
}

final class RP3D_PhysicsCommon extends Struct {
  Pointer<RP3D_PhysicsCommon> get address => super.address.cast();
  RP3D_PhysicsCommon(super.address);

  static Pointer<RP3D_PhysicsCommon> stackAlloc() {
    return Pointer<RP3D_PhysicsCommon>(
      NativeLibrary.instance.stackAlloc<RP3D_PhysicsCommon>(0),
    );
  }
}

extension RP3D_PhysicsWorldExt on Pointer<RP3D_PhysicsWorld> {
  RP3D_PhysicsWorld toDart() {
    return RP3D_PhysicsWorld(this);
  }
}

final class RP3D_PhysicsWorld extends Struct {
  Pointer<RP3D_PhysicsWorld> get address => super.address.cast();
  RP3D_PhysicsWorld(super.address);

  static Pointer<RP3D_PhysicsWorld> stackAlloc() {
    return Pointer<RP3D_PhysicsWorld>(
      NativeLibrary.instance.stackAlloc<RP3D_PhysicsWorld>(0),
    );
  }
}

extension RP3D_BoxShapeExt on Pointer<RP3D_BoxShape> {
  RP3D_BoxShape toDart() {
    return RP3D_BoxShape(this);
  }
}

final class RP3D_BoxShape extends Struct {
  Pointer<RP3D_BoxShape> get address => super.address.cast();
  RP3D_BoxShape(super.address);

  static Pointer<RP3D_BoxShape> stackAlloc() {
    return Pointer<RP3D_BoxShape>(
      NativeLibrary.instance.stackAlloc<RP3D_BoxShape>(0),
    );
  }
}

/// ==================== Value Types (POD Structs) ====================

extension RP3D_Vector3Ext on Pointer<RP3D_Vector3> {
  RP3D_Vector3 toDart() {
    return RP3D_Vector3(this);
  }
}

final class RP3D_Vector3 extends Struct {
  Pointer<RP3D_Vector3> get address => super.address.cast();
  double get x {
    final addr = this.address + 0;
    final value = NativeLibrary.instance.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set x(double val) {
    NativeLibrary.instance.setValue(this.address + 0, val.toJS, 'float');
  }

  double get y {
    final addr = this.address + 4;
    final value = NativeLibrary.instance.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set y(double val) {
    NativeLibrary.instance.setValue(this.address + 4, val.toJS, 'float');
  }

  double get z {
    final addr = this.address + 8;
    final value = NativeLibrary.instance.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set z(double val) {
    NativeLibrary.instance.setValue(this.address + 8, val.toJS, 'float');
  }

  RP3D_Vector3(super.address);

  static Pointer<RP3D_Vector3> stackAlloc() {
    return Pointer<RP3D_Vector3>(
      NativeLibrary.instance.stackAlloc<RP3D_Vector3>(12),
    );
  }
}

extension RP3D_SphereShapeExt on Pointer<RP3D_SphereShape> {
  RP3D_SphereShape toDart() {
    return RP3D_SphereShape(this);
  }
}

final class RP3D_SphereShape extends Struct {
  Pointer<RP3D_SphereShape> get address => super.address.cast();
  RP3D_SphereShape(super.address);

  static Pointer<RP3D_SphereShape> stackAlloc() {
    return Pointer<RP3D_SphereShape>(
      NativeLibrary.instance.stackAlloc<RP3D_SphereShape>(0),
    );
  }
}

extension RP3D_CapsuleShapeExt on Pointer<RP3D_CapsuleShape> {
  RP3D_CapsuleShape toDart() {
    return RP3D_CapsuleShape(this);
  }
}

final class RP3D_CapsuleShape extends Struct {
  Pointer<RP3D_CapsuleShape> get address => super.address.cast();
  RP3D_CapsuleShape(super.address);

  static Pointer<RP3D_CapsuleShape> stackAlloc() {
    return Pointer<RP3D_CapsuleShape>(
      NativeLibrary.instance.stackAlloc<RP3D_CapsuleShape>(0),
    );
  }
}

extension RP3D_HeightFieldExt on Pointer<RP3D_HeightField> {
  RP3D_HeightField toDart() {
    return RP3D_HeightField(this);
  }
}

final class RP3D_HeightField extends Struct {
  Pointer<RP3D_HeightField> get address => super.address.cast();
  RP3D_HeightField(super.address);

  static Pointer<RP3D_HeightField> stackAlloc() {
    return Pointer<RP3D_HeightField>(
      NativeLibrary.instance.stackAlloc<RP3D_HeightField>(0),
    );
  }
}

extension RP3D_HeightFieldShapeExt on Pointer<RP3D_HeightFieldShape> {
  RP3D_HeightFieldShape toDart() {
    return RP3D_HeightFieldShape(this);
  }
}

final class RP3D_HeightFieldShape extends Struct {
  Pointer<RP3D_HeightFieldShape> get address => super.address.cast();
  RP3D_HeightFieldShape(super.address);

  static Pointer<RP3D_HeightFieldShape> stackAlloc() {
    return Pointer<RP3D_HeightFieldShape>(
      NativeLibrary.instance.stackAlloc<RP3D_HeightFieldShape>(0),
    );
  }
}

extension RP3D_TriangleVertexArrayExt on Pointer<RP3D_TriangleVertexArray> {
  RP3D_TriangleVertexArray toDart() {
    return RP3D_TriangleVertexArray(this);
  }
}

final class RP3D_TriangleVertexArray extends Struct {
  Pointer<RP3D_TriangleVertexArray> get address => super.address.cast();
  RP3D_TriangleVertexArray(super.address);

  static Pointer<RP3D_TriangleVertexArray> stackAlloc() {
    return Pointer<RP3D_TriangleVertexArray>(
      NativeLibrary.instance.stackAlloc<RP3D_TriangleVertexArray>(0),
    );
  }
}

extension RP3D_PolygonVertexArrayExt on Pointer<RP3D_PolygonVertexArray> {
  RP3D_PolygonVertexArray toDart() {
    return RP3D_PolygonVertexArray(this);
  }
}

final class RP3D_PolygonVertexArray extends Struct {
  Pointer<RP3D_PolygonVertexArray> get address => super.address.cast();
  RP3D_PolygonVertexArray(super.address);

  static Pointer<RP3D_PolygonVertexArray> stackAlloc() {
    return Pointer<RP3D_PolygonVertexArray>(
      NativeLibrary.instance.stackAlloc<RP3D_PolygonVertexArray>(0),
    );
  }
}

extension RP3D_TriangleMeshExt on Pointer<RP3D_TriangleMesh> {
  RP3D_TriangleMesh toDart() {
    return RP3D_TriangleMesh(this);
  }
}

final class RP3D_TriangleMesh extends Struct {
  Pointer<RP3D_TriangleMesh> get address => super.address.cast();
  RP3D_TriangleMesh(super.address);

  static Pointer<RP3D_TriangleMesh> stackAlloc() {
    return Pointer<RP3D_TriangleMesh>(
      NativeLibrary.instance.stackAlloc<RP3D_TriangleMesh>(0),
    );
  }
}

extension RP3D_ConvexMeshExt on Pointer<RP3D_ConvexMesh> {
  RP3D_ConvexMesh toDart() {
    return RP3D_ConvexMesh(this);
  }
}

final class RP3D_ConvexMesh extends Struct {
  Pointer<RP3D_ConvexMesh> get address => super.address.cast();
  RP3D_ConvexMesh(super.address);

  static Pointer<RP3D_ConvexMesh> stackAlloc() {
    return Pointer<RP3D_ConvexMesh>(
      NativeLibrary.instance.stackAlloc<RP3D_ConvexMesh>(0),
    );
  }
}

extension RP3D_ConvexMeshShapeExt on Pointer<RP3D_ConvexMeshShape> {
  RP3D_ConvexMeshShape toDart() {
    return RP3D_ConvexMeshShape(this);
  }
}

final class RP3D_ConvexMeshShape extends Struct {
  Pointer<RP3D_ConvexMeshShape> get address => super.address.cast();
  RP3D_ConvexMeshShape(super.address);

  static Pointer<RP3D_ConvexMeshShape> stackAlloc() {
    return Pointer<RP3D_ConvexMeshShape>(
      NativeLibrary.instance.stackAlloc<RP3D_ConvexMeshShape>(0),
    );
  }
}

extension RP3D_ConcaveMeshShapeExt on Pointer<RP3D_ConcaveMeshShape> {
  RP3D_ConcaveMeshShape toDart() {
    return RP3D_ConcaveMeshShape(this);
  }
}

final class RP3D_ConcaveMeshShape extends Struct {
  Pointer<RP3D_ConcaveMeshShape> get address => super.address.cast();
  RP3D_ConcaveMeshShape(super.address);

  static Pointer<RP3D_ConcaveMeshShape> stackAlloc() {
    return Pointer<RP3D_ConcaveMeshShape>(
      NativeLibrary.instance.stackAlloc<RP3D_ConcaveMeshShape>(0),
    );
  }
}

extension RP3D_DebugRendererExt on Pointer<RP3D_DebugRenderer> {
  RP3D_DebugRenderer toDart() {
    return RP3D_DebugRenderer(this);
  }
}

final class RP3D_DebugRenderer extends Struct {
  Pointer<RP3D_DebugRenderer> get address => super.address.cast();
  RP3D_DebugRenderer(super.address);

  static Pointer<RP3D_DebugRenderer> stackAlloc() {
    return Pointer<RP3D_DebugRenderer>(
      NativeLibrary.instance.stackAlloc<RP3D_DebugRenderer>(0),
    );
  }
}

extension RP3D_RigidBodyExt on Pointer<RP3D_RigidBody> {
  RP3D_RigidBody toDart() {
    return RP3D_RigidBody(this);
  }
}

final class RP3D_RigidBody extends Struct {
  Pointer<RP3D_RigidBody> get address => super.address.cast();
  RP3D_RigidBody(super.address);

  static Pointer<RP3D_RigidBody> stackAlloc() {
    return Pointer<RP3D_RigidBody>(
      NativeLibrary.instance.stackAlloc<RP3D_RigidBody>(0),
    );
  }
}

extension RP3D_TransformExt on Pointer<RP3D_Transform> {
  RP3D_Transform toDart() {
    return RP3D_Transform(this);
  }
}

final class RP3D_Transform extends Struct {
  Pointer<RP3D_Transform> get address => super.address.cast();
  RP3D_Vector3 get position {
    final addr = this.address + 0;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return RP3D_Vector3(Pointer<RP3D_Vector3>(addr));
  }

  set position(RP3D_Vector3 val) {
    NativeLibrary.instance.setValue(this.address + 0, val.address.toJS, '*');
  }

  RP3D_Quaternion get orientation {
    final addr = this.address + 12;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return RP3D_Quaternion(Pointer<RP3D_Quaternion>(addr));
  }

  set orientation(RP3D_Quaternion val) {
    NativeLibrary.instance.setValue(this.address + 12, val.address.toJS, '*');
  }

  RP3D_Transform(super.address);

  static Pointer<RP3D_Transform> stackAlloc() {
    return Pointer<RP3D_Transform>(
      NativeLibrary.instance.stackAlloc<RP3D_Transform>(28),
    );
  }
}

extension RP3D_QuaternionExt on Pointer<RP3D_Quaternion> {
  RP3D_Quaternion toDart() {
    return RP3D_Quaternion(this);
  }
}

final class RP3D_Quaternion extends Struct {
  Pointer<RP3D_Quaternion> get address => super.address.cast();
  double get x {
    final addr = this.address + 0;
    final value = NativeLibrary.instance.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set x(double val) {
    NativeLibrary.instance.setValue(this.address + 0, val.toJS, 'float');
  }

  double get y {
    final addr = this.address + 4;
    final value = NativeLibrary.instance.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set y(double val) {
    NativeLibrary.instance.setValue(this.address + 4, val.toJS, 'float');
  }

  double get z {
    final addr = this.address + 8;
    final value = NativeLibrary.instance.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set z(double val) {
    NativeLibrary.instance.setValue(this.address + 8, val.toJS, 'float');
  }

  double get w {
    final addr = this.address + 12;
    final value = NativeLibrary.instance.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set w(double val) {
    NativeLibrary.instance.setValue(this.address + 12, val.toJS, 'float');
  }

  RP3D_Quaternion(super.address);

  static Pointer<RP3D_Quaternion> stackAlloc() {
    return Pointer<RP3D_Quaternion>(
      NativeLibrary.instance.stackAlloc<RP3D_Quaternion>(16),
    );
  }
}

extension RP3D_RayExt on Pointer<RP3D_Ray> {
  RP3D_Ray toDart() {
    return RP3D_Ray(this);
  }
}

final class RP3D_Ray extends Struct {
  Pointer<RP3D_Ray> get address => super.address.cast();
  RP3D_Vector3 get point1 {
    final addr = this.address + 0;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return RP3D_Vector3(Pointer<RP3D_Vector3>(addr));
  }

  set point1(RP3D_Vector3 val) {
    NativeLibrary.instance.setValue(this.address + 0, val.address.toJS, '*');
  }

  RP3D_Vector3 get point2 {
    final addr = this.address + 12;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return RP3D_Vector3(Pointer<RP3D_Vector3>(addr));
  }

  set point2(RP3D_Vector3 val) {
    NativeLibrary.instance.setValue(this.address + 12, val.address.toJS, '*');
  }

  double get maxFraction {
    final addr = this.address + 24;
    final value = NativeLibrary.instance.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set maxFraction(double val) {
    NativeLibrary.instance.setValue(this.address + 24, val.toJS, 'float');
  }

  RP3D_Ray(super.address);

  static Pointer<RP3D_Ray> stackAlloc() {
    return Pointer<RP3D_Ray>(NativeLibrary.instance.stackAlloc<RP3D_Ray>(28));
  }
}

extension RP3D_RaycastInfoExt on Pointer<RP3D_RaycastInfo> {
  RP3D_RaycastInfo toDart() {
    return RP3D_RaycastInfo(this);
  }
}

final class RP3D_RaycastInfo extends Struct {
  Pointer<RP3D_RaycastInfo> get address => super.address.cast();
  Pointer<RP3D_RigidBody> get body {
    final addr = this.address + 0;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Pointer<RP3D_RigidBody>(value.toDartInt);
  }

  set body(Pointer<RP3D_RigidBody> val) {
    NativeLibrary.instance.setValue(this.address + 0, val.toJS, '*');
  }

  Pointer<RP3D_Collider> get collider {
    final addr = this.address + 4;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Pointer<RP3D_Collider>(value.toDartInt);
  }

  set collider(Pointer<RP3D_Collider> val) {
    NativeLibrary.instance.setValue(this.address + 4, val.toJS, '*');
  }

  RP3D_Vector3 get worldPoint {
    final addr = this.address + 8;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return RP3D_Vector3(Pointer<RP3D_Vector3>(addr));
  }

  set worldPoint(RP3D_Vector3 val) {
    NativeLibrary.instance.setValue(this.address + 8, val.address.toJS, '*');
  }

  RP3D_Vector3 get worldNormal {
    final addr = this.address + 20;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return RP3D_Vector3(Pointer<RP3D_Vector3>(addr));
  }

  set worldNormal(RP3D_Vector3 val) {
    NativeLibrary.instance.setValue(this.address + 20, val.address.toJS, '*');
  }

  double get hitFraction {
    final addr = this.address + 32;
    final value = NativeLibrary.instance.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set hitFraction(double val) {
    NativeLibrary.instance.setValue(this.address + 32, val.toJS, 'float');
  }

  RP3D_RaycastInfo(super.address);

  static Pointer<RP3D_RaycastInfo> stackAlloc() {
    return Pointer<RP3D_RaycastInfo>(
      NativeLibrary.instance.stackAlloc<RP3D_RaycastInfo>(36),
    );
  }
}

extension RP3D_ColliderExt on Pointer<RP3D_Collider> {
  RP3D_Collider toDart() {
    return RP3D_Collider(this);
  }
}

final class RP3D_Collider extends Struct {
  Pointer<RP3D_Collider> get address => super.address.cast();
  RP3D_Collider(super.address);

  static Pointer<RP3D_Collider> stackAlloc() {
    return Pointer<RP3D_Collider>(
      NativeLibrary.instance.stackAlloc<RP3D_Collider>(0),
    );
  }
}

/// ==================== Enums ====================
sealed class RP3D_BodyType {
  static const RP3D_BODY_TYPE_STATIC = 1;
  static const RP3D_BODY_TYPE_KINEMATIC = 2;
  static const RP3D_BODY_TYPE_DYNAMIC = 3;
}

extension RP3D_CollisionShapeExt on Pointer<RP3D_CollisionShape> {
  RP3D_CollisionShape toDart() {
    return RP3D_CollisionShape(this);
  }
}

final class RP3D_CollisionShape extends Struct {
  Pointer<RP3D_CollisionShape> get address => super.address.cast();
  RP3D_CollisionShape(super.address);

  static Pointer<RP3D_CollisionShape> stackAlloc() {
    return Pointer<RP3D_CollisionShape>(
      NativeLibrary.instance.stackAlloc<RP3D_CollisionShape>(0),
    );
  }
}

extension RP3D_MaterialExt on Pointer<RP3D_Material> {
  RP3D_Material toDart() {
    return RP3D_Material(this);
  }
}

final class RP3D_Material extends Struct {
  Pointer<RP3D_Material> get address => super.address.cast();
  RP3D_Material(super.address);

  static Pointer<RP3D_Material> stackAlloc() {
    return Pointer<RP3D_Material>(
      NativeLibrary.instance.stackAlloc<RP3D_Material>(0),
    );
  }
}

extension RP3D_AABBExt on Pointer<RP3D_AABB> {
  RP3D_AABB toDart() {
    return RP3D_AABB(this);
  }
}

final class RP3D_AABB extends Struct {
  Pointer<RP3D_AABB> get address => super.address.cast();
  RP3D_Vector3 get min {
    final addr = this.address + 0;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return RP3D_Vector3(Pointer<RP3D_Vector3>(addr));
  }

  set min(RP3D_Vector3 val) {
    NativeLibrary.instance.setValue(this.address + 0, val.address.toJS, '*');
  }

  RP3D_Vector3 get max {
    final addr = this.address + 12;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return RP3D_Vector3(Pointer<RP3D_Vector3>(addr));
  }

  set max(RP3D_Vector3 val) {
    NativeLibrary.instance.setValue(this.address + 12, val.address.toJS, '*');
  }

  RP3D_AABB(super.address);

  static Pointer<RP3D_AABB> stackAlloc() {
    return Pointer<RP3D_AABB>(NativeLibrary.instance.stackAlloc<RP3D_AABB>(24));
  }
}

sealed class RP3D_DebugItem {
  static const RP3D_DEBUG_ITEM_COLLIDER_AABB = 1;
  static const RP3D_DEBUG_ITEM_COLLIDER_BROADPHASE_AABB = 2;
  static const RP3D_DEBUG_ITEM_COLLISION_SHAPE = 4;
  static const RP3D_DEBUG_ITEM_CONTACT_POINT = 8;
  static const RP3D_DEBUG_ITEM_CONTACT_NORMAL = 16;
}

extension RP3D_BallAndSocketJointExt on Pointer<RP3D_BallAndSocketJoint> {
  RP3D_BallAndSocketJoint toDart() {
    return RP3D_BallAndSocketJoint(this);
  }
}

final class RP3D_BallAndSocketJoint extends Struct {
  Pointer<RP3D_BallAndSocketJoint> get address => super.address.cast();
  RP3D_BallAndSocketJoint(super.address);

  static Pointer<RP3D_BallAndSocketJoint> stackAlloc() {
    return Pointer<RP3D_BallAndSocketJoint>(
      NativeLibrary.instance.stackAlloc<RP3D_BallAndSocketJoint>(0),
    );
  }
}

/// Joint info structures

extension RP3D_BallAndSocketJointInfoExt
    on Pointer<RP3D_BallAndSocketJointInfo> {
  RP3D_BallAndSocketJointInfo toDart() {
    return RP3D_BallAndSocketJointInfo(this);
  }
}

final class RP3D_BallAndSocketJointInfo extends Struct {
  Pointer<RP3D_BallAndSocketJointInfo> get address => super.address.cast();
  RP3D_Vector3 get anchorPointWorldSpace {
    final addr = this.address + 0;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return RP3D_Vector3(Pointer<RP3D_Vector3>(addr));
  }

  set anchorPointWorldSpace(RP3D_Vector3 val) {
    NativeLibrary.instance.setValue(this.address + 0, val.address.toJS, '*');
  }

  Pointer<RP3D_RigidBody> get body1 {
    final addr = this.address + 12;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Pointer<RP3D_RigidBody>(value.toDartInt);
  }

  set body1(Pointer<RP3D_RigidBody> val) {
    NativeLibrary.instance.setValue(this.address + 12, val.toJS, '*');
  }

  Pointer<RP3D_RigidBody> get body2 {
    final addr = this.address + 16;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Pointer<RP3D_RigidBody>(value.toDartInt);
  }

  set body2(Pointer<RP3D_RigidBody> val) {
    NativeLibrary.instance.setValue(this.address + 16, val.toJS, '*');
  }

  int get isCollisionEnabled {
    final addr = this.address + 20;
    final value = NativeLibrary.instance.getValue(addr, 'i8').toDartInt;
    return value;
  }

  set isCollisionEnabled(int val) {
    NativeLibrary.instance.setValue(this.address + 20, val.toJS, 'i8');
  }

  RP3D_BallAndSocketJointInfo(super.address);

  static Pointer<RP3D_BallAndSocketJointInfo> stackAlloc() {
    return Pointer<RP3D_BallAndSocketJointInfo>(
      NativeLibrary.instance.stackAlloc<RP3D_BallAndSocketJointInfo>(21),
    );
  }
}

extension RP3D_HingeJointExt on Pointer<RP3D_HingeJoint> {
  RP3D_HingeJoint toDart() {
    return RP3D_HingeJoint(this);
  }
}

final class RP3D_HingeJoint extends Struct {
  Pointer<RP3D_HingeJoint> get address => super.address.cast();
  RP3D_HingeJoint(super.address);

  static Pointer<RP3D_HingeJoint> stackAlloc() {
    return Pointer<RP3D_HingeJoint>(
      NativeLibrary.instance.stackAlloc<RP3D_HingeJoint>(0),
    );
  }
}

extension RP3D_HingeJointInfoExt on Pointer<RP3D_HingeJointInfo> {
  RP3D_HingeJointInfo toDart() {
    return RP3D_HingeJointInfo(this);
  }
}

final class RP3D_HingeJointInfo extends Struct {
  Pointer<RP3D_HingeJointInfo> get address => super.address.cast();
  RP3D_Vector3 get anchorPointWorldSpace {
    final addr = this.address + 0;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return RP3D_Vector3(Pointer<RP3D_Vector3>(addr));
  }

  set anchorPointWorldSpace(RP3D_Vector3 val) {
    NativeLibrary.instance.setValue(this.address + 0, val.address.toJS, '*');
  }

  RP3D_Vector3 get rotationAxisWorld {
    final addr = this.address + 12;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return RP3D_Vector3(Pointer<RP3D_Vector3>(addr));
  }

  set rotationAxisWorld(RP3D_Vector3 val) {
    NativeLibrary.instance.setValue(this.address + 12, val.address.toJS, '*');
  }

  Pointer<RP3D_RigidBody> get body1 {
    final addr = this.address + 24;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Pointer<RP3D_RigidBody>(value.toDartInt);
  }

  set body1(Pointer<RP3D_RigidBody> val) {
    NativeLibrary.instance.setValue(this.address + 24, val.toJS, '*');
  }

  Pointer<RP3D_RigidBody> get body2 {
    final addr = this.address + 28;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Pointer<RP3D_RigidBody>(value.toDartInt);
  }

  set body2(Pointer<RP3D_RigidBody> val) {
    NativeLibrary.instance.setValue(this.address + 28, val.toJS, '*');
  }

  int get isCollisionEnabled {
    final addr = this.address + 32;
    final value = NativeLibrary.instance.getValue(addr, 'i8').toDartInt;
    return value;
  }

  set isCollisionEnabled(int val) {
    NativeLibrary.instance.setValue(this.address + 32, val.toJS, 'i8');
  }

  int get isLimitEnabled {
    final addr = this.address + 33;
    final value = NativeLibrary.instance.getValue(addr, 'i8').toDartInt;
    return value;
  }

  set isLimitEnabled(int val) {
    NativeLibrary.instance.setValue(this.address + 33, val.toJS, 'i8');
  }

  int get isMotorEnabled {
    final addr = this.address + 34;
    final value = NativeLibrary.instance.getValue(addr, 'i8').toDartInt;
    return value;
  }

  set isMotorEnabled(int val) {
    NativeLibrary.instance.setValue(this.address + 34, val.toJS, 'i8');
  }

  double get minAngleLimit {
    final addr = this.address + 35;
    final value = NativeLibrary.instance.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set minAngleLimit(double val) {
    NativeLibrary.instance.setValue(this.address + 35, val.toJS, 'float');
  }

  double get maxAngleLimit {
    final addr = this.address + 39;
    final value = NativeLibrary.instance.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set maxAngleLimit(double val) {
    NativeLibrary.instance.setValue(this.address + 39, val.toJS, 'float');
  }

  double get motorSpeed {
    final addr = this.address + 43;
    final value = NativeLibrary.instance.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set motorSpeed(double val) {
    NativeLibrary.instance.setValue(this.address + 43, val.toJS, 'float');
  }

  double get maxMotorTorque {
    final addr = this.address + 47;
    final value = NativeLibrary.instance.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set maxMotorTorque(double val) {
    NativeLibrary.instance.setValue(this.address + 47, val.toJS, 'float');
  }

  RP3D_HingeJointInfo(super.address);

  static Pointer<RP3D_HingeJointInfo> stackAlloc() {
    return Pointer<RP3D_HingeJointInfo>(
      NativeLibrary.instance.stackAlloc<RP3D_HingeJointInfo>(51),
    );
  }
}

extension RP3D_SliderJointExt on Pointer<RP3D_SliderJoint> {
  RP3D_SliderJoint toDart() {
    return RP3D_SliderJoint(this);
  }
}

final class RP3D_SliderJoint extends Struct {
  Pointer<RP3D_SliderJoint> get address => super.address.cast();
  RP3D_SliderJoint(super.address);

  static Pointer<RP3D_SliderJoint> stackAlloc() {
    return Pointer<RP3D_SliderJoint>(
      NativeLibrary.instance.stackAlloc<RP3D_SliderJoint>(0),
    );
  }
}

extension RP3D_SliderJointInfoExt on Pointer<RP3D_SliderJointInfo> {
  RP3D_SliderJointInfo toDart() {
    return RP3D_SliderJointInfo(this);
  }
}

final class RP3D_SliderJointInfo extends Struct {
  Pointer<RP3D_SliderJointInfo> get address => super.address.cast();
  RP3D_Vector3 get anchorPointWorldSpace {
    final addr = this.address + 0;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return RP3D_Vector3(Pointer<RP3D_Vector3>(addr));
  }

  set anchorPointWorldSpace(RP3D_Vector3 val) {
    NativeLibrary.instance.setValue(this.address + 0, val.address.toJS, '*');
  }

  RP3D_Vector3 get sliderAxisWorldSpace {
    final addr = this.address + 12;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return RP3D_Vector3(Pointer<RP3D_Vector3>(addr));
  }

  set sliderAxisWorldSpace(RP3D_Vector3 val) {
    NativeLibrary.instance.setValue(this.address + 12, val.address.toJS, '*');
  }

  Pointer<RP3D_RigidBody> get body1 {
    final addr = this.address + 24;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Pointer<RP3D_RigidBody>(value.toDartInt);
  }

  set body1(Pointer<RP3D_RigidBody> val) {
    NativeLibrary.instance.setValue(this.address + 24, val.toJS, '*');
  }

  Pointer<RP3D_RigidBody> get body2 {
    final addr = this.address + 28;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Pointer<RP3D_RigidBody>(value.toDartInt);
  }

  set body2(Pointer<RP3D_RigidBody> val) {
    NativeLibrary.instance.setValue(this.address + 28, val.toJS, '*');
  }

  int get isCollisionEnabled {
    final addr = this.address + 32;
    final value = NativeLibrary.instance.getValue(addr, 'i8').toDartInt;
    return value;
  }

  set isCollisionEnabled(int val) {
    NativeLibrary.instance.setValue(this.address + 32, val.toJS, 'i8');
  }

  int get isLimitEnabled {
    final addr = this.address + 33;
    final value = NativeLibrary.instance.getValue(addr, 'i8').toDartInt;
    return value;
  }

  set isLimitEnabled(int val) {
    NativeLibrary.instance.setValue(this.address + 33, val.toJS, 'i8');
  }

  int get isMotorEnabled {
    final addr = this.address + 34;
    final value = NativeLibrary.instance.getValue(addr, 'i8').toDartInt;
    return value;
  }

  set isMotorEnabled(int val) {
    NativeLibrary.instance.setValue(this.address + 34, val.toJS, 'i8');
  }

  double get minTranslationLimit {
    final addr = this.address + 35;
    final value = NativeLibrary.instance.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set minTranslationLimit(double val) {
    NativeLibrary.instance.setValue(this.address + 35, val.toJS, 'float');
  }

  double get maxTranslationLimit {
    final addr = this.address + 39;
    final value = NativeLibrary.instance.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set maxTranslationLimit(double val) {
    NativeLibrary.instance.setValue(this.address + 39, val.toJS, 'float');
  }

  double get motorSpeed {
    final addr = this.address + 43;
    final value = NativeLibrary.instance.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set motorSpeed(double val) {
    NativeLibrary.instance.setValue(this.address + 43, val.toJS, 'float');
  }

  double get maxMotorForce {
    final addr = this.address + 47;
    final value = NativeLibrary.instance.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set maxMotorForce(double val) {
    NativeLibrary.instance.setValue(this.address + 47, val.toJS, 'float');
  }

  RP3D_SliderJointInfo(super.address);

  static Pointer<RP3D_SliderJointInfo> stackAlloc() {
    return Pointer<RP3D_SliderJointInfo>(
      NativeLibrary.instance.stackAlloc<RP3D_SliderJointInfo>(51),
    );
  }
}

extension RP3D_FixedJointExt on Pointer<RP3D_FixedJoint> {
  RP3D_FixedJoint toDart() {
    return RP3D_FixedJoint(this);
  }
}

final class RP3D_FixedJoint extends Struct {
  Pointer<RP3D_FixedJoint> get address => super.address.cast();
  RP3D_FixedJoint(super.address);

  static Pointer<RP3D_FixedJoint> stackAlloc() {
    return Pointer<RP3D_FixedJoint>(
      NativeLibrary.instance.stackAlloc<RP3D_FixedJoint>(0),
    );
  }
}

extension RP3D_FixedJointInfoExt on Pointer<RP3D_FixedJointInfo> {
  RP3D_FixedJointInfo toDart() {
    return RP3D_FixedJointInfo(this);
  }
}

final class RP3D_FixedJointInfo extends Struct {
  Pointer<RP3D_FixedJointInfo> get address => super.address.cast();
  RP3D_Vector3 get anchorPointWorldSpace {
    final addr = this.address + 0;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return RP3D_Vector3(Pointer<RP3D_Vector3>(addr));
  }

  set anchorPointWorldSpace(RP3D_Vector3 val) {
    NativeLibrary.instance.setValue(this.address + 0, val.address.toJS, '*');
  }

  Pointer<RP3D_RigidBody> get body1 {
    final addr = this.address + 12;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Pointer<RP3D_RigidBody>(value.toDartInt);
  }

  set body1(Pointer<RP3D_RigidBody> val) {
    NativeLibrary.instance.setValue(this.address + 12, val.toJS, '*');
  }

  Pointer<RP3D_RigidBody> get body2 {
    final addr = this.address + 16;
    final value = NativeLibrary.instance.getValue(addr, '*');
    return Pointer<RP3D_RigidBody>(value.toDartInt);
  }

  set body2(Pointer<RP3D_RigidBody> val) {
    NativeLibrary.instance.setValue(this.address + 16, val.toJS, '*');
  }

  int get isCollisionEnabled {
    final addr = this.address + 20;
    final value = NativeLibrary.instance.getValue(addr, 'i8').toDartInt;
    return value;
  }

  set isCollisionEnabled(int val) {
    NativeLibrary.instance.setValue(this.address + 20, val.toJS, 'i8');
  }

  RP3D_FixedJointInfo(super.address);

  static Pointer<RP3D_FixedJointInfo> stackAlloc() {
    return Pointer<RP3D_FixedJointInfo>(
      NativeLibrary.instance.stackAlloc<RP3D_FixedJointInfo>(21),
    );
  }
}

extension StructAllocator on Struct {
  static T create<T>() {
    switch (T) {
      case RP3D_PhysicsCommon:
        final ptr = RP3D_PhysicsCommon.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_PhysicsWorld:
        final ptr = RP3D_PhysicsWorld.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_BoxShape:
        final ptr = RP3D_BoxShape.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_Vector3:
        final ptr = RP3D_Vector3.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_SphereShape:
        final ptr = RP3D_SphereShape.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_CapsuleShape:
        final ptr = RP3D_CapsuleShape.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_HeightField:
        final ptr = RP3D_HeightField.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_HeightFieldShape:
        final ptr = RP3D_HeightFieldShape.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_TriangleVertexArray:
        final ptr = RP3D_TriangleVertexArray.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_PolygonVertexArray:
        final ptr = RP3D_PolygonVertexArray.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_TriangleMesh:
        final ptr = RP3D_TriangleMesh.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_ConvexMesh:
        final ptr = RP3D_ConvexMesh.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_ConvexMeshShape:
        final ptr = RP3D_ConvexMeshShape.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_ConcaveMeshShape:
        final ptr = RP3D_ConcaveMeshShape.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_DebugRenderer:
        final ptr = RP3D_DebugRenderer.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_RigidBody:
        final ptr = RP3D_RigidBody.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_Transform:
        final ptr = RP3D_Transform.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_Quaternion:
        final ptr = RP3D_Quaternion.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_Ray:
        final ptr = RP3D_Ray.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_RaycastInfo:
        final ptr = RP3D_RaycastInfo.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_Collider:
        final ptr = RP3D_Collider.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_CollisionShape:
        final ptr = RP3D_CollisionShape.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_Material:
        final ptr = RP3D_Material.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_AABB:
        final ptr = RP3D_AABB.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_BallAndSocketJoint:
        final ptr = RP3D_BallAndSocketJoint.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_BallAndSocketJointInfo:
        final ptr = RP3D_BallAndSocketJointInfo.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_HingeJoint:
        final ptr = RP3D_HingeJoint.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_HingeJointInfo:
        final ptr = RP3D_HingeJointInfo.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_SliderJoint:
        final ptr = RP3D_SliderJoint.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_SliderJointInfo:
        final ptr = RP3D_SliderJointInfo.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_FixedJoint:
        final ptr = RP3D_FixedJoint.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_FixedJointInfo:
        final ptr = RP3D_FixedJointInfo.stackAlloc();
        return ptr.toDart() as T;
    }
    throw Exception("Unsupported type $T");
  }
}
