// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:jsgen`.
// ignore_for_file: type=lint
import '' as self;
import 'dart:typed_data';
import 'dart:js_interop';
import 'dart:js_interop_unsafe';

///
/// Sub-classes of [NativeType] represent a "native" type (by which we mean a
/// type that can be passed to a WASM-compiled native function), and its
/// equivalent Dart representation.
///
/// Most sub-classes are non-constructible; they are only intended to preserve
/// compile-time type information and to translate between native types and
/// their Dart equivalent.
///
/// The exceptions are [Pointer], [Array] and sub-classes of [Struct]; these can be
/// instantiated and returned to the user.
///
/// Sub-classes doesn't necessarily represent a singular WASM type; for example,
/// WASM does not have a char type but we implement a [Char] type to help
/// preserve "native" type information. Without this, [const char*] would only be
/// represented as Pointer<Int64>, and we would have no way of knowing that
/// it can safely be interpreted/converted to a Dart String.
///
///
abstract final class NativeType {}

extension type const Pointer<T extends NativeType>(int addr) implements int {
  Pointer<T> operator +(int byteOffset) => Pointer<T>(this.addr + byteOffset);
  Pointer<U> cast<U extends NativeType>() => this as Pointer<U>;
  void free() {
    _lib._free(this);
  }

  int get address => addr;
}

base class PointerClass<T extends NativeType> extends NativeType {
  final Pointer<T> addr;

  PointerClass(this.addr);

  String get llvmType => '*';
  int size() => 4;

  static PointerClass<PointerClass<T>> stackAlloc<T extends NativeType>(
    int count,
  ) {
    return _lib._stackAlloc<T>(4 * count) as PointerClass<PointerClass<T>>;
  }

  PointerClass<T> operator +(int numElements) =>
      PointerClass<T>(this.addr.addr + (numElements * size()) as Pointer<T>);
  PointerClass<U> cast<U extends NativeType>() => this as PointerClass<U>;
}

extension type Null._(NativeType value) implements NativeType {}

Pointer<NativeFunction<T>> addFunction<T>(JSFunction fn, String signature) {
  return _lib.addFunction(fn, signature);
}

extension type Char._(NativeType value) implements NativeType {
  static Pointer<Char> stackAlloc(int count) {
    return Pointer<Char>(_lib._stackAlloc<Char>(4 * count));
  }
}

extension type Bool._(NativeType value) implements NativeType {
  static Pointer<Bool> stackAlloc(int count) {
    return Pointer<Bool>(_lib._stackAlloc<Char>(4 * count));
  }
}

extension type const Uint32._(NativeType nt) implements NativeType {
  static Pointer<Uint32> stackAlloc(int count) {
    return _lib._stackAlloc<Uint32>(4 * count);
  }
}

extension type const Uint8._(NativeType nt) implements NativeType {
  static Pointer<Uint8> stackAlloc(int count) {
    return _lib._stackAlloc<Uint8>(count);
  }
}

extension type const Int8._(NativeType nt) implements NativeType {
  static Pointer<Int8> stackAlloc(int count) {
    return _lib._stackAlloc<Int8>(count);
  }
}

extension type const Uint16._(NativeType nt) implements NativeType {
  static Pointer<Uint16> stackAlloc(int count) {
    return _lib._stackAlloc<Uint16>(2 * count);
  }
}

extension type const Int16._(NativeType nt) implements NativeType {
  static Pointer<Int16> stackAlloc(int count) {
    return _lib._stackAlloc<Int16>(2 * count);
  }
}

extension type const Int32._(NativeType nt) implements NativeType {
  static Pointer<Int32> stackAlloc(int count) {
    return _lib._stackAlloc<Int32>(4 * count);
  }
}

extension type Int64(NativeType nt) implements NativeType {
  static Pointer<Int64> stackAlloc(int count) {
    return _lib._stackAlloc<Int64>(8 * count);
  }
}
extension type Float32._(NativeType nt) implements NativeType {
  static Pointer<Float32> stackAlloc(int count) {
    return _lib._stackAlloc<Float32>(4 * count);
  }
}
extension type Float64._(NativeType nt) implements NativeType {
  static Pointer<Float64> stackAlloc(int count) {
    return _lib._stackAlloc<Float64>(8 * count);
  }
}
extension type NativeFunction<T>._(NativeType nt) implements NativeType {}
extension type Void._(NativeType nt) implements NativeType {}

Pointer<Never> nullptr = Pointer<Never>(0);

extension PointerPointerClass<T extends NativeType>
    on Pointer<PointerClass<T>> {
  operator [](int i) => this + i;
  void operator []=(int i, Pointer<T> value) {
    _lib.setValue(this + (i * 4), value.addr.toJS, 'i64');
  }
}

extension fncp<T extends NativeType> on void Function(Pointer<T>) {
  Pointer<NativeFunction<void Function(Pointer<T>)>> addFunction() {
    var fnPtr = _lib.addFunction<void Function(Pointer<T>)>(this.toJS, "vp");
    return fnPtr;
  }
}

extension VoidPointerClass on Pointer<Void> {
  String get llvmType => 'v';

  static Pointer<Void> fromAddress(int addr) => Pointer<Void>(addr);
}

extension Int32PointerClass on Pointer<Int32> {
  String get llvmType => 'i32';

  void setValue(int value) {
    _lib.setValue(this, value.toJS, llvmType);
  }

  int getValue() {
    return _lib.getValue(this, llvmType).toDartInt;
  }

  static Pointer<Int32> fromAddress(int addr) => Pointer<Int32>(addr);
}

extension Int64Pointer on Pointer<Int64> {
  String get llvmType => 'i64';

  void setValue(int value) {
    _lib.setValue(this, value.toJS, llvmType);
  }

  int getValue() {
    return _lib.getValue(this, llvmType).toDartInt;
  }

  static Pointer<Int64> fromAddress(int addr) => Pointer<Int64>(addr);
}

extension Float32Pointer on Pointer<Float32> {
  String get llvmType => 'float';

  void setValue(double value) {
    _lib.setValue(this, value.toJS, llvmType);
  }

  double get value {
    return getValue();
  }

  double getValue() {
    return _lib.getValue(this, llvmType).toDartDouble;
  }

  double operator [](int i) {
    return _lib.getValue(this + (i * 4), 'f').toDartDouble;
  }

  operator []=(int i, double val) {
    _lib.setValue(this + (i * 4), val.toJS, 'f');
  }

  static Pointer<Float32> fromAddress(int addr) => Pointer<Float32>(addr);
}

extension Float64Pointer on Pointer<Float64> {
  String get llvmType => 'double';

  void setValue(double value) {
    _lib.setValue(this, value.toJS, llvmType);
  }

  double getValue() {
    return _lib.getValue(this, llvmType).toDartDouble;
  }

  static Pointer<Float64> fromAddress(int addr) => Pointer<Float64>(addr);
}

extension StringUtils on String {
  Pointer<Char> toNativeUtf8() {
    var len = _lib._lengthBytesUTF8(this) + 1;
    var ptr = Char.stackAlloc(len);
    _lib._stringToUTF8(this, ptr, len);
    return ptr;
  }
}

extension CharPtr on Pointer<Char> {
  void setValue(String value) {
    var len = _lib._lengthBytesUTF8(value);
    _lib._stringToUTF8(value, this, len);
  }

  String toDartString() {
    return _lib._UTF8ToString(this);
  }

  static Pointer<Char> fromAddress(int addr) => Pointer<Char>(addr);
}

extension DisposePointerClass<T extends NativeType> on Pointer<NativeFunction> {
  void dispose() {
    _lib.removeFunction(this);
  }
}

extension type const Array<T extends NativeType>._(
  ({int numElements, Pointer<T> addr}) _
) {
  Array<U> cast<U extends NativeType>() => this as Array<U>;

  Uint8List asUint8List() {
    final start = _.addr;
    final end = _.addr.addr + _.numElements;

    return Uint8List.sublistView(_lib.HEAPU8.toDart, start.addr, end);
  }

  void setValue(Uint8List data) {
    _lib.writeArrayToMemory(data.toJS, _.addr);
  }
}

extension ArrayInt32Ext on Array<Int32> {
  int operator [](int i) {
    return _lib.getValue(_.addr + (i * 4), 'i32').toDartInt;
  }

  void operator []=(int i, int v) {
    _lib.setValue(_.addr + (i * 4), v.toJS, 'i32');
  }
}

extension ArrayFloat32Ext on Array<Float32> {
  double operator [](int i) {
    return _lib.getValue(_.addr + (i * 4), 'double').toDartDouble;
  }

  void operator []=(int i, double v) {
    _lib.setValue(_.addr + (i * 4), v.toJS, 'double');
  }
}

extension ArrayFloat64Ext on Array<Float64> {
  double operator [](int i) {
    return _lib.getValue(_.addr + (i * 8), 'double').toDartDouble;
  }

  void operator []=(int i, double v) {
    _lib.setValue(_.addr + (i * 8), v.toJS, 'double');
  }
}

late NativeLibrary _lib;

Pointer<T> malloc<T extends NativeType>(int numBytes) {
  return _lib._malloc<T>(numBytes);
}

Pointer<T> stackAlloc<T extends NativeType>(int numBytes) {
  final ptr = _lib._stackAlloc<T>(numBytes);
  return ptr;
}

void free(Pointer ptr) {
  _lib._free(ptr);
}

@JS('BigInt')
external JSBigInt bigInt(String s);

@JS('BigInt.asUintN')
external JSBigInt bigIntasUintN(int numBits, JSBigInt bi);

extension JSBigIntExtension on JSBigInt {
  BigInt get toDart {
    return BigInt.parse(this.toString());
  }
}

extension BigIntExtension on int {
  JSBigInt get toJSBigInt {
    return bigInt(this.toString());
  }
}

extension DartBigIntExtension on BigInt {
  JSBigInt get toJSBigInt {
    return bigInt(this.toString());
  }
}

final _allocations = <TypedData>{};

Uint8List makeUint8List(int length) {
  var ptr = malloc<Uint8>(length);
  var buf = NativeLibrary.instance._emscripten_make_uint8_buffer(ptr, length);
  var uint8List = buf.toDart;
  _allocations.add(uint8List);
  return uint8List;
}

Int32List makeInt32List(int length) {
  var ptr = stackAlloc<Int32>(length * 4);
  var buf = NativeLibrary.instance._emscripten_make_int32_buffer(ptr, length);
  var int32List = buf.toDart;
  _allocations.add(int32List);
  return int32List;
}

Float32List makeFloat32List(int length) {
  var ptr = stackAlloc<Float32>(length * 4);
  var buf = NativeLibrary.instance._emscripten_make_f32_buffer(ptr, length);
  var f32List = buf.toDart;
  _allocations.add(f32List);
  return f32List;
}

extension FreeTypedData<T> on TypedData {
  void free() {
    Pointer<Void>(this.offsetInBytes).free();
    _allocations.remove(this);
  }
}

extension type NativeLibrary(JSObject _) implements JSObject {
  static NativeLibrary get instance => _lib;

  static void initBindings(String moduleName) {
    var lib = globalContext.getProperty(moduleName.toJS);
    if (lib == null) {
      throw Exception("Failed to find JS module ${moduleName}");
    }
    _lib = lib as NativeLibrary;
  }

  @JS('stackAlloc')
  external Pointer<T> _stackAlloc<T extends NativeType>(int numBytes);

  external Pointer<T> _malloc<T extends NativeType>(int numBytes);

  external void _free(Pointer ptr);

  @JS('stackSave')
  external Pointer<Void> stackSave();

  @JS('stackRestore')
  external void stackRestore(Pointer<Void> ptr);

  @JS('getValue')
  external JSBigInt getValueBigInt(Pointer addr, String llvmType);
  external JSNumber getValue(Pointer addr, String llvmType);
  external void setValue(Pointer addr, JSNumber value, String llvmType);

  @JS("lengthBytesUTF8")
  external int _lengthBytesUTF8(String str);

  @JS("UTF8ToString")
  external String _UTF8ToString(Pointer<Char> ptr);

  @JS("stringToUTF8")
  external void _stringToUTF8(
    String str,
    Pointer<Char> ptr,
    int maxBytesToWrite,
  );

  external void writeArrayToMemory(JSUint8Array data, Pointer ptr);

  external Pointer<NativeFunction<T>> addFunction<T>(
    JSFunction f,
    String signature,
  );
  external void removeFunction<T>(Pointer<NativeFunction<T>> f);
  external JSUint8Array get HEAPU8;
  external JSFloat32Array get HEAPF32;

  external JSUint8Array _emscripten_make_uint8_buffer(
    Pointer<Uint8> ptr,
    int length,
  );
  external JSUint16Array _emscripten_make_uint16_buffer(
    Pointer<Uint16> ptr,
    int length,
  );
  external JSInt16Array _emscripten_make_int16_buffer(
    Pointer<Int16> ptr,
    int length,
  );
  external JSInt32Array _emscripten_make_int32_buffer(
    Pointer<Int32> ptr,
    int length,
  );
  external JSFloat32Array _emscripten_make_f32_buffer(
    Pointer<Float32> ptr,
    int length,
  );
  external JSFloat64Array _emscripten_make_f64_buffer(
    Pointer<Float64> ptr,
    int length,
  );
  external Pointer _emscripten_get_byte_offset(JSObject obj);

  external int _emscripten_stack_get_base();
  external Pointer _emscripten_stack_get_current();
  external int _emscripten_stack_get_free();

  external void _execute_queue();

  /// ==================== PhysicsCommon (Factory) ====================
  external Pointer<RP3D_PhysicsCommon> _rp3d_physics_common_create();
  external void _rp3d_physics_common_destroy(
    Pointer<RP3D_PhysicsCommon> common,
  );
  external Pointer<RP3D_PhysicsWorld> _rp3d_physics_common_create_physics_world(
    Pointer<RP3D_PhysicsCommon> common,
  );
  external void _rp3d_physics_common_destroy_physics_world(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_PhysicsWorld> world,
  );

  /// Shape creation through PhysicsCommon
  external Pointer<RP3D_BoxShape> _rp3d_physics_common_create_box_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_Vector3> halfExtents,
  );
  external Pointer<RP3D_SphereShape> _rp3d_physics_common_create_sphere_shape(
    Pointer<RP3D_PhysicsCommon> common,
    double radius,
  );
  external Pointer<RP3D_CapsuleShape> _rp3d_physics_common_create_capsule_shape(
    Pointer<RP3D_PhysicsCommon> common,
    double radius,
    double height,
  );

  /// HeightField creation/destruction
  external Pointer<RP3D_HeightField> _rp3d_physics_common_create_height_field(
    Pointer<RP3D_PhysicsCommon> common,
    int nbRows,
    int nbColumns,
    Pointer<Float32> heights,
    double minHeight,
    double maxHeight,
  );
  external void _rp3d_physics_common_destroy_height_field(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_HeightField> heightField,
  );

  /// HeightFieldShape creation/destruction
  external Pointer<RP3D_HeightFieldShape>
  _rp3d_physics_common_create_height_field_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_HeightField> heightField,
  );
  external void _rp3d_physics_common_destroy_height_field_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_HeightFieldShape> heightFieldShape,
  );

  /// TriangleVertexArray creation/destruction
  external Pointer<RP3D_TriangleVertexArray> _rp3d_triangle_vertex_array_create(
    int nbVertices,
    Pointer<Float32> verticesStart,
    int verticesStride,
    int nbIndices,
    Pointer<Uint32> indicesStart,
    int indicesStride,
  );
  external void _rp3d_triangle_vertex_array_destroy(
    Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
  );

  /// TriangleVertexArray accessors
  external int _rp3d_triangle_vertex_array_get_nb_vertices(
    Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
  );
  external int _rp3d_triangle_vertex_array_get_nb_triangles(
    Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
  );
  external Pointer<Float32> _rp3d_triangle_vertex_array_get_vertices_start(
    Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
  );
  external Pointer<Uint32> _rp3d_triangle_vertex_array_get_indices_start(
    Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
  );
  external void _rp3d_triangle_vertex_array_get_triangle_vertices_indices(
    Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
    int triangleIndex,
    Pointer<Uint32> out,
  );

  /// PolygonVertexArray creation/destruction
  external Pointer<RP3D_PolygonVertexArray> _rp3d_polygon_vertex_array_create(
    int nbVertices,
    Pointer<Float32> verticesStart,
    int verticesStride,
    int nbIndices,
    Pointer<Uint32> indicesStart,
    int indicesStride,
    Pointer<Uint32> polygonIndicesStart,
    int polygonIndicesStride,
  );
  external void _rp3d_polygon_vertex_array_destroy(
    Pointer<RP3D_PolygonVertexArray> polygonVertexArray,
  );

  /// TriangleMesh creation/destruction
  external Pointer<RP3D_TriangleMesh> _rp3d_physics_common_create_triangle_mesh(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
  );
  external void _rp3d_physics_common_destroy_triangle_mesh(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_TriangleMesh> triangleMesh,
  );

  /// TriangleMesh accessors
  external int _rp3d_triangle_mesh_get_nb_vertices(
    Pointer<RP3D_TriangleMesh> triangleMesh,
  );
  external int _rp3d_triangle_mesh_get_nb_triangles(
    Pointer<RP3D_TriangleMesh> triangleMesh,
  );
  external void _rp3d_triangle_mesh_get_vertex(
    Pointer<RP3D_TriangleMesh> triangleMesh,
    int vertexIndex,
    Pointer<RP3D_Vector3> outVertex,
  );
  external void _rp3d_triangle_mesh_get_triangle_vertices_indices(
    Pointer<RP3D_TriangleMesh> triangleMesh,
    int triangleIndex,
    Pointer<Uint32> indices,
  );

  /// ConvexMesh creation/destruction
  external Pointer<RP3D_ConvexMesh>
  _rp3d_physics_common_create_convex_mesh_from_triangles(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
  );
  external Pointer<RP3D_ConvexMesh>
  _rp3d_physics_common_create_convex_mesh_from_polygons(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_PolygonVertexArray> polygonVertexArray,
  );
  external void _rp3d_physics_common_destroy_convex_mesh(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_ConvexMesh> convexMesh,
  );

  /// ConvexMeshShape creation/destruction
  external Pointer<RP3D_ConvexMeshShape>
  _rp3d_physics_common_create_convex_mesh_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_ConvexMesh> convexMesh,
  );
  external void _rp3d_physics_common_destroy_convex_mesh_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_ConvexMeshShape> convexMeshShape,
  );

  /// ConcaveMeshShape creation/destruction
  external Pointer<RP3D_ConcaveMeshShape>
  _rp3d_physics_common_create_concave_mesh_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_TriangleMesh> triangleMesh,
    Pointer<RP3D_Vector3> scaling,
  );
  external void _rp3d_physics_common_destroy_concave_mesh_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_ConcaveMeshShape> concaveMeshShape,
  );

  /// Mesh/shape destruction
  external void _rp3d_physics_common_destroy_box_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_BoxShape> shape,
  );
  external void _rp3d_physics_common_destroy_sphere_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_SphereShape> shape,
  );
  external void _rp3d_physics_common_destroy_capsule_shape(
    Pointer<RP3D_PhysicsCommon> common,
    Pointer<RP3D_CapsuleShape> shape,
  );

  /// ==================== PhysicsWorld ====================
  external void _rp3d_world_update(
    Pointer<RP3D_PhysicsWorld> world,
    double timeStep,
  );
  external void _rp3d_world_set_gravity(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<RP3D_Vector3> gravity,
  );
  external void _rp3d_world_get_gravity(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<RP3D_Vector3> outGravity,
  );
  external int _rp3d_world_get_is_sleeping_enabled(
    Pointer<RP3D_PhysicsWorld> world,
  );
  external void _rp3d_world_set_is_sleeping_enabled(
    Pointer<RP3D_PhysicsWorld> world,
    int isSleepingEnabled,
  );

  /// Gravity and sleep control
  external void _rp3d_world_set_is_gravity_enabled(
    Pointer<RP3D_PhysicsWorld> world,
    int isGravityEnabled,
  );
  external void _rp3d_world_set_sleep_linear_velocity(
    Pointer<RP3D_PhysicsWorld> world,
    double sleepLinearVelocity,
  );
  external void _rp3d_world_set_sleep_angular_velocity(
    Pointer<RP3D_PhysicsWorld> world,
    double sleepAngularVelocity,
  );
  external void _rp3d_world_set_time_before_sleep(
    Pointer<RP3D_PhysicsWorld> world,
    double timeBeforeSleep,
  );

  /// Debug rendering
  external void _rp3d_world_set_is_debug_rendering_enabled(
    Pointer<RP3D_PhysicsWorld> world,
    int isEnabled,
  );
  external int _rp3d_world_get_is_debug_rendering_enabled(
    Pointer<RP3D_PhysicsWorld> world,
  );
  external Pointer<RP3D_DebugRenderer> _rp3d_world_get_debug_renderer(
    Pointer<RP3D_PhysicsWorld> world,
  );
  external int _rp3d_world_get_nb_rigid_bodies(
    Pointer<RP3D_PhysicsWorld> world,
  );
  external Pointer<RP3D_RigidBody> _rp3d_world_get_rigid_body(
    Pointer<RP3D_PhysicsWorld> world,
    int index,
  );

  /// Body creation/destruction
  external Pointer<RP3D_RigidBody> _rp3d_world_create_rigid_body(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<RP3D_Transform> transform,
  );
  external void _rp3d_world_destroy_rigid_body(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<RP3D_RigidBody> body,
  );

  /// Raycasting
  external int _rp3d_world_raycast(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<RP3D_Ray> ray,
    Pointer<RP3D_RaycastInfo> raycastInfo,
  );

  /// ==================== RigidBody ====================
  external void _rp3d_body_get_transform(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Transform> outTransform,
  );
  external void _rp3d_body_set_transform(
    Pointer<RP3D_RigidBody> body,
    double posX,
    double posY,
    double posZ,
    double quatX,
    double quatY,
    double quatZ,
    double quatW,
  );
  external void _rp3d_body_get_position(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Vector3> outPosition,
  );
  external void _rp3d_body_get_orientation(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Quaternion> outOrientation,
  );
  external void _rp3d_body_set_type(Pointer<RP3D_RigidBody> body, int type);
  external int _rp3d_body_get_type(Pointer<RP3D_RigidBody> body);
  external void _rp3d_body_set_mass(Pointer<RP3D_RigidBody> body, double mass);
  external double _rp3d_body_get_mass(Pointer<RP3D_RigidBody> body);
  external void _rp3d_body_set_linear_velocity(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Vector3> linearVelocity,
  );
  external void _rp3d_body_get_linear_velocity(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Vector3> outLinearVelocity,
  );
  external void _rp3d_body_set_angular_velocity(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Vector3> angularVelocity,
  );
  external void _rp3d_body_get_angular_velocity(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Vector3> outAngularVelocity,
  );
  external void _rp3d_body_apply_force(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Vector3> force,
  );
  external void _rp3d_body_apply_force_at_position(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Vector3> force,
    Pointer<RP3D_Vector3> position,
  );
  external void _rp3d_body_apply_torque(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Vector3> torque,
  );
  external void _rp3d_body_set_is_active(
    Pointer<RP3D_RigidBody> body,
    int isActive,
  );
  external int _rp3d_body_get_is_active(Pointer<RP3D_RigidBody> body);
  external void _rp3d_body_set_is_sleeping_allowed(
    Pointer<RP3D_RigidBody> body,
    int isAllowed,
  );
  external int _rp3d_body_get_is_sleeping_allowed(Pointer<RP3D_RigidBody> body);

  /// Gravity control
  external void _rp3d_body_enable_gravity(
    Pointer<RP3D_RigidBody> body,
    int enableGravity,
  );
  external int _rp3d_body_is_gravity_enabled(Pointer<RP3D_RigidBody> body);

  /// Debug rendering
  external void _rp3d_body_set_is_debug_enabled(
    Pointer<RP3D_RigidBody> body,
    int isEnabled,
  );
  external int _rp3d_body_get_is_debug_enabled(Pointer<RP3D_RigidBody> body);

  /// Mass properties
  external void _rp3d_body_update_mass_properties_from_colliders(
    Pointer<RP3D_RigidBody> body,
  );

  /// Collider management
  external Pointer<RP3D_Collider> _rp3d_body_add_collider(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_CollisionShape> shape,
    Pointer<RP3D_Transform> transform,
  );
  external void _rp3d_body_remove_collider(
    Pointer<RP3D_RigidBody> body,
    Pointer<RP3D_Collider> collider,
  );
  external void _rp3d_collider_set_material(
    Pointer<RP3D_Collider> collider,
    Pointer<RP3D_Material> material,
  );

  /// ==================== Collider ====================
  external Pointer<RP3D_Material> _rp3d_collider_get_material(
    Pointer<RP3D_Collider> collider,
  );
  external void _rp3d_collider_get_local_bounds(
    Pointer<RP3D_Collider> collider,
    Pointer<RP3D_AABB> outAABB,
  );
  external void _rp3d_collider_set_is_trigger(
    Pointer<RP3D_Collider> collider,
    int isTrigger,
  );
  external int _rp3d_collider_get_is_trigger(Pointer<RP3D_Collider> collider);

  /// ==================== Material ====================
  external void _rp3d_material_destroy(Pointer<RP3D_Material> material);
  external void _rp3d_material_set_bounciness(
    Pointer<RP3D_Material> material,
    double bounciness,
  );
  external double _rp3d_material_get_bounciness(
    Pointer<RP3D_Material> material,
  );
  external void _rp3d_material_set_friction_coefficient(
    Pointer<RP3D_Material> material,
    double frictionCoefficient,
  );
  external double _rp3d_material_get_friction_coefficient(
    Pointer<RP3D_Material> material,
  );
  external void _rp3d_material_set_mass_density(
    Pointer<RP3D_Material> material,
    double massDensity,
  );
  external double _rp3d_material_get_mass_density(
    Pointer<RP3D_Material> material,
  );

  /// ==================== CollisionShape (base) ====================
  external void _rp3d_shape_get_local_bounds(
    Pointer<RP3D_CollisionShape> shape,
    Pointer<RP3D_AABB> outAABB,
  );
  external void _rp3d_concave_shape_set_scale(
    Pointer<RP3D_HeightFieldShape> shape,
    Pointer<RP3D_Vector3> scale,
  );

  /// ==================== HeightFieldShape ====================
  external void _rp3d_height_field_shape_get_vertex_at(
    Pointer<RP3D_HeightFieldShape> heightFieldShape,
    int row,
    int column,
    Pointer<RP3D_Vector3> outVertex,
  );

  /// Vector3
  external void _rp3d_vector3_zero(Pointer<RP3D_Vector3> v);
  external double _rp3d_vector3_length(Pointer<RP3D_Vector3> v);
  external void _rp3d_vector3_normalize(Pointer<RP3D_Vector3> v);
  external double _rp3d_vector3_dot(
    Pointer<RP3D_Vector3> v1,
    Pointer<RP3D_Vector3> v2,
  );
  external void _rp3d_vector3_cross(
    Pointer<RP3D_Vector3> v1,
    Pointer<RP3D_Vector3> v2,
    Pointer<RP3D_Vector3> outResult,
  );

  /// Quaternion
  external void _rp3d_quaternion_identity(Pointer<RP3D_Quaternion> q);
  external void _rp3d_quaternion_from_axis_angle(
    Pointer<RP3D_Vector3> axis,
    double angle,
    Pointer<RP3D_Quaternion> outQuat,
  );
  external void _rp3d_quaternion_normalize(Pointer<RP3D_Quaternion> q);

  /// Transform
  external void _rp3d_transform_identity(Pointer<RP3D_Transform> t);
  external void _rp3d_transform_inverse(
    Pointer<RP3D_Transform> t,
    Pointer<RP3D_Transform> outInverse,
  );
  external void _rp3d_transform_get_opengl_matrix(
    Pointer<RP3D_Transform> t,
    Pointer<Float32> outMatrix,
  );

  /// ==================== DebugRenderer ====================
  external void _rp3d_debug_renderer_set_is_debug_item_displayed(
    Pointer<RP3D_DebugRenderer> renderer,
    int item,
    int isDisplayed,
  );
  external int _rp3d_debug_renderer_get_is_debug_item_displayed(
    Pointer<RP3D_DebugRenderer> renderer,
    int item,
  );
  external int _rp3d_debug_renderer_get_nb_lines(
    Pointer<RP3D_DebugRenderer> renderer,
  );
  external int _rp3d_debug_renderer_get_nb_triangles(
    Pointer<RP3D_DebugRenderer> renderer,
  );
  external void _rp3d_debug_renderer_get_lines_array(
    Pointer<RP3D_DebugRenderer> renderer,
    Pointer<Float32> outVertices,
    Pointer<Uint32> outColors,
  );
  external void _rp3d_debug_renderer_get_triangles_array(
    Pointer<RP3D_DebugRenderer> renderer,
    Pointer<Float32> outVertices,
    Pointer<Uint32> outColors,
  );

  /// ==================== Joints ====================
  external Pointer<RP3D_BallAndSocketJoint>
  _rp3d_world_create_ball_and_socket_joint(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<RP3D_BallAndSocketJointInfo> jointInfo,
  );
  external Pointer<RP3D_HingeJoint> _rp3d_world_create_hinge_joint(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<RP3D_HingeJointInfo> jointInfo,
  );
  external Pointer<RP3D_SliderJoint> _rp3d_world_create_slider_joint(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<RP3D_SliderJointInfo> jointInfo,
  );
  external Pointer<RP3D_FixedJoint> _rp3d_world_create_fixed_joint(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<RP3D_FixedJointInfo> jointInfo,
  );
  external void _rp3d_world_destroy_joint(
    Pointer<RP3D_PhysicsWorld> world,
    Pointer<Void> joint,
  );
}

/// ==================== PhysicsCommon (Factory) ====================
self.Pointer<RP3D_PhysicsCommon> rp3d_physics_common_create() {
  final result = _lib._rp3d_physics_common_create();
  return self.Pointer<RP3D_PhysicsCommon>(result);
}

void rp3d_physics_common_destroy(self.Pointer<RP3D_PhysicsCommon> common) {
  final result = _lib._rp3d_physics_common_destroy(common.cast());
  return result;
}

self.Pointer<RP3D_PhysicsWorld> rp3d_physics_common_create_physics_world(
  self.Pointer<RP3D_PhysicsCommon> common,
) {
  final result = _lib._rp3d_physics_common_create_physics_world(common.cast());
  return self.Pointer<RP3D_PhysicsWorld>(result);
}

void rp3d_physics_common_destroy_physics_world(
  self.Pointer<RP3D_PhysicsCommon> common,
  self.Pointer<RP3D_PhysicsWorld> world,
) {
  final result = _lib._rp3d_physics_common_destroy_physics_world(
    common.cast(),
    world.cast(),
  );
  return result;
}

/// Shape creation through PhysicsCommon
self.Pointer<RP3D_BoxShape> rp3d_physics_common_create_box_shape(
  self.Pointer<RP3D_PhysicsCommon> common,
  self.Pointer<RP3D_Vector3> halfExtents,
) {
  final result = _lib._rp3d_physics_common_create_box_shape(
    common.cast(),
    halfExtents.cast(),
  );
  return self.Pointer<RP3D_BoxShape>(result);
}

self.Pointer<RP3D_SphereShape> rp3d_physics_common_create_sphere_shape(
  self.Pointer<RP3D_PhysicsCommon> common,
  double radius,
) {
  final result = _lib._rp3d_physics_common_create_sphere_shape(
    common.cast(),
    radius,
  );
  return self.Pointer<RP3D_SphereShape>(result);
}

self.Pointer<RP3D_CapsuleShape> rp3d_physics_common_create_capsule_shape(
  self.Pointer<RP3D_PhysicsCommon> common,
  double radius,
  double height,
) {
  final result = _lib._rp3d_physics_common_create_capsule_shape(
    common.cast(),
    radius,
    height,
  );
  return self.Pointer<RP3D_CapsuleShape>(result);
}

/// HeightField creation/destruction
self.Pointer<RP3D_HeightField> rp3d_physics_common_create_height_field(
  self.Pointer<RP3D_PhysicsCommon> common,
  int nbRows,
  int nbColumns,
  self.Pointer<Float32> heights,
  double minHeight,
  double maxHeight,
) {
  final result = _lib._rp3d_physics_common_create_height_field(
    common.cast(),
    nbRows,
    nbColumns,
    heights,
    minHeight,
    maxHeight,
  );
  return self.Pointer<RP3D_HeightField>(result);
}

void rp3d_physics_common_destroy_height_field(
  self.Pointer<RP3D_PhysicsCommon> common,
  self.Pointer<RP3D_HeightField> heightField,
) {
  final result = _lib._rp3d_physics_common_destroy_height_field(
    common.cast(),
    heightField.cast(),
  );
  return result;
}

/// HeightFieldShape creation/destruction
self.Pointer<RP3D_HeightFieldShape>
rp3d_physics_common_create_height_field_shape(
  self.Pointer<RP3D_PhysicsCommon> common,
  self.Pointer<RP3D_HeightField> heightField,
) {
  final result = _lib._rp3d_physics_common_create_height_field_shape(
    common.cast(),
    heightField.cast(),
  );
  return self.Pointer<RP3D_HeightFieldShape>(result);
}

void rp3d_physics_common_destroy_height_field_shape(
  self.Pointer<RP3D_PhysicsCommon> common,
  self.Pointer<RP3D_HeightFieldShape> heightFieldShape,
) {
  final result = _lib._rp3d_physics_common_destroy_height_field_shape(
    common.cast(),
    heightFieldShape.cast(),
  );
  return result;
}

/// TriangleVertexArray creation/destruction
self.Pointer<RP3D_TriangleVertexArray> rp3d_triangle_vertex_array_create(
  int nbVertices,
  self.Pointer<Float32> verticesStart,
  int verticesStride,
  int nbIndices,
  self.Pointer<Uint32> indicesStart,
  int indicesStride,
) {
  final result = _lib._rp3d_triangle_vertex_array_create(
    nbVertices,
    verticesStart,
    verticesStride,
    nbIndices,
    indicesStart,
    indicesStride,
  );
  return self.Pointer<RP3D_TriangleVertexArray>(result);
}

void rp3d_triangle_vertex_array_destroy(
  self.Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
) {
  final result = _lib._rp3d_triangle_vertex_array_destroy(
    triangleVertexArray.cast(),
  );
  return result;
}

/// TriangleVertexArray accessors
int rp3d_triangle_vertex_array_get_nb_vertices(
  self.Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
) {
  final result = _lib._rp3d_triangle_vertex_array_get_nb_vertices(
    triangleVertexArray.cast(),
  );
  return result;
}

int rp3d_triangle_vertex_array_get_nb_triangles(
  self.Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
) {
  final result = _lib._rp3d_triangle_vertex_array_get_nb_triangles(
    triangleVertexArray.cast(),
  );
  return result;
}

self.Pointer<Float32> rp3d_triangle_vertex_array_get_vertices_start(
  self.Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
) {
  final result = _lib._rp3d_triangle_vertex_array_get_vertices_start(
    triangleVertexArray.cast(),
  );
  return self.Pointer<Float32>(result);
}

self.Pointer<Uint32> rp3d_triangle_vertex_array_get_indices_start(
  self.Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
) {
  final result = _lib._rp3d_triangle_vertex_array_get_indices_start(
    triangleVertexArray.cast(),
  );
  return self.Pointer<Uint32>(result);
}

void rp3d_triangle_vertex_array_get_triangle_vertices_indices(
  self.Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
  int triangleIndex,
  self.Pointer<Uint32> out,
) {
  final result = _lib._rp3d_triangle_vertex_array_get_triangle_vertices_indices(
    triangleVertexArray.cast(),
    triangleIndex,
    out,
  );
  return result;
}

/// PolygonVertexArray creation/destruction
self.Pointer<RP3D_PolygonVertexArray> rp3d_polygon_vertex_array_create(
  int nbVertices,
  self.Pointer<Float32> verticesStart,
  int verticesStride,
  int nbIndices,
  self.Pointer<Uint32> indicesStart,
  int indicesStride,
  self.Pointer<Uint32> polygonIndicesStart,
  int polygonIndicesStride,
) {
  final result = _lib._rp3d_polygon_vertex_array_create(
    nbVertices,
    verticesStart,
    verticesStride,
    nbIndices,
    indicesStart,
    indicesStride,
    polygonIndicesStart,
    polygonIndicesStride,
  );
  return self.Pointer<RP3D_PolygonVertexArray>(result);
}

void rp3d_polygon_vertex_array_destroy(
  self.Pointer<RP3D_PolygonVertexArray> polygonVertexArray,
) {
  final result = _lib._rp3d_polygon_vertex_array_destroy(
    polygonVertexArray.cast(),
  );
  return result;
}

/// TriangleMesh creation/destruction
self.Pointer<RP3D_TriangleMesh> rp3d_physics_common_create_triangle_mesh(
  self.Pointer<RP3D_PhysicsCommon> common,
  self.Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
) {
  final result = _lib._rp3d_physics_common_create_triangle_mesh(
    common.cast(),
    triangleVertexArray.cast(),
  );
  return self.Pointer<RP3D_TriangleMesh>(result);
}

void rp3d_physics_common_destroy_triangle_mesh(
  self.Pointer<RP3D_PhysicsCommon> common,
  self.Pointer<RP3D_TriangleMesh> triangleMesh,
) {
  final result = _lib._rp3d_physics_common_destroy_triangle_mesh(
    common.cast(),
    triangleMesh.cast(),
  );
  return result;
}

/// TriangleMesh accessors
int rp3d_triangle_mesh_get_nb_vertices(
  self.Pointer<RP3D_TriangleMesh> triangleMesh,
) {
  final result = _lib._rp3d_triangle_mesh_get_nb_vertices(triangleMesh.cast());
  return result;
}

int rp3d_triangle_mesh_get_nb_triangles(
  self.Pointer<RP3D_TriangleMesh> triangleMesh,
) {
  final result = _lib._rp3d_triangle_mesh_get_nb_triangles(triangleMesh.cast());
  return result;
}

void rp3d_triangle_mesh_get_vertex(
  self.Pointer<RP3D_TriangleMesh> triangleMesh,
  int vertexIndex,
  self.Pointer<RP3D_Vector3> outVertex,
) {
  final result = _lib._rp3d_triangle_mesh_get_vertex(
    triangleMesh.cast(),
    vertexIndex,
    outVertex.cast(),
  );
  return result;
}

void rp3d_triangle_mesh_get_triangle_vertices_indices(
  self.Pointer<RP3D_TriangleMesh> triangleMesh,
  int triangleIndex,
  self.Pointer<Uint32> indices,
) {
  final result = _lib._rp3d_triangle_mesh_get_triangle_vertices_indices(
    triangleMesh.cast(),
    triangleIndex,
    indices,
  );
  return result;
}

/// ConvexMesh creation/destruction
self.Pointer<RP3D_ConvexMesh>
rp3d_physics_common_create_convex_mesh_from_triangles(
  self.Pointer<RP3D_PhysicsCommon> common,
  self.Pointer<RP3D_TriangleVertexArray> triangleVertexArray,
) {
  final result = _lib._rp3d_physics_common_create_convex_mesh_from_triangles(
    common.cast(),
    triangleVertexArray.cast(),
  );
  return self.Pointer<RP3D_ConvexMesh>(result);
}

self.Pointer<RP3D_ConvexMesh>
rp3d_physics_common_create_convex_mesh_from_polygons(
  self.Pointer<RP3D_PhysicsCommon> common,
  self.Pointer<RP3D_PolygonVertexArray> polygonVertexArray,
) {
  final result = _lib._rp3d_physics_common_create_convex_mesh_from_polygons(
    common.cast(),
    polygonVertexArray.cast(),
  );
  return self.Pointer<RP3D_ConvexMesh>(result);
}

void rp3d_physics_common_destroy_convex_mesh(
  self.Pointer<RP3D_PhysicsCommon> common,
  self.Pointer<RP3D_ConvexMesh> convexMesh,
) {
  final result = _lib._rp3d_physics_common_destroy_convex_mesh(
    common.cast(),
    convexMesh.cast(),
  );
  return result;
}

/// ConvexMeshShape creation/destruction
self.Pointer<RP3D_ConvexMeshShape> rp3d_physics_common_create_convex_mesh_shape(
  self.Pointer<RP3D_PhysicsCommon> common,
  self.Pointer<RP3D_ConvexMesh> convexMesh,
) {
  final result = _lib._rp3d_physics_common_create_convex_mesh_shape(
    common.cast(),
    convexMesh.cast(),
  );
  return self.Pointer<RP3D_ConvexMeshShape>(result);
}

void rp3d_physics_common_destroy_convex_mesh_shape(
  self.Pointer<RP3D_PhysicsCommon> common,
  self.Pointer<RP3D_ConvexMeshShape> convexMeshShape,
) {
  final result = _lib._rp3d_physics_common_destroy_convex_mesh_shape(
    common.cast(),
    convexMeshShape.cast(),
  );
  return result;
}

/// ConcaveMeshShape creation/destruction
self.Pointer<RP3D_ConcaveMeshShape>
rp3d_physics_common_create_concave_mesh_shape(
  self.Pointer<RP3D_PhysicsCommon> common,
  self.Pointer<RP3D_TriangleMesh> triangleMesh,
  self.Pointer<RP3D_Vector3> scaling,
) {
  final result = _lib._rp3d_physics_common_create_concave_mesh_shape(
    common.cast(),
    triangleMesh.cast(),
    scaling.cast(),
  );
  return self.Pointer<RP3D_ConcaveMeshShape>(result);
}

void rp3d_physics_common_destroy_concave_mesh_shape(
  self.Pointer<RP3D_PhysicsCommon> common,
  self.Pointer<RP3D_ConcaveMeshShape> concaveMeshShape,
) {
  final result = _lib._rp3d_physics_common_destroy_concave_mesh_shape(
    common.cast(),
    concaveMeshShape.cast(),
  );
  return result;
}

/// Mesh/shape destruction
void rp3d_physics_common_destroy_box_shape(
  self.Pointer<RP3D_PhysicsCommon> common,
  self.Pointer<RP3D_BoxShape> shape,
) {
  final result = _lib._rp3d_physics_common_destroy_box_shape(
    common.cast(),
    shape.cast(),
  );
  return result;
}

void rp3d_physics_common_destroy_sphere_shape(
  self.Pointer<RP3D_PhysicsCommon> common,
  self.Pointer<RP3D_SphereShape> shape,
) {
  final result = _lib._rp3d_physics_common_destroy_sphere_shape(
    common.cast(),
    shape.cast(),
  );
  return result;
}

void rp3d_physics_common_destroy_capsule_shape(
  self.Pointer<RP3D_PhysicsCommon> common,
  self.Pointer<RP3D_CapsuleShape> shape,
) {
  final result = _lib._rp3d_physics_common_destroy_capsule_shape(
    common.cast(),
    shape.cast(),
  );
  return result;
}

/// ==================== PhysicsWorld ====================
void rp3d_world_update(self.Pointer<RP3D_PhysicsWorld> world, double timeStep) {
  final result = _lib._rp3d_world_update(world.cast(), timeStep);
  return result;
}

void rp3d_world_set_gravity(
  self.Pointer<RP3D_PhysicsWorld> world,
  self.Pointer<RP3D_Vector3> gravity,
) {
  final result = _lib._rp3d_world_set_gravity(world.cast(), gravity.cast());
  return result;
}

void rp3d_world_get_gravity(
  self.Pointer<RP3D_PhysicsWorld> world,
  self.Pointer<RP3D_Vector3> outGravity,
) {
  final result = _lib._rp3d_world_get_gravity(world.cast(), outGravity.cast());
  return result;
}

int rp3d_world_get_is_sleeping_enabled(self.Pointer<RP3D_PhysicsWorld> world) {
  final result = _lib._rp3d_world_get_is_sleeping_enabled(world.cast());
  return result;
}

void rp3d_world_set_is_sleeping_enabled(
  self.Pointer<RP3D_PhysicsWorld> world,
  int isSleepingEnabled,
) {
  final result = _lib._rp3d_world_set_is_sleeping_enabled(
    world.cast(),
    isSleepingEnabled,
  );
  return result;
}

/// Gravity and sleep control
void rp3d_world_set_is_gravity_enabled(
  self.Pointer<RP3D_PhysicsWorld> world,
  int isGravityEnabled,
) {
  final result = _lib._rp3d_world_set_is_gravity_enabled(
    world.cast(),
    isGravityEnabled,
  );
  return result;
}

void rp3d_world_set_sleep_linear_velocity(
  self.Pointer<RP3D_PhysicsWorld> world,
  double sleepLinearVelocity,
) {
  final result = _lib._rp3d_world_set_sleep_linear_velocity(
    world.cast(),
    sleepLinearVelocity,
  );
  return result;
}

void rp3d_world_set_sleep_angular_velocity(
  self.Pointer<RP3D_PhysicsWorld> world,
  double sleepAngularVelocity,
) {
  final result = _lib._rp3d_world_set_sleep_angular_velocity(
    world.cast(),
    sleepAngularVelocity,
  );
  return result;
}

void rp3d_world_set_time_before_sleep(
  self.Pointer<RP3D_PhysicsWorld> world,
  double timeBeforeSleep,
) {
  final result = _lib._rp3d_world_set_time_before_sleep(
    world.cast(),
    timeBeforeSleep,
  );
  return result;
}

/// Debug rendering
void rp3d_world_set_is_debug_rendering_enabled(
  self.Pointer<RP3D_PhysicsWorld> world,
  int isEnabled,
) {
  final result = _lib._rp3d_world_set_is_debug_rendering_enabled(
    world.cast(),
    isEnabled,
  );
  return result;
}

int rp3d_world_get_is_debug_rendering_enabled(
  self.Pointer<RP3D_PhysicsWorld> world,
) {
  final result = _lib._rp3d_world_get_is_debug_rendering_enabled(world.cast());
  return result;
}

self.Pointer<RP3D_DebugRenderer> rp3d_world_get_debug_renderer(
  self.Pointer<RP3D_PhysicsWorld> world,
) {
  final result = _lib._rp3d_world_get_debug_renderer(world.cast());
  return self.Pointer<RP3D_DebugRenderer>(result);
}

int rp3d_world_get_nb_rigid_bodies(self.Pointer<RP3D_PhysicsWorld> world) {
  final result = _lib._rp3d_world_get_nb_rigid_bodies(world.cast());
  return result;
}

self.Pointer<RP3D_RigidBody> rp3d_world_get_rigid_body(
  self.Pointer<RP3D_PhysicsWorld> world,
  int index,
) {
  final result = _lib._rp3d_world_get_rigid_body(world.cast(), index);
  return self.Pointer<RP3D_RigidBody>(result);
}

/// Body creation/destruction
self.Pointer<RP3D_RigidBody> rp3d_world_create_rigid_body(
  self.Pointer<RP3D_PhysicsWorld> world,
  self.Pointer<RP3D_Transform> transform,
) {
  final result = _lib._rp3d_world_create_rigid_body(
    world.cast(),
    transform.cast(),
  );
  return self.Pointer<RP3D_RigidBody>(result);
}

void rp3d_world_destroy_rigid_body(
  self.Pointer<RP3D_PhysicsWorld> world,
  self.Pointer<RP3D_RigidBody> body,
) {
  final result = _lib._rp3d_world_destroy_rigid_body(world.cast(), body.cast());
  return result;
}

/// Raycasting
int rp3d_world_raycast(
  self.Pointer<RP3D_PhysicsWorld> world,
  self.Pointer<RP3D_Ray> ray,
  self.Pointer<RP3D_RaycastInfo> raycastInfo,
) {
  final result = _lib._rp3d_world_raycast(
    world.cast(),
    ray.cast(),
    raycastInfo.cast(),
  );
  return result;
}

/// ==================== RigidBody ====================
void rp3d_body_get_transform(
  self.Pointer<RP3D_RigidBody> body,
  self.Pointer<RP3D_Transform> outTransform,
) {
  final result = _lib._rp3d_body_get_transform(
    body.cast(),
    outTransform.cast(),
  );
  return result;
}

void rp3d_body_set_transform(
  self.Pointer<RP3D_RigidBody> body,
  double posX,
  double posY,
  double posZ,
  double quatX,
  double quatY,
  double quatZ,
  double quatW,
) {
  final result = _lib._rp3d_body_set_transform(
    body.cast(),
    posX,
    posY,
    posZ,
    quatX,
    quatY,
    quatZ,
    quatW,
  );
  return result;
}

void rp3d_body_get_position(
  self.Pointer<RP3D_RigidBody> body,
  self.Pointer<RP3D_Vector3> outPosition,
) {
  final result = _lib._rp3d_body_get_position(body.cast(), outPosition.cast());
  return result;
}

void rp3d_body_get_orientation(
  self.Pointer<RP3D_RigidBody> body,
  self.Pointer<RP3D_Quaternion> outOrientation,
) {
  final result = _lib._rp3d_body_get_orientation(
    body.cast(),
    outOrientation.cast(),
  );
  return result;
}

void rp3d_body_set_type(self.Pointer<RP3D_RigidBody> body, int type) {
  final result = _lib._rp3d_body_set_type(body.cast(), type);
  return result;
}

int rp3d_body_get_type(self.Pointer<RP3D_RigidBody> body) {
  final result = _lib._rp3d_body_get_type(body.cast());
  return result;
}

void rp3d_body_set_mass(self.Pointer<RP3D_RigidBody> body, double mass) {
  final result = _lib._rp3d_body_set_mass(body.cast(), mass);
  return result;
}

double rp3d_body_get_mass(self.Pointer<RP3D_RigidBody> body) {
  final result = _lib._rp3d_body_get_mass(body.cast());
  return result;
}

void rp3d_body_set_linear_velocity(
  self.Pointer<RP3D_RigidBody> body,
  self.Pointer<RP3D_Vector3> linearVelocity,
) {
  final result = _lib._rp3d_body_set_linear_velocity(
    body.cast(),
    linearVelocity.cast(),
  );
  return result;
}

void rp3d_body_get_linear_velocity(
  self.Pointer<RP3D_RigidBody> body,
  self.Pointer<RP3D_Vector3> outLinearVelocity,
) {
  final result = _lib._rp3d_body_get_linear_velocity(
    body.cast(),
    outLinearVelocity.cast(),
  );
  return result;
}

void rp3d_body_set_angular_velocity(
  self.Pointer<RP3D_RigidBody> body,
  self.Pointer<RP3D_Vector3> angularVelocity,
) {
  final result = _lib._rp3d_body_set_angular_velocity(
    body.cast(),
    angularVelocity.cast(),
  );
  return result;
}

void rp3d_body_get_angular_velocity(
  self.Pointer<RP3D_RigidBody> body,
  self.Pointer<RP3D_Vector3> outAngularVelocity,
) {
  final result = _lib._rp3d_body_get_angular_velocity(
    body.cast(),
    outAngularVelocity.cast(),
  );
  return result;
}

void rp3d_body_apply_force(
  self.Pointer<RP3D_RigidBody> body,
  self.Pointer<RP3D_Vector3> force,
) {
  final result = _lib._rp3d_body_apply_force(body.cast(), force.cast());
  return result;
}

void rp3d_body_apply_force_at_position(
  self.Pointer<RP3D_RigidBody> body,
  self.Pointer<RP3D_Vector3> force,
  self.Pointer<RP3D_Vector3> position,
) {
  final result = _lib._rp3d_body_apply_force_at_position(
    body.cast(),
    force.cast(),
    position.cast(),
  );
  return result;
}

void rp3d_body_apply_torque(
  self.Pointer<RP3D_RigidBody> body,
  self.Pointer<RP3D_Vector3> torque,
) {
  final result = _lib._rp3d_body_apply_torque(body.cast(), torque.cast());
  return result;
}

void rp3d_body_set_is_active(self.Pointer<RP3D_RigidBody> body, int isActive) {
  final result = _lib._rp3d_body_set_is_active(body.cast(), isActive);
  return result;
}

int rp3d_body_get_is_active(self.Pointer<RP3D_RigidBody> body) {
  final result = _lib._rp3d_body_get_is_active(body.cast());
  return result;
}

void rp3d_body_set_is_sleeping_allowed(
  self.Pointer<RP3D_RigidBody> body,
  int isAllowed,
) {
  final result = _lib._rp3d_body_set_is_sleeping_allowed(
    body.cast(),
    isAllowed,
  );
  return result;
}

int rp3d_body_get_is_sleeping_allowed(self.Pointer<RP3D_RigidBody> body) {
  final result = _lib._rp3d_body_get_is_sleeping_allowed(body.cast());
  return result;
}

/// Gravity control
void rp3d_body_enable_gravity(
  self.Pointer<RP3D_RigidBody> body,
  int enableGravity,
) {
  final result = _lib._rp3d_body_enable_gravity(body.cast(), enableGravity);
  return result;
}

int rp3d_body_is_gravity_enabled(self.Pointer<RP3D_RigidBody> body) {
  final result = _lib._rp3d_body_is_gravity_enabled(body.cast());
  return result;
}

/// Debug rendering
void rp3d_body_set_is_debug_enabled(
  self.Pointer<RP3D_RigidBody> body,
  int isEnabled,
) {
  final result = _lib._rp3d_body_set_is_debug_enabled(body.cast(), isEnabled);
  return result;
}

int rp3d_body_get_is_debug_enabled(self.Pointer<RP3D_RigidBody> body) {
  final result = _lib._rp3d_body_get_is_debug_enabled(body.cast());
  return result;
}

/// Mass properties
void rp3d_body_update_mass_properties_from_colliders(
  self.Pointer<RP3D_RigidBody> body,
) {
  final result = _lib._rp3d_body_update_mass_properties_from_colliders(
    body.cast(),
  );
  return result;
}

/// Collider management
self.Pointer<RP3D_Collider> rp3d_body_add_collider(
  self.Pointer<RP3D_RigidBody> body,
  self.Pointer<RP3D_CollisionShape> shape,
  self.Pointer<RP3D_Transform> transform,
) {
  final result = _lib._rp3d_body_add_collider(
    body.cast(),
    shape.cast(),
    transform.cast(),
  );
  return self.Pointer<RP3D_Collider>(result);
}

void rp3d_body_remove_collider(
  self.Pointer<RP3D_RigidBody> body,
  self.Pointer<RP3D_Collider> collider,
) {
  final result = _lib._rp3d_body_remove_collider(body.cast(), collider.cast());
  return result;
}

void rp3d_collider_set_material(
  self.Pointer<RP3D_Collider> collider,
  self.Pointer<RP3D_Material> material,
) {
  final result = _lib._rp3d_collider_set_material(
    collider.cast(),
    material.cast(),
  );
  return result;
}

/// ==================== Collider ====================
self.Pointer<RP3D_Material> rp3d_collider_get_material(
  self.Pointer<RP3D_Collider> collider,
) {
  final result = _lib._rp3d_collider_get_material(collider.cast());
  return self.Pointer<RP3D_Material>(result);
}

void rp3d_collider_get_local_bounds(
  self.Pointer<RP3D_Collider> collider,
  self.Pointer<RP3D_AABB> outAABB,
) {
  final result = _lib._rp3d_collider_get_local_bounds(
    collider.cast(),
    outAABB.cast(),
  );
  return result;
}

void rp3d_collider_set_is_trigger(
  self.Pointer<RP3D_Collider> collider,
  int isTrigger,
) {
  final result = _lib._rp3d_collider_set_is_trigger(collider.cast(), isTrigger);
  return result;
}

int rp3d_collider_get_is_trigger(self.Pointer<RP3D_Collider> collider) {
  final result = _lib._rp3d_collider_get_is_trigger(collider.cast());
  return result;
}

/// ==================== Material ====================
void rp3d_material_destroy(self.Pointer<RP3D_Material> material) {
  final result = _lib._rp3d_material_destroy(material.cast());
  return result;
}

void rp3d_material_set_bounciness(
  self.Pointer<RP3D_Material> material,
  double bounciness,
) {
  final result = _lib._rp3d_material_set_bounciness(
    material.cast(),
    bounciness,
  );
  return result;
}

double rp3d_material_get_bounciness(self.Pointer<RP3D_Material> material) {
  final result = _lib._rp3d_material_get_bounciness(material.cast());
  return result;
}

void rp3d_material_set_friction_coefficient(
  self.Pointer<RP3D_Material> material,
  double frictionCoefficient,
) {
  final result = _lib._rp3d_material_set_friction_coefficient(
    material.cast(),
    frictionCoefficient,
  );
  return result;
}

double rp3d_material_get_friction_coefficient(
  self.Pointer<RP3D_Material> material,
) {
  final result = _lib._rp3d_material_get_friction_coefficient(material.cast());
  return result;
}

void rp3d_material_set_mass_density(
  self.Pointer<RP3D_Material> material,
  double massDensity,
) {
  final result = _lib._rp3d_material_set_mass_density(
    material.cast(),
    massDensity,
  );
  return result;
}

double rp3d_material_get_mass_density(self.Pointer<RP3D_Material> material) {
  final result = _lib._rp3d_material_get_mass_density(material.cast());
  return result;
}

/// ==================== CollisionShape (base) ====================
void rp3d_shape_get_local_bounds(
  self.Pointer<RP3D_CollisionShape> shape,
  self.Pointer<RP3D_AABB> outAABB,
) {
  final result = _lib._rp3d_shape_get_local_bounds(
    shape.cast(),
    outAABB.cast(),
  );
  return result;
}

void rp3d_concave_shape_set_scale(
  self.Pointer<RP3D_HeightFieldShape> shape,
  self.Pointer<RP3D_Vector3> scale,
) {
  final result = _lib._rp3d_concave_shape_set_scale(shape.cast(), scale.cast());
  return result;
}

/// ==================== HeightFieldShape ====================
void rp3d_height_field_shape_get_vertex_at(
  self.Pointer<RP3D_HeightFieldShape> heightFieldShape,
  int row,
  int column,
  self.Pointer<RP3D_Vector3> outVertex,
) {
  final result = _lib._rp3d_height_field_shape_get_vertex_at(
    heightFieldShape.cast(),
    row,
    column,
    outVertex.cast(),
  );
  return result;
}

/// Vector3
void rp3d_vector3_zero(self.Pointer<RP3D_Vector3> v) {
  final result = _lib._rp3d_vector3_zero(v.cast());
  return result;
}

double rp3d_vector3_length(self.Pointer<RP3D_Vector3> v) {
  final result = _lib._rp3d_vector3_length(v.cast());
  return result;
}

void rp3d_vector3_normalize(self.Pointer<RP3D_Vector3> v) {
  final result = _lib._rp3d_vector3_normalize(v.cast());
  return result;
}

double rp3d_vector3_dot(
  self.Pointer<RP3D_Vector3> v1,
  self.Pointer<RP3D_Vector3> v2,
) {
  final result = _lib._rp3d_vector3_dot(v1.cast(), v2.cast());
  return result;
}

void rp3d_vector3_cross(
  self.Pointer<RP3D_Vector3> v1,
  self.Pointer<RP3D_Vector3> v2,
  self.Pointer<RP3D_Vector3> outResult,
) {
  final result = _lib._rp3d_vector3_cross(
    v1.cast(),
    v2.cast(),
    outResult.cast(),
  );
  return result;
}

/// Quaternion
void rp3d_quaternion_identity(self.Pointer<RP3D_Quaternion> q) {
  final result = _lib._rp3d_quaternion_identity(q.cast());
  return result;
}

void rp3d_quaternion_from_axis_angle(
  self.Pointer<RP3D_Vector3> axis,
  double angle,
  self.Pointer<RP3D_Quaternion> outQuat,
) {
  final result = _lib._rp3d_quaternion_from_axis_angle(
    axis.cast(),
    angle,
    outQuat.cast(),
  );
  return result;
}

void rp3d_quaternion_normalize(self.Pointer<RP3D_Quaternion> q) {
  final result = _lib._rp3d_quaternion_normalize(q.cast());
  return result;
}

/// Transform
void rp3d_transform_identity(self.Pointer<RP3D_Transform> t) {
  final result = _lib._rp3d_transform_identity(t.cast());
  return result;
}

void rp3d_transform_inverse(
  self.Pointer<RP3D_Transform> t,
  self.Pointer<RP3D_Transform> outInverse,
) {
  final result = _lib._rp3d_transform_inverse(t.cast(), outInverse.cast());
  return result;
}

void rp3d_transform_get_opengl_matrix(
  self.Pointer<RP3D_Transform> t,
  self.Pointer<Float32> outMatrix,
) {
  final result = _lib._rp3d_transform_get_opengl_matrix(t.cast(), outMatrix);
  return result;
}

/// ==================== DebugRenderer ====================
void rp3d_debug_renderer_set_is_debug_item_displayed(
  self.Pointer<RP3D_DebugRenderer> renderer,
  int item,
  int isDisplayed,
) {
  final result = _lib._rp3d_debug_renderer_set_is_debug_item_displayed(
    renderer.cast(),
    item,
    isDisplayed,
  );
  return result;
}

int rp3d_debug_renderer_get_is_debug_item_displayed(
  self.Pointer<RP3D_DebugRenderer> renderer,
  int item,
) {
  final result = _lib._rp3d_debug_renderer_get_is_debug_item_displayed(
    renderer.cast(),
    item,
  );
  return result;
}

int rp3d_debug_renderer_get_nb_lines(
  self.Pointer<RP3D_DebugRenderer> renderer,
) {
  final result = _lib._rp3d_debug_renderer_get_nb_lines(renderer.cast());
  return result;
}

int rp3d_debug_renderer_get_nb_triangles(
  self.Pointer<RP3D_DebugRenderer> renderer,
) {
  final result = _lib._rp3d_debug_renderer_get_nb_triangles(renderer.cast());
  return result;
}

void rp3d_debug_renderer_get_lines_array(
  self.Pointer<RP3D_DebugRenderer> renderer,
  self.Pointer<Float32> outVertices,
  self.Pointer<Uint32> outColors,
) {
  final result = _lib._rp3d_debug_renderer_get_lines_array(
    renderer.cast(),
    outVertices,
    outColors,
  );
  return result;
}

void rp3d_debug_renderer_get_triangles_array(
  self.Pointer<RP3D_DebugRenderer> renderer,
  self.Pointer<Float32> outVertices,
  self.Pointer<Uint32> outColors,
) {
  final result = _lib._rp3d_debug_renderer_get_triangles_array(
    renderer.cast(),
    outVertices,
    outColors,
  );
  return result;
}

/// ==================== Joints ====================
self.Pointer<RP3D_BallAndSocketJoint> rp3d_world_create_ball_and_socket_joint(
  self.Pointer<RP3D_PhysicsWorld> world,
  self.Pointer<RP3D_BallAndSocketJointInfo> jointInfo,
) {
  final result = _lib._rp3d_world_create_ball_and_socket_joint(
    world.cast(),
    jointInfo.cast(),
  );
  return self.Pointer<RP3D_BallAndSocketJoint>(result);
}

self.Pointer<RP3D_HingeJoint> rp3d_world_create_hinge_joint(
  self.Pointer<RP3D_PhysicsWorld> world,
  self.Pointer<RP3D_HingeJointInfo> jointInfo,
) {
  final result = _lib._rp3d_world_create_hinge_joint(
    world.cast(),
    jointInfo.cast(),
  );
  return self.Pointer<RP3D_HingeJoint>(result);
}

self.Pointer<RP3D_SliderJoint> rp3d_world_create_slider_joint(
  self.Pointer<RP3D_PhysicsWorld> world,
  self.Pointer<RP3D_SliderJointInfo> jointInfo,
) {
  final result = _lib._rp3d_world_create_slider_joint(
    world.cast(),
    jointInfo.cast(),
  );
  return self.Pointer<RP3D_SliderJoint>(result);
}

self.Pointer<RP3D_FixedJoint> rp3d_world_create_fixed_joint(
  self.Pointer<RP3D_PhysicsWorld> world,
  self.Pointer<RP3D_FixedJointInfo> jointInfo,
) {
  final result = _lib._rp3d_world_create_fixed_joint(
    world.cast(),
    jointInfo.cast(),
  );
  return self.Pointer<RP3D_FixedJoint>(result);
}

void rp3d_world_destroy_joint(
  self.Pointer<RP3D_PhysicsWorld> world,
  self.Pointer<Void> joint,
) {
  final result = _lib._rp3d_world_destroy_joint(world.cast(), joint);
  return result;
}

extension RP3D_PhysicsCommonExt on Pointer<RP3D_PhysicsCommon> {
  RP3D_PhysicsCommon toDart() {
    return RP3D_PhysicsCommon(this);
  }
}

final class RP3D_PhysicsCommon extends self.Struct {
  RP3D_PhysicsCommon(super._address);

  static Pointer<RP3D_PhysicsCommon> stackAlloc() {
    return Pointer<RP3D_PhysicsCommon>(_lib._stackAlloc<RP3D_PhysicsCommon>(0));
  }
}

extension RP3D_PhysicsWorldExt on Pointer<RP3D_PhysicsWorld> {
  RP3D_PhysicsWorld toDart() {
    return RP3D_PhysicsWorld(this);
  }
}

final class RP3D_PhysicsWorld extends self.Struct {
  RP3D_PhysicsWorld(super._address);

  static Pointer<RP3D_PhysicsWorld> stackAlloc() {
    return Pointer<RP3D_PhysicsWorld>(_lib._stackAlloc<RP3D_PhysicsWorld>(0));
  }
}

extension RP3D_BoxShapeExt on Pointer<RP3D_BoxShape> {
  RP3D_BoxShape toDart() {
    return RP3D_BoxShape(this);
  }
}

final class RP3D_BoxShape extends self.Struct {
  RP3D_BoxShape(super._address);

  static Pointer<RP3D_BoxShape> stackAlloc() {
    return Pointer<RP3D_BoxShape>(_lib._stackAlloc<RP3D_BoxShape>(0));
  }
}

/// ==================== Value Types (POD Structs) ====================

extension RP3D_Vector3Ext on Pointer<RP3D_Vector3> {
  RP3D_Vector3 toDart() {
    return RP3D_Vector3(this);
  }
}

final class RP3D_Vector3 extends self.Struct {
  double get x {
    final addr = this._address + 0;
    final value = _lib.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set x(double val) {
    _lib.setValue(this._address + 0, val.toJS, 'float');
  }

  double get y {
    final addr = this._address + 4;
    final value = _lib.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set y(double val) {
    _lib.setValue(this._address + 4, val.toJS, 'float');
  }

  double get z {
    final addr = this._address + 8;
    final value = _lib.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set z(double val) {
    _lib.setValue(this._address + 8, val.toJS, 'float');
  }

  RP3D_Vector3(super._address);

  static Pointer<RP3D_Vector3> stackAlloc() {
    return Pointer<RP3D_Vector3>(_lib._stackAlloc<RP3D_Vector3>(12));
  }
}

extension RP3D_SphereShapeExt on Pointer<RP3D_SphereShape> {
  RP3D_SphereShape toDart() {
    return RP3D_SphereShape(this);
  }
}

final class RP3D_SphereShape extends self.Struct {
  RP3D_SphereShape(super._address);

  static Pointer<RP3D_SphereShape> stackAlloc() {
    return Pointer<RP3D_SphereShape>(_lib._stackAlloc<RP3D_SphereShape>(0));
  }
}

extension RP3D_CapsuleShapeExt on Pointer<RP3D_CapsuleShape> {
  RP3D_CapsuleShape toDart() {
    return RP3D_CapsuleShape(this);
  }
}

final class RP3D_CapsuleShape extends self.Struct {
  RP3D_CapsuleShape(super._address);

  static Pointer<RP3D_CapsuleShape> stackAlloc() {
    return Pointer<RP3D_CapsuleShape>(_lib._stackAlloc<RP3D_CapsuleShape>(0));
  }
}

extension RP3D_HeightFieldExt on Pointer<RP3D_HeightField> {
  RP3D_HeightField toDart() {
    return RP3D_HeightField(this);
  }
}

final class RP3D_HeightField extends self.Struct {
  RP3D_HeightField(super._address);

  static Pointer<RP3D_HeightField> stackAlloc() {
    return Pointer<RP3D_HeightField>(_lib._stackAlloc<RP3D_HeightField>(0));
  }
}

extension RP3D_HeightFieldShapeExt on Pointer<RP3D_HeightFieldShape> {
  RP3D_HeightFieldShape toDart() {
    return RP3D_HeightFieldShape(this);
  }
}

final class RP3D_HeightFieldShape extends self.Struct {
  RP3D_HeightFieldShape(super._address);

  static Pointer<RP3D_HeightFieldShape> stackAlloc() {
    return Pointer<RP3D_HeightFieldShape>(
      _lib._stackAlloc<RP3D_HeightFieldShape>(0),
    );
  }
}

extension RP3D_TriangleVertexArrayExt on Pointer<RP3D_TriangleVertexArray> {
  RP3D_TriangleVertexArray toDart() {
    return RP3D_TriangleVertexArray(this);
  }
}

final class RP3D_TriangleVertexArray extends self.Struct {
  RP3D_TriangleVertexArray(super._address);

  static Pointer<RP3D_TriangleVertexArray> stackAlloc() {
    return Pointer<RP3D_TriangleVertexArray>(
      _lib._stackAlloc<RP3D_TriangleVertexArray>(0),
    );
  }
}

extension RP3D_PolygonVertexArrayExt on Pointer<RP3D_PolygonVertexArray> {
  RP3D_PolygonVertexArray toDart() {
    return RP3D_PolygonVertexArray(this);
  }
}

final class RP3D_PolygonVertexArray extends self.Struct {
  RP3D_PolygonVertexArray(super._address);

  static Pointer<RP3D_PolygonVertexArray> stackAlloc() {
    return Pointer<RP3D_PolygonVertexArray>(
      _lib._stackAlloc<RP3D_PolygonVertexArray>(0),
    );
  }
}

extension RP3D_TriangleMeshExt on Pointer<RP3D_TriangleMesh> {
  RP3D_TriangleMesh toDart() {
    return RP3D_TriangleMesh(this);
  }
}

final class RP3D_TriangleMesh extends self.Struct {
  RP3D_TriangleMesh(super._address);

  static Pointer<RP3D_TriangleMesh> stackAlloc() {
    return Pointer<RP3D_TriangleMesh>(_lib._stackAlloc<RP3D_TriangleMesh>(0));
  }
}

extension RP3D_ConvexMeshExt on Pointer<RP3D_ConvexMesh> {
  RP3D_ConvexMesh toDart() {
    return RP3D_ConvexMesh(this);
  }
}

final class RP3D_ConvexMesh extends self.Struct {
  RP3D_ConvexMesh(super._address);

  static Pointer<RP3D_ConvexMesh> stackAlloc() {
    return Pointer<RP3D_ConvexMesh>(_lib._stackAlloc<RP3D_ConvexMesh>(0));
  }
}

extension RP3D_ConvexMeshShapeExt on Pointer<RP3D_ConvexMeshShape> {
  RP3D_ConvexMeshShape toDart() {
    return RP3D_ConvexMeshShape(this);
  }
}

final class RP3D_ConvexMeshShape extends self.Struct {
  RP3D_ConvexMeshShape(super._address);

  static Pointer<RP3D_ConvexMeshShape> stackAlloc() {
    return Pointer<RP3D_ConvexMeshShape>(
      _lib._stackAlloc<RP3D_ConvexMeshShape>(0),
    );
  }
}

extension RP3D_ConcaveMeshShapeExt on Pointer<RP3D_ConcaveMeshShape> {
  RP3D_ConcaveMeshShape toDart() {
    return RP3D_ConcaveMeshShape(this);
  }
}

final class RP3D_ConcaveMeshShape extends self.Struct {
  RP3D_ConcaveMeshShape(super._address);

  static Pointer<RP3D_ConcaveMeshShape> stackAlloc() {
    return Pointer<RP3D_ConcaveMeshShape>(
      _lib._stackAlloc<RP3D_ConcaveMeshShape>(0),
    );
  }
}

extension RP3D_DebugRendererExt on Pointer<RP3D_DebugRenderer> {
  RP3D_DebugRenderer toDart() {
    return RP3D_DebugRenderer(this);
  }
}

final class RP3D_DebugRenderer extends self.Struct {
  RP3D_DebugRenderer(super._address);

  static Pointer<RP3D_DebugRenderer> stackAlloc() {
    return Pointer<RP3D_DebugRenderer>(_lib._stackAlloc<RP3D_DebugRenderer>(0));
  }
}

extension RP3D_RigidBodyExt on Pointer<RP3D_RigidBody> {
  RP3D_RigidBody toDart() {
    return RP3D_RigidBody(this);
  }
}

final class RP3D_RigidBody extends self.Struct {
  RP3D_RigidBody(super._address);

  static Pointer<RP3D_RigidBody> stackAlloc() {
    return Pointer<RP3D_RigidBody>(_lib._stackAlloc<RP3D_RigidBody>(0));
  }
}

extension RP3D_TransformExt on Pointer<RP3D_Transform> {
  RP3D_Transform toDart() {
    return RP3D_Transform(this);
  }
}

final class RP3D_Transform extends self.Struct {
  RP3D_Vector3 get position {
    final addr = this._address + 0;
    final value = _lib.getValue(addr, '*');
    return RP3D_Vector3(self.Pointer<RP3D_Vector3>(addr));
  }

  set position(RP3D_Vector3 val) {
    _lib.setValue(this._address + 0, val.address.toJS, '*');
  }

  RP3D_Quaternion get orientation {
    final addr = this._address + 12;
    final value = _lib.getValue(addr, '*');
    return RP3D_Quaternion(self.Pointer<RP3D_Quaternion>(addr));
  }

  set orientation(RP3D_Quaternion val) {
    _lib.setValue(this._address + 12, val.address.toJS, '*');
  }

  RP3D_Transform(super._address);

  static Pointer<RP3D_Transform> stackAlloc() {
    return Pointer<RP3D_Transform>(_lib._stackAlloc<RP3D_Transform>(28));
  }
}

extension RP3D_QuaternionExt on Pointer<RP3D_Quaternion> {
  RP3D_Quaternion toDart() {
    return RP3D_Quaternion(this);
  }
}

final class RP3D_Quaternion extends self.Struct {
  double get x {
    final addr = this._address + 0;
    final value = _lib.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set x(double val) {
    _lib.setValue(this._address + 0, val.toJS, 'float');
  }

  double get y {
    final addr = this._address + 4;
    final value = _lib.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set y(double val) {
    _lib.setValue(this._address + 4, val.toJS, 'float');
  }

  double get z {
    final addr = this._address + 8;
    final value = _lib.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set z(double val) {
    _lib.setValue(this._address + 8, val.toJS, 'float');
  }

  double get w {
    final addr = this._address + 12;
    final value = _lib.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set w(double val) {
    _lib.setValue(this._address + 12, val.toJS, 'float');
  }

  RP3D_Quaternion(super._address);

  static Pointer<RP3D_Quaternion> stackAlloc() {
    return Pointer<RP3D_Quaternion>(_lib._stackAlloc<RP3D_Quaternion>(16));
  }
}

extension RP3D_RayExt on Pointer<RP3D_Ray> {
  RP3D_Ray toDart() {
    return RP3D_Ray(this);
  }
}

final class RP3D_Ray extends self.Struct {
  RP3D_Vector3 get point1 {
    final addr = this._address + 0;
    final value = _lib.getValue(addr, '*');
    return RP3D_Vector3(self.Pointer<RP3D_Vector3>(addr));
  }

  set point1(RP3D_Vector3 val) {
    _lib.setValue(this._address + 0, val.address.toJS, '*');
  }

  RP3D_Vector3 get point2 {
    final addr = this._address + 12;
    final value = _lib.getValue(addr, '*');
    return RP3D_Vector3(self.Pointer<RP3D_Vector3>(addr));
  }

  set point2(RP3D_Vector3 val) {
    _lib.setValue(this._address + 12, val.address.toJS, '*');
  }

  double get maxFraction {
    final addr = this._address + 24;
    final value = _lib.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set maxFraction(double val) {
    _lib.setValue(this._address + 24, val.toJS, 'float');
  }

  RP3D_Ray(super._address);

  static Pointer<RP3D_Ray> stackAlloc() {
    return Pointer<RP3D_Ray>(_lib._stackAlloc<RP3D_Ray>(28));
  }
}

extension RP3D_RaycastInfoExt on Pointer<RP3D_RaycastInfo> {
  RP3D_RaycastInfo toDart() {
    return RP3D_RaycastInfo(this);
  }
}

final class RP3D_RaycastInfo extends self.Struct {
  self.Pointer<RP3D_RigidBody> get body {
    final addr = this._address + 0;
    final value = _lib.getValue(addr, '*');
    return self.Pointer<RP3D_RigidBody>(value.toDartInt);
  }

  set body(self.Pointer<RP3D_RigidBody> val) {
    _lib.setValue(this._address + 0, val.toJS, '*');
  }

  self.Pointer<RP3D_Collider> get collider {
    final addr = this._address + 4;
    final value = _lib.getValue(addr, '*');
    return self.Pointer<RP3D_Collider>(value.toDartInt);
  }

  set collider(self.Pointer<RP3D_Collider> val) {
    _lib.setValue(this._address + 4, val.toJS, '*');
  }

  RP3D_Vector3 get worldPoint {
    final addr = this._address + 8;
    final value = _lib.getValue(addr, '*');
    return RP3D_Vector3(self.Pointer<RP3D_Vector3>(addr));
  }

  set worldPoint(RP3D_Vector3 val) {
    _lib.setValue(this._address + 8, val.address.toJS, '*');
  }

  RP3D_Vector3 get worldNormal {
    final addr = this._address + 20;
    final value = _lib.getValue(addr, '*');
    return RP3D_Vector3(self.Pointer<RP3D_Vector3>(addr));
  }

  set worldNormal(RP3D_Vector3 val) {
    _lib.setValue(this._address + 20, val.address.toJS, '*');
  }

  double get hitFraction {
    final addr = this._address + 32;
    final value = _lib.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set hitFraction(double val) {
    _lib.setValue(this._address + 32, val.toJS, 'float');
  }

  RP3D_RaycastInfo(super._address);

  static Pointer<RP3D_RaycastInfo> stackAlloc() {
    return Pointer<RP3D_RaycastInfo>(_lib._stackAlloc<RP3D_RaycastInfo>(36));
  }
}

extension RP3D_ColliderExt on Pointer<RP3D_Collider> {
  RP3D_Collider toDart() {
    return RP3D_Collider(this);
  }
}

final class RP3D_Collider extends self.Struct {
  RP3D_Collider(super._address);

  static Pointer<RP3D_Collider> stackAlloc() {
    return Pointer<RP3D_Collider>(_lib._stackAlloc<RP3D_Collider>(0));
  }
}

/// ==================== Enums ====================
sealed class RP3D_BodyType {
  static const RP3D_BODY_TYPE_STATIC = 1;
  static const RP3D_BODY_TYPE_KINEMATIC = 2;
  static const RP3D_BODY_TYPE_DYNAMIC = 3;
}

extension RP3D_CollisionShapeExt on Pointer<RP3D_CollisionShape> {
  RP3D_CollisionShape toDart() {
    return RP3D_CollisionShape(this);
  }
}

final class RP3D_CollisionShape extends self.Struct {
  RP3D_CollisionShape(super._address);

  static Pointer<RP3D_CollisionShape> stackAlloc() {
    return Pointer<RP3D_CollisionShape>(
      _lib._stackAlloc<RP3D_CollisionShape>(0),
    );
  }
}

extension RP3D_MaterialExt on Pointer<RP3D_Material> {
  RP3D_Material toDart() {
    return RP3D_Material(this);
  }
}

final class RP3D_Material extends self.Struct {
  RP3D_Material(super._address);

  static Pointer<RP3D_Material> stackAlloc() {
    return Pointer<RP3D_Material>(_lib._stackAlloc<RP3D_Material>(0));
  }
}

extension RP3D_AABBExt on Pointer<RP3D_AABB> {
  RP3D_AABB toDart() {
    return RP3D_AABB(this);
  }
}

final class RP3D_AABB extends self.Struct {
  RP3D_Vector3 get min {
    final addr = this._address + 0;
    final value = _lib.getValue(addr, '*');
    return RP3D_Vector3(self.Pointer<RP3D_Vector3>(addr));
  }

  set min(RP3D_Vector3 val) {
    _lib.setValue(this._address + 0, val.address.toJS, '*');
  }

  RP3D_Vector3 get max {
    final addr = this._address + 12;
    final value = _lib.getValue(addr, '*');
    return RP3D_Vector3(self.Pointer<RP3D_Vector3>(addr));
  }

  set max(RP3D_Vector3 val) {
    _lib.setValue(this._address + 12, val.address.toJS, '*');
  }

  RP3D_AABB(super._address);

  static Pointer<RP3D_AABB> stackAlloc() {
    return Pointer<RP3D_AABB>(_lib._stackAlloc<RP3D_AABB>(24));
  }
}

sealed class RP3D_DebugItem {
  static const RP3D_DEBUG_ITEM_COLLIDER_AABB = 1;
  static const RP3D_DEBUG_ITEM_COLLIDER_BROADPHASE_AABB = 2;
  static const RP3D_DEBUG_ITEM_COLLISION_SHAPE = 4;
  static const RP3D_DEBUG_ITEM_CONTACT_POINT = 8;
  static const RP3D_DEBUG_ITEM_CONTACT_NORMAL = 16;
}

extension RP3D_BallAndSocketJointExt on Pointer<RP3D_BallAndSocketJoint> {
  RP3D_BallAndSocketJoint toDart() {
    return RP3D_BallAndSocketJoint(this);
  }
}

final class RP3D_BallAndSocketJoint extends self.Struct {
  RP3D_BallAndSocketJoint(super._address);

  static Pointer<RP3D_BallAndSocketJoint> stackAlloc() {
    return Pointer<RP3D_BallAndSocketJoint>(
      _lib._stackAlloc<RP3D_BallAndSocketJoint>(0),
    );
  }
}

/// Joint info structures

extension RP3D_BallAndSocketJointInfoExt
    on Pointer<RP3D_BallAndSocketJointInfo> {
  RP3D_BallAndSocketJointInfo toDart() {
    return RP3D_BallAndSocketJointInfo(this);
  }
}

final class RP3D_BallAndSocketJointInfo extends self.Struct {
  RP3D_Vector3 get anchorPointWorldSpace {
    final addr = this._address + 0;
    final value = _lib.getValue(addr, '*');
    return RP3D_Vector3(self.Pointer<RP3D_Vector3>(addr));
  }

  set anchorPointWorldSpace(RP3D_Vector3 val) {
    _lib.setValue(this._address + 0, val.address.toJS, '*');
  }

  self.Pointer<RP3D_RigidBody> get body1 {
    final addr = this._address + 12;
    final value = _lib.getValue(addr, '*');
    return self.Pointer<RP3D_RigidBody>(value.toDartInt);
  }

  set body1(self.Pointer<RP3D_RigidBody> val) {
    _lib.setValue(this._address + 12, val.toJS, '*');
  }

  self.Pointer<RP3D_RigidBody> get body2 {
    final addr = this._address + 16;
    final value = _lib.getValue(addr, '*');
    return self.Pointer<RP3D_RigidBody>(value.toDartInt);
  }

  set body2(self.Pointer<RP3D_RigidBody> val) {
    _lib.setValue(this._address + 16, val.toJS, '*');
  }

  int get isCollisionEnabled {
    final addr = this._address + 20;
    final value = _lib.getValue(addr, 'i8').toDartInt;
    return value;
  }

  set isCollisionEnabled(int val) {
    _lib.setValue(this._address + 20, val.toJS, 'i8');
  }

  RP3D_BallAndSocketJointInfo(super._address);

  static Pointer<RP3D_BallAndSocketJointInfo> stackAlloc() {
    return Pointer<RP3D_BallAndSocketJointInfo>(
      _lib._stackAlloc<RP3D_BallAndSocketJointInfo>(21),
    );
  }
}

extension RP3D_HingeJointExt on Pointer<RP3D_HingeJoint> {
  RP3D_HingeJoint toDart() {
    return RP3D_HingeJoint(this);
  }
}

final class RP3D_HingeJoint extends self.Struct {
  RP3D_HingeJoint(super._address);

  static Pointer<RP3D_HingeJoint> stackAlloc() {
    return Pointer<RP3D_HingeJoint>(_lib._stackAlloc<RP3D_HingeJoint>(0));
  }
}

extension RP3D_HingeJointInfoExt on Pointer<RP3D_HingeJointInfo> {
  RP3D_HingeJointInfo toDart() {
    return RP3D_HingeJointInfo(this);
  }
}

final class RP3D_HingeJointInfo extends self.Struct {
  RP3D_Vector3 get anchorPointWorldSpace {
    final addr = this._address + 0;
    final value = _lib.getValue(addr, '*');
    return RP3D_Vector3(self.Pointer<RP3D_Vector3>(addr));
  }

  set anchorPointWorldSpace(RP3D_Vector3 val) {
    _lib.setValue(this._address + 0, val.address.toJS, '*');
  }

  RP3D_Vector3 get rotationAxisWorld {
    final addr = this._address + 12;
    final value = _lib.getValue(addr, '*');
    return RP3D_Vector3(self.Pointer<RP3D_Vector3>(addr));
  }

  set rotationAxisWorld(RP3D_Vector3 val) {
    _lib.setValue(this._address + 12, val.address.toJS, '*');
  }

  self.Pointer<RP3D_RigidBody> get body1 {
    final addr = this._address + 24;
    final value = _lib.getValue(addr, '*');
    return self.Pointer<RP3D_RigidBody>(value.toDartInt);
  }

  set body1(self.Pointer<RP3D_RigidBody> val) {
    _lib.setValue(this._address + 24, val.toJS, '*');
  }

  self.Pointer<RP3D_RigidBody> get body2 {
    final addr = this._address + 28;
    final value = _lib.getValue(addr, '*');
    return self.Pointer<RP3D_RigidBody>(value.toDartInt);
  }

  set body2(self.Pointer<RP3D_RigidBody> val) {
    _lib.setValue(this._address + 28, val.toJS, '*');
  }

  int get isCollisionEnabled {
    final addr = this._address + 32;
    final value = _lib.getValue(addr, 'i8').toDartInt;
    return value;
  }

  set isCollisionEnabled(int val) {
    _lib.setValue(this._address + 32, val.toJS, 'i8');
  }

  int get isLimitEnabled {
    final addr = this._address + 33;
    final value = _lib.getValue(addr, 'i8').toDartInt;
    return value;
  }

  set isLimitEnabled(int val) {
    _lib.setValue(this._address + 33, val.toJS, 'i8');
  }

  int get isMotorEnabled {
    final addr = this._address + 34;
    final value = _lib.getValue(addr, 'i8').toDartInt;
    return value;
  }

  set isMotorEnabled(int val) {
    _lib.setValue(this._address + 34, val.toJS, 'i8');
  }

  double get minAngleLimit {
    final addr = this._address + 35;
    final value = _lib.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set minAngleLimit(double val) {
    _lib.setValue(this._address + 35, val.toJS, 'float');
  }

  double get maxAngleLimit {
    final addr = this._address + 39;
    final value = _lib.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set maxAngleLimit(double val) {
    _lib.setValue(this._address + 39, val.toJS, 'float');
  }

  double get motorSpeed {
    final addr = this._address + 43;
    final value = _lib.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set motorSpeed(double val) {
    _lib.setValue(this._address + 43, val.toJS, 'float');
  }

  double get maxMotorTorque {
    final addr = this._address + 47;
    final value = _lib.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set maxMotorTorque(double val) {
    _lib.setValue(this._address + 47, val.toJS, 'float');
  }

  RP3D_HingeJointInfo(super._address);

  static Pointer<RP3D_HingeJointInfo> stackAlloc() {
    return Pointer<RP3D_HingeJointInfo>(
      _lib._stackAlloc<RP3D_HingeJointInfo>(51),
    );
  }
}

extension RP3D_SliderJointExt on Pointer<RP3D_SliderJoint> {
  RP3D_SliderJoint toDart() {
    return RP3D_SliderJoint(this);
  }
}

final class RP3D_SliderJoint extends self.Struct {
  RP3D_SliderJoint(super._address);

  static Pointer<RP3D_SliderJoint> stackAlloc() {
    return Pointer<RP3D_SliderJoint>(_lib._stackAlloc<RP3D_SliderJoint>(0));
  }
}

extension RP3D_SliderJointInfoExt on Pointer<RP3D_SliderJointInfo> {
  RP3D_SliderJointInfo toDart() {
    return RP3D_SliderJointInfo(this);
  }
}

final class RP3D_SliderJointInfo extends self.Struct {
  RP3D_Vector3 get anchorPointWorldSpace {
    final addr = this._address + 0;
    final value = _lib.getValue(addr, '*');
    return RP3D_Vector3(self.Pointer<RP3D_Vector3>(addr));
  }

  set anchorPointWorldSpace(RP3D_Vector3 val) {
    _lib.setValue(this._address + 0, val.address.toJS, '*');
  }

  RP3D_Vector3 get sliderAxisWorldSpace {
    final addr = this._address + 12;
    final value = _lib.getValue(addr, '*');
    return RP3D_Vector3(self.Pointer<RP3D_Vector3>(addr));
  }

  set sliderAxisWorldSpace(RP3D_Vector3 val) {
    _lib.setValue(this._address + 12, val.address.toJS, '*');
  }

  self.Pointer<RP3D_RigidBody> get body1 {
    final addr = this._address + 24;
    final value = _lib.getValue(addr, '*');
    return self.Pointer<RP3D_RigidBody>(value.toDartInt);
  }

  set body1(self.Pointer<RP3D_RigidBody> val) {
    _lib.setValue(this._address + 24, val.toJS, '*');
  }

  self.Pointer<RP3D_RigidBody> get body2 {
    final addr = this._address + 28;
    final value = _lib.getValue(addr, '*');
    return self.Pointer<RP3D_RigidBody>(value.toDartInt);
  }

  set body2(self.Pointer<RP3D_RigidBody> val) {
    _lib.setValue(this._address + 28, val.toJS, '*');
  }

  int get isCollisionEnabled {
    final addr = this._address + 32;
    final value = _lib.getValue(addr, 'i8').toDartInt;
    return value;
  }

  set isCollisionEnabled(int val) {
    _lib.setValue(this._address + 32, val.toJS, 'i8');
  }

  int get isLimitEnabled {
    final addr = this._address + 33;
    final value = _lib.getValue(addr, 'i8').toDartInt;
    return value;
  }

  set isLimitEnabled(int val) {
    _lib.setValue(this._address + 33, val.toJS, 'i8');
  }

  int get isMotorEnabled {
    final addr = this._address + 34;
    final value = _lib.getValue(addr, 'i8').toDartInt;
    return value;
  }

  set isMotorEnabled(int val) {
    _lib.setValue(this._address + 34, val.toJS, 'i8');
  }

  double get minTranslationLimit {
    final addr = this._address + 35;
    final value = _lib.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set minTranslationLimit(double val) {
    _lib.setValue(this._address + 35, val.toJS, 'float');
  }

  double get maxTranslationLimit {
    final addr = this._address + 39;
    final value = _lib.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set maxTranslationLimit(double val) {
    _lib.setValue(this._address + 39, val.toJS, 'float');
  }

  double get motorSpeed {
    final addr = this._address + 43;
    final value = _lib.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set motorSpeed(double val) {
    _lib.setValue(this._address + 43, val.toJS, 'float');
  }

  double get maxMotorForce {
    final addr = this._address + 47;
    final value = _lib.getValue(addr, 'float').toDartDouble;
    return value;
  }

  set maxMotorForce(double val) {
    _lib.setValue(this._address + 47, val.toJS, 'float');
  }

  RP3D_SliderJointInfo(super._address);

  static Pointer<RP3D_SliderJointInfo> stackAlloc() {
    return Pointer<RP3D_SliderJointInfo>(
      _lib._stackAlloc<RP3D_SliderJointInfo>(51),
    );
  }
}

extension RP3D_FixedJointExt on Pointer<RP3D_FixedJoint> {
  RP3D_FixedJoint toDart() {
    return RP3D_FixedJoint(this);
  }
}

final class RP3D_FixedJoint extends self.Struct {
  RP3D_FixedJoint(super._address);

  static Pointer<RP3D_FixedJoint> stackAlloc() {
    return Pointer<RP3D_FixedJoint>(_lib._stackAlloc<RP3D_FixedJoint>(0));
  }
}

extension RP3D_FixedJointInfoExt on Pointer<RP3D_FixedJointInfo> {
  RP3D_FixedJointInfo toDart() {
    return RP3D_FixedJointInfo(this);
  }
}

final class RP3D_FixedJointInfo extends self.Struct {
  RP3D_Vector3 get anchorPointWorldSpace {
    final addr = this._address + 0;
    final value = _lib.getValue(addr, '*');
    return RP3D_Vector3(self.Pointer<RP3D_Vector3>(addr));
  }

  set anchorPointWorldSpace(RP3D_Vector3 val) {
    _lib.setValue(this._address + 0, val.address.toJS, '*');
  }

  self.Pointer<RP3D_RigidBody> get body1 {
    final addr = this._address + 12;
    final value = _lib.getValue(addr, '*');
    return self.Pointer<RP3D_RigidBody>(value.toDartInt);
  }

  set body1(self.Pointer<RP3D_RigidBody> val) {
    _lib.setValue(this._address + 12, val.toJS, '*');
  }

  self.Pointer<RP3D_RigidBody> get body2 {
    final addr = this._address + 16;
    final value = _lib.getValue(addr, '*');
    return self.Pointer<RP3D_RigidBody>(value.toDartInt);
  }

  set body2(self.Pointer<RP3D_RigidBody> val) {
    _lib.setValue(this._address + 16, val.toJS, '*');
  }

  int get isCollisionEnabled {
    final addr = this._address + 20;
    final value = _lib.getValue(addr, 'i8').toDartInt;
    return value;
  }

  set isCollisionEnabled(int val) {
    _lib.setValue(this._address + 20, val.toJS, 'i8');
  }

  RP3D_FixedJointInfo(super._address);

  static Pointer<RP3D_FixedJointInfo> stackAlloc() {
    return Pointer<RP3D_FixedJointInfo>(
      _lib._stackAlloc<RP3D_FixedJointInfo>(21),
    );
  }
}

sealed class Struct extends NativeType {
  final Pointer _address;

  Struct(this._address);

  static T create<T extends Struct>() {
    switch (T) {
      case RP3D_PhysicsCommon:
        final ptr = RP3D_PhysicsCommon.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_PhysicsWorld:
        final ptr = RP3D_PhysicsWorld.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_BoxShape:
        final ptr = RP3D_BoxShape.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_Vector3:
        final ptr = RP3D_Vector3.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_SphereShape:
        final ptr = RP3D_SphereShape.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_CapsuleShape:
        final ptr = RP3D_CapsuleShape.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_HeightField:
        final ptr = RP3D_HeightField.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_HeightFieldShape:
        final ptr = RP3D_HeightFieldShape.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_TriangleVertexArray:
        final ptr = RP3D_TriangleVertexArray.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_PolygonVertexArray:
        final ptr = RP3D_PolygonVertexArray.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_TriangleMesh:
        final ptr = RP3D_TriangleMesh.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_ConvexMesh:
        final ptr = RP3D_ConvexMesh.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_ConvexMeshShape:
        final ptr = RP3D_ConvexMeshShape.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_ConcaveMeshShape:
        final ptr = RP3D_ConcaveMeshShape.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_DebugRenderer:
        final ptr = RP3D_DebugRenderer.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_RigidBody:
        final ptr = RP3D_RigidBody.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_Transform:
        final ptr = RP3D_Transform.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_Quaternion:
        final ptr = RP3D_Quaternion.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_Ray:
        final ptr = RP3D_Ray.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_RaycastInfo:
        final ptr = RP3D_RaycastInfo.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_Collider:
        final ptr = RP3D_Collider.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_CollisionShape:
        final ptr = RP3D_CollisionShape.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_Material:
        final ptr = RP3D_Material.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_AABB:
        final ptr = RP3D_AABB.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_BallAndSocketJoint:
        final ptr = RP3D_BallAndSocketJoint.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_BallAndSocketJointInfo:
        final ptr = RP3D_BallAndSocketJointInfo.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_HingeJoint:
        final ptr = RP3D_HingeJoint.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_HingeJointInfo:
        final ptr = RP3D_HingeJointInfo.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_SliderJoint:
        final ptr = RP3D_SliderJoint.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_SliderJointInfo:
        final ptr = RP3D_SliderJointInfo.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_FixedJoint:
        final ptr = RP3D_FixedJoint.stackAlloc();
        return ptr.toDart() as T;
      case RP3D_FixedJointInfo:
        final ptr = RP3D_FixedJointInfo.stackAlloc();
        return ptr.toDart() as T;
      default:
        throw Exception("Unsupported type: $T");
    }
  }
}

extension StructPointer<T extends Struct> on T {
  Pointer<T> get address => _address as Pointer<T>;
}

Pointer<T> getPointer<T extends NativeType>(TypedData data, JSObject obj) {
  late Pointer<T> ptr;

  if (data.lengthInBytes < 32 * 1024) {
    ptr = stackAlloc(data.lengthInBytes).cast<T>();
  } else {
    ptr = malloc<T>(data.lengthInBytes);
  }

  return ptr;
}

extension JSUint8BackingBuffer on JSUint8Array {
  @JS('buffer')
  external JSObject buffer;
}

extension JSFloat32BackingBuffer on JSFloat32Array {
  @JS('buffer')
  external JSObject buffer;
}

@JS('Uint8Array')
extension type Uint8ArrayWrapper._(JSObject _) implements JSObject {
  external Uint8ArrayWrapper(JSObject buffer, int offset, int length);
}

@JS('Int8Array')
extension type Int8ArrayWrapper._(JSObject _) implements JSObject {
  external Int8ArrayWrapper(JSObject buffer, int offset, int length);
}

@JS('Uint16Array')
extension type Uint16ArrayWrapper._(JSObject _) implements JSObject {
  external Uint16ArrayWrapper(JSObject buffer, int offset, int length);
}

@JS('Int16Array')
extension type Int16ArrayWrapper._(JSObject _) implements JSObject {
  external Int16ArrayWrapper(JSObject buffer, int offset, int length);
}

@JS('Uint32Array')
extension type Uint32ArrayWrapper._(JSObject _) implements JSObject {
  external Uint32ArrayWrapper(JSObject buffer, int offset, int length);
}

@JS('Int32Array')
extension type Int32ArrayWrapper._(JSObject _) implements JSObject {
  external Int32ArrayWrapper(JSObject buffer, int offset, int length);
}

@JS('Float32Array')
extension type Float32ArrayWrapper._(JSObject _) implements JSObject {
  external Float32ArrayWrapper(JSObject buffer, int offset, int length);
}
@JS('Float64Array')
extension type Float64ArrayWrapper._(JSObject _) implements JSObject {
  external Float64ArrayWrapper(JSObject buffer, int offset, int length);
}

extension Uint8ListExtension on Uint8List {
  Pointer<Uint8> get address {
    if (this.lengthInBytes == 0) {
      return nullptr;
    }
    if (_allocations.contains(this)) {
      return Pointer<Uint8>(
        NativeLibrary.instance._emscripten_get_byte_offset(this.toJS),
      );
    }
    final ptr = getPointer<Uint8>(this, this.toJS);
    final bar =
        Uint8ArrayWrapper(NativeLibrary.instance.HEAPU8.buffer, ptr, length)
            as JSUint8Array;
    var now = DateTime.now();
    bar.toDart.setRange(0, length, this);
    var finished = DateTime.now();
    return ptr;
  }
}

extension Float32ListExtension on Float32List {
  Pointer<Float32> get address {
    final ptr = getPointer<Float32>(this, this.toJS);
    final bar =
        Float32ArrayWrapper(NativeLibrary.instance.HEAPU8.buffer, ptr, length)
            as JSFloat32Array;
    bar.toDart.setRange(0, length, this);
    return ptr;
  }

  Uint8List asUint8List() {
    var ptr = Pointer<Uint8>(
      NativeLibrary.instance._emscripten_get_byte_offset(this.toJS),
    );
    return ptr.asTypedList(length * 4);
  }
}

extension Int16ListExtension on Int16List {
  Pointer<Int16> get address {
    if (this.lengthInBytes == 0) {
      return nullptr;
    }
    final ptr = getPointer<Int16>(this, this.toJS);
    final bar =
        Int16ArrayWrapper(NativeLibrary.instance.HEAPU8, ptr, length)
            as JSInt16Array;
    bar.toDart.setRange(0, length, this);
    return ptr;
  }
}

extension Uint16ListExtension on Uint16List {
  Pointer<Uint16> get address {
    final ptr = getPointer<Uint16>(this, this.toJS);
    final bar =
        Uint16ArrayWrapper(NativeLibrary.instance.HEAPU8.buffer, ptr, length)
            as JSUint16Array;
    bar.toDart.setRange(0, length, this);
    return ptr;
  }
}

extension UInt32ListExtension on Uint32List {
  Pointer<Uint32> get address {
    if (this.lengthInBytes == 0) {
      return nullptr;
    }
    final ptr = getPointer<Uint32>(this, this.toJS);
    final bar =
        Uint32ArrayWrapper(NativeLibrary.instance.HEAPU8.buffer, ptr, length)
            as JSUint32Array;
    bar.toDart.setRange(0, length, this);
    return ptr;
  }
}

extension Int32ListExtension on Int32List {
  Pointer<Int32> get address {
    if (this.lengthInBytes == 0) {
      return nullptr;
    }
    if (_allocations.contains(this)) {
      return Pointer<Int32>(
        NativeLibrary.instance._emscripten_get_byte_offset(this.toJS),
      );
    }
    try {
      this.buffer.asUint8List(this.offsetInBytes);
      final ptr = getPointer<Int32>(this, this.toJS);
      final bar =
          Int32ArrayWrapper(NativeLibrary.instance.HEAPU8.buffer, ptr, length)
              as JSInt32Array;
      bar.toDart.setRange(0, length, this);
      return ptr;
    } catch (_) {
      return Pointer<Int32>(this.offsetInBytes);
    }
  }
}

extension Int64ListExtension on Int64List {
  Pointer<Float32> get address {
    throw Exception();
  }

  static Int64List create(int length) {
    throw Exception();
  }
}

extension Float64ListExtension on Float64List {
  Pointer<Float64> get address {
    if (this.lengthInBytes == 0) {
      return nullptr;
    }
    final ptr = getPointer<Float64>(this, this.toJS);
    final bar =
        Float64ArrayWrapper(NativeLibrary.instance.HEAPU8.buffer, ptr, length)
            as JSFloat64Array;
    bar.toDart.setRange(0, length, this);
    return ptr;
  }
}

extension AsUint8List on Pointer<Uint8> {
  Uint8List asTypedList(int length) {
    final start = addr;
    final wrapper =
        Uint8ArrayWrapper(NativeLibrary.instance.HEAPU8.buffer, start, length)
            as JSUint8Array;
    return wrapper.toDart;
  }
}

extension AsFloat32List on Pointer<Float> {
  Float32List asTypedList(int length) {
    final start = addr;
    final wrapper =
        Float32ArrayWrapper(
              NativeLibrary.instance.HEAPF32.buffer,
              start,
              length,
            )
            as JSFloat32Array;
    return wrapper.toDart;
  }
}

int sizeOf<T extends NativeType>() {
  switch (T) {
    case Float:
      return 4;
    default:
      throw Exception();
  }
}

typedef IntPtrList = Int32List;
typedef Utf8 = Char;
typedef Float = Float32;
typedef Double = Float64;
